#!/usr/local/bin/perl

use Bio::EnsEMBL::DBSQL::DBAdaptor;
use strict;

use Bio::EnsEMBL::Pipeline::GeneConf qw (
                                         GB_DBHOST
                                         GB_DBUSER
                                         GB_DBNAME
                                         GB_DBPASS
                                         GB_PFASTA
                                         GB_TMPDIR
                                        );
$| = 1;

my $db = new Bio::EnsEMBL::DBSQL::DBAdaptor(-host => $GB_DBHOST,
                                            -user => $GB_DBUSER,
                                            -dbname => $GB_DBNAME,
                                            -pass   => $GB_DBPASS);

my $sa = $db->get_SliceAdaptor;

my $chunk = 20000000;

foreach my $chr (@{$db->get_ChromosomeAdaptor->fetch_all}) {
   my $start = 1;
   my $length = $chr->length;
   my $chrname = $chr->chr_name;
 
   while ($start <= $length) {

      my $end = $start + $chunk - 1;

      if ($end > $length) {
         $end = $length;
      }

      my $cmd = "bsub -q yesterday -R\'ncpus>1' -o $GB_TMPDIR/$chrname.$start-$end.out -e $GB_TMPDIR/$chrname.$start-$end.err pmatch_proteome -chr $chrname -chrstart $start -chrend $end ";

      if (! -e "$GB_TMPDIR/$chrname.$start-$end.out") {
        print $cmd . "\n";
      } 
      $start += $chunk;
    }
}
