## Bioperl Test Harness Script for Modules
##
# Before `make install' is performed this script should be runnable with
# `make test'. After `make install' it should work as `perl test.t'
#-----------------------------------------------------------------------
## perl test harness expects the following output syntax only!
## 1..3
## ok 1  [not ok 1 (if test fails)]
## 2..3
## ok 2  [not ok 2 (if test fails)]
## 3..3
## ok 3  [not ok 3 (if test fails)]
##
## etc. etc. etc. (continue on for each tested function in the .t file)
#-----------------------------------------------------------------------


## We start with some black magic to print on failure.
BEGIN { $| = 1; print "1..5\n"; 
 use vars qw($loaded); }
END { print "not ok 1\n" unless $loaded; }


use Bio::EnsEMBL::Pipeline::Runnable::EPCR;
use Bio::PrimarySeq;
use Bio::Seq;
use Bio::SeqIO;

BEGIN {
    require "Bio/EnsEMBL/Pipeline/pipeConf.pl";
}

$loaded = 1;
print "ok 1\n";    # 1st test passed.
my ($seq) =  set_seq();


my $clone =  Bio::PrimarySeq->new(
    -seq         => $seq,
    -id          => 'AC025422.19.99723.113695',
    -accession   => 'AC025422.19.99723.113695',
    -moltype     => 'dna'
);
unless ($clone) 
{ print "not ok 2\n"; }
else
{ print "ok 2\n"; }

#create EPCR object    
my $sts_db = $::pipeConf{'datadir'} . '/mapprimer';
my $epcr = Bio::EnsEMBL::Pipeline::Runnable::EPCR->new(
    -CLONE   => $clone,
    -DB      => $sts_db,
    -OPTIONS => 'M=1000'
);
 
unless ($epcr)
{ print "not ok 3\n"; }
else
{ print "ok 3\n"; }

#run EPCR                                                
$epcr->run();
print "ok 4\n"; # 4th test passed

#get and store the output
my @results = $epcr->output();
display (@results);

unless (@results) 
{ print "not ok 5\n"; }
else
{ print "ok 5\n"; }

#Display output
sub display {
    my @results = @_;
    #Display output
    foreach my $obj (@results)
    {
       print STDERR ($obj->gffstring."\n");
       if ($obj->sub_SeqFeature)
       {
            foreach my $exon ($obj->sub_SeqFeature)
            {
                print STDERR "Sub: ".$exon->gffstring."\n";
            }
       }
    }
}

sub set_seq {
#embedded sequence! Because I can't create Bio::PrimarySeqs from files
my $seq = 
'TCCTTTAGTCCTTACATCTCTATGAGTTAGGTATAAGGCATTTGAAAAATAAGAAGACAG'.
'AGGTAAGGCAGAGCAGTGATTTGCCCAGGGTTAGGCAGCTTGAGAGTGATGGAGCGAGGA'.
'TGTAACTCCTGAACAATCTAGCTTGAGTCCATACTCAGGCTCTTCAAGATGCTGGAGCTG'.
'AACCTTAAGAATGAATTCATGCCAGGAGCAGTGGCTCACACCTGTAATCCCAGCACTTTG'.
'GGAGGCCGAGGCAGGTGGATCACCTGAGGTCAGGAGTTCAAGACCAACCTGACCAATATG'.
'GTGAAACCCCGTCTCTACTAAAAATACAAAAATTAGGCCGCCTGTAGTCCCAGCTACTTG'.
'GGAGGCTGAGACAGAAGAATCACTTGAACCCAGGAGCTGGAGGTTGCAGTGAGCCAAGAT'.
'GGTGCCAGCGCACTCCAGCCTGAGCGACAGAGCAAGACTCCATCTCAAAAAATAATAATA'.
'ATAATAATAATAATAATAATAATAATAATAATAATAATTCACTGGGCAGGTAAGGGAGAG'.
'GTCTTCCAGACAGAGGGAACAGCTCATACAAAAGCATGGAAACACAAAAAGACATGTTTT'.
'GGGAAGTGAGCTTAGTGGTGGAATCACAAGGAATGTTAACTAGATCCAGCTGGGACTAAA'.
'CATTTTTTTCTTTTTTTTTTTTGAGACGGAGCCTCGCTCTGTCTCCAGGCTGGAGTGCAG'.
'TGGCGCAATCTTGGCTCACTGTAACCTTTGCCTCCCGGGTTCAAGTCAATTCTCCTGCCT'.
'CAGCCTCCTGAGCAGTTGGGACTACAGGCGTGTGCCACCATGCCCAACTAATTTTTGTAT'.
'TTTTAGTAGAGATGGGGTTTCACCACGTTGGCCGGGATGGTTTTGATCTCTTGACCTCGT'.
'GATCCGCCTTGGCCTCCCAATGTGTTGGGATTACAGGCGTGAACCACCGTGCCTGGCCTA'.
'CTAAACACTTTTATGGTTTTTTTTTTTTTTTTGAGATGAAGTCTCGCTCTTGTCCCCCAG'.
'GCTGGAGTGCAATGGCACGATCTCAGCTCATTGCAACCTCCGCCTCCCAGGTTCAAGCAA'.
'TTCTCCTGCCTCAGCCTCCCGAGTAGCTGAGATTACAGGCACCTGCCACCACGCCCGGCT'.
'AATTTTTTGTATTTTTAGTAGAGGCTGGGTTTCACCATGTTGGCCAGGCTGGTCTCGAAC'.
'TCCTGACCTCAGATGATCCACCCGCCTCAACCTCCCAAAATGCTGAGATTACAGGCATGA'.
'GCCACTGTGCCTGGCCAGTTTTATGTATTCTTTAGACTAGTGGTTTCCAAAACTAAAGTT'.
'TTCTCTAAAGCTGTGGACCTTCTCCCCCAGATAATTTTACATAGAATGCAATATATAAAG'.
'CAGTTAAAAGCGGAGTTATTCTCTAACGGAAAAGTACCAAGGGCACTCCAATTTGGCCAG'.
'CTTTTGGGGTTGCACAGAAAAGTTTGAGAACCACTAAAAAGCCTGTTACCTTGAGTATGA'.
'GCTCTAAGCCAATGGCAAATCCTGGCTCTATCACTAAGTTGGAAACTTTGGACAAATTAC'.
'TTAAGCTCTGTGGCTCAGCACCCTCACATGAAACATGAGATTAATAATACTCCCATATCC'.
'ATAGGGTTGCAAGGAATGAACTAGTAAGCCACTTTCCCACAATTCCATGACTATACATTG'.
'ATTAGACCTCTTCTTCCCCTTTAACTCTTTACTCATCCTTTAAACCCATTTCCCTTCTTC'.
'CTGAAGTTTCCCGATATCCTTAGTGTGCGACAGATAACCCTCCTGTTTCCACAGCACCTG'.
'TTACTTTATACTACTATTGCTGTAGCAGTTCCCCTTTTCCTGAGTTGGGGAATGTATCCT'.
'TTCTTTGTCTTTGTCCTATGTAGAAAATTAAAACTGGCAATGCTGTCAATGCAAGTGCTG'.
'GGGCAACTGTAGACAGACATGTCCTGGCCCTTGAGAAATTAGTATCTAGGTAGAAGGCAG'.
'CAGAAAACAAGGGACTGGCTGTCTAGGTGAAAAAAGTGGCAGGAACACAGGCACACAGAT'.
'CTGAGTTGTTAGGCTAGAGTAGTGCTGTCTATCACTGCAAGCAAGCCACAGATGTCATTT'.
'TAAATGTTCTGGTAGCTCTATTAAAAAAAGAAACAGATGAAATTAACTTTAATGCATTTT'.
'ATTTAACCCAACACATATATTTCAACATGTAATCAGTATCAAATATTTTTGACATATTTT'.
'ACATTTTGTGTGCTGTCTTAGAAATCTGCTGTGTATTTTACACTTACATTACATCTCAAT'.
'TGAGACTAGTCATATTTCAAATGAGTCCTATGTGACTAGTGACTTCGGTACTAGTAGTCC'.
'AGGGCTAGAGGAAAATGTTCATACGGAAGAGTAACAGAGGTTCAAGTTGGAGGTAGGGGT'.
'CAAACTAGAGGGGGTCTGAATGCCACTAAAGAAAGTGGAAAGCCTTTGAAGGATTTTGAG'.
'TTGATTGTAAAGTTAATCTAGTGGTTAACACAGGATTAAGAGACCATCCTTAATGCCACT'.
'GTAGCAATCCTTCCTTCATTTCATTGAGGCTGTTCCACTCTGTCACAGCTTATCACTGGT'.
'GGTGCAGACTGCTTTTCCAAGCATGTACTTTTGTACCTTACCAACGGGTCTGGTAGGTAG'.
'TGAGGACTGAGCAATCAGGACAGCAGTATGCAGATGCTTCCCTCTTCAGATGACACACTC'.
'TTAGGCATGGCTGGGCACTAAAAAAGGTCCTTTGACAATGTTGGTGAAAGCTGAGATTCA'.
'GCCAGAGTATCAAACAGTGCGGATTGATGTGCCACAGGTACAATGTCAAGTATGACTCAG'.
'AGGACAAATTATCTAGATCCTTCTAATAATAGCATGTACCCCAACAACTGGATTCCTTAG'.
'TATTCTTCAAAATCTGAGGTAAAATCACTCTCGCTTTAAAAGATACCAACTTCACCCCTT'.
'CCTCTCTTCCCAACTCCCTCCTGCTTCCTTAAGGATCCATGCCAGCTAGCAGGTAAACCA'.
'GAGGCTGACTTGCTGACATCTTCCTTACCTTATTCCTCAGGTATACATCCTAGGCAGGGA'.
'AAATTTACAGAATGCATCCCAGCCTGATTTTGGAAGAATGAGAAAGTTATCTGAGGGCTC'.
'CCAAGGGCCTCCTGTGCATACCATCTTTATCTTCCAACTTAGAACTAACCAAATTCAGTC'.
'TTTTTGTGTAATGAAAAAAGGATAAGCTGGGCACAGTGGCTCACACCTGTAATCCCGGCA'.
'CTTTGGGAGACCGAGGCGGGAGGACTGCTTGAGCCCAGGAACAAGACCAGCCTGGGCAAC'.
'ATAGCGAGACCTTGTCTCTATACAAAAATAAAGAAGAAAAAAGGATGCAGGAAATTAACA'.
'ATAGGATAGCCAACACCCTCACTAAAGCATCAATTTCCATATGATGTTAAGTACCAGGTA'.
'GAAATCTCTCTGACTTTAAGGAGCTTTGGACACAAAAACTTTTCCTTAAACAAGCCATTT'.
'ATTTTCTAAACATGGACTTCCACTAGTTGTGTAACTCTCCTAGAATTCTAGCCAATATTT'.
'AATAATTGTTGCCACACTTTTGTATTTCAACTTAAGTATTTTATATTATTAAAAACTACC'.
'AATTATCTTAACAAACCTGCACATGGAGGGAGAGGTATATGAAACTCAGCCCACTAACTA'.
'GACCAAAATCCTCCTCAATGACACTAAGGTTGTAATACTAAAAAGTCCCAATCACCCTCC'.
'CAGGATTCTATTAAAGCAAGCTGTGGTTAACAGACAAGATGCCTTTTTCGTCATCATTTT'.
'CAAAAGCATTGTCACTTTTTTTCCAAGACACAACTTCTTTGAACCTGTTTCATAACCTAT'.
'CATATAAATACCAGCCTCAATACTGCTATCAAGATTAAACAATGAACAAAAAAGTGTTTT'.
'ATAAGTAAGAGTGGACAATGTGAGTTTTTATTGTTTGGCTCATTAGAAATGTTCTTGGCC'.
'ATCTCATGCAGGAACAGCTGGAGGAAATGGAAGAACGCCAGAGGCAGTTAAGAAATGGGG'.
'TGCAACTCCAGCAACAGAAGAACAAAGAGATGGAACAGCTAAGGCTCAGTCTTGCTGAAG'.
'AGCTCTCTACTTATAAGTCAGTTTCTGCTGCTATACAAATCTCATCTAATACTGGCTGAG'.
'GGGATGGTGGGAGGGCTTAGGGAAAATTTTACCTTAGAATCAAAAACAAAAAGAGGATTT'.
'GGGAAATGATTTTCAAATTGTGCTTATCCAAAAACACATGGAAAATGGCTCTCTCTTTTT'.
'AAAGGGCTATGCTACTACCCAAGAGCCTGGAACAGGCTGATGCTCCCACTTCTCAGGCAG'.
'GTGGAATGGAGACACAGTCTCAAGGTGATCTTTGTGAAGAGAAGAGTGGTGTTTGCATTG'.
'TTACTGCTTTCCTAACAATACTAATTAATGCCTTAAAAACAGGCCGGACGGGGTGGCTCA'.
'CGCCTGTAATCCTAGCACTTTGGGAGGCTGAGGAGGGTGGATCACCTGGAGTCAGGAGTT'.
'CAAGACCAGCCTGGCCAACATGGCAAAACTCCATCTCCACTAAAAATACAAAAATTAGCC'.
'GGGCATAGTGGCAGGCACTTATAATCCCAGCTACTCAGGAGGCCAAGGCAGGAGAATCGC'.
'TTGAACCAGGAGGCAGAGGTTGCAGTGAGTCAAGATCACAATACAGCACTCCAGCTTGTA'.
'CAACAGAGTGAGACTGCCTCAAAACAAAACAAAAACCCAAAAAACAAAAACAACAAAAAA'.
'CCCTTGTGTGCCTAATGACAAGGGGATAACCCAAACCTCCAAAACGCCTGAGTCAGGCAT'.
'TCAGAGTTCATTTGGAATGTTTGTTTCTAGTAGGACTCAAAATATGCCCTGATTATCACC'.
'ATGAATTCTGTGGCATCTAGGCTTTGGGCATCTTGTTTCCTCATCCTACCCTACCCACCT'.
'GCTATTCTCAGTTTTCCTTATAATAGCAGAGAAAGCAGTTGTGCTATCAAAAATAATAAA'.
'CATATCTATCCATTAAGTTCCTTATATAATATTCAAAGGCTGTGGTTTTGGGTGGAAGCA'.
'GAGATGTTCATGTTACACAGACTTACTCTTTTTTTTTTTTTTTTTTTGAGACGGAGTCTT'.
'GCTCTGTTGCCAGGCTGGAGTGCAGTGGCGTGACCTCTGCCTCCCGGGTTCAAGCGATTC'.
'CCCTGCCTCAGCCTCCCAAGTAGCTGGGATTATAGGCACGCACCACCACGCCTGGCTAAT'.
'TTTTTTGTATTTTAGTAGAGACGGGGTTTCACCATGTTGGCTAAGATGGTCTCATCTCCT'.
'GACCTTGTGATCCACTTGCCTCGGCCTCCCAAAGTGCTGGGATTTCAGGTGTGAGCCACC'.
'ATGCTTGGCCTAAACAGACTTAACTTTTAGACACTGACAAAACTGAAGGCATCTTTCTGA'.
'CCAATCACCTACTCAGGATCCCTCCCCCAATGTTTTACCAGTATATTCTGATAAAAGTTC'.
'TAGAGTCCGTGAAAGAAACTAAGGATAAAAGAAAGTCCGTGTCAAGTTGTACATTATACA'.
'GATGCCTATAAATTTTATTCATTTCCTAAGCTTACATCAAATTCACAACTTTCTTTTTTT'.
'TTTGAGACAGAGTCTCGCTCTGCCACCCAGGCTGGAGTGCAGTGGCACGGTCTCAGTTCA'.
'CTGCAACCTCCACCTCCTGGGTTCAAGTGATTTTCCTGCCTCAGCCTCCTGAGTAGCTGG'.
'GACTACAGGAGCATGCCACCACGGCCAGCTAGTTTTTGTATTTTTAGTAGAAACGGGGTT'.
'TCACCATCTTGGCCAGGCTGGTCTTGAACTCCTGACCTTGTGATCCACGTGCCTCAGCCT'.
'CTCAAAGTGCTGGGATTACAGGCGTGAACCACCGCGCCTGGCCCACAAGTAACTATTGTT'.
'GCTTTTTCTAATTTTCTAGGATTTTATTTCATTTTTTTAAATTTCTTTTTAGTAGAGATG'.
'GGGGGTCGGGTCTTGCTATTTTGCCCAGGCTGGAGTAGTGGCACGATCTTGGCTCACTGC'.
'AACTCTGCCTCCTGGGTTCAAACAATACTCCTGCCTCAGCCTGCTAAGTAGCTGGGATTA'.
'CAGGCATAAGCCATCACACCCAGCCTTGAGGATTTTCTTATACTGTGTTTGAATCCACAT'.
'GACTGATAATATGCTTAATGTTTGAGAAATTATAACCTTGCAATTGAGGTTAATGATCTA'.
'CTAACTACCTTTGTGTTGATCAGATTGTGTACAATCTGGAAAAGACAACGACTAATCCAA'.
'AGAAATGAAACTACAGAATTTCAGGCATTGTAATTATACCTGTAAGAAGTTAACCTAGCA'.
'GAGAAAACGTTTAACTATCCCTCCCATCACCATCACCATTCATTCTATTTGACAAACAGG'.
'AGGCATCCAAATATTTGCTAGGGGAAAGTCATCCCTGATCATCCATAAATCACACTGTAA'.
'CAATCTCTTCTCAACAAAGCCTGCAGTAACTAAACCTCAGAAGTTCACTGTTATAAACTT'.
'TTTCTTTCAACTTTACAGGGGCTGTTTAGAAATATATGGCCAAATCTGTAACCCGGAAAC'.
'AGCAAAAAACTTCTTAGCAAAGGATCACTAAGTACCCTTTGGATGTACTCTTCCAACCAG'.
'ACAAGAGTGCCAGAAACTTGGCAAGCAATTCATCCTGTGGAAGTTGCAAATACTGGCTGA'.
'CCTGCTTAAAAAGATTCTAGAGTTGGCCGGAGGCAGAACATGTCAACTCTTTGCTGGATT'.
'CTATTTCATCTGCTGTTGATACTGATCTCAATGCACCAAGGAAAGGAAAGATGAGCCTCC'.
'TGTCTTCCAGCAACAACCCTCACATATGCACTGAGTAAAGGATGAATGTATGGACACATC'.
'TGGGAGTATTTTAAAGAATGTATCTTGCCTTGTGTTGACCCAAACCAAAAACATTTTTGA'.
'GGGGCACATGTGGGGTCAAAAAGATAGCCAATTTCCATTACATGGGTTTACAATTTCCAT'.
'TCTTTTGTGCCACGAGTGTTAGAATTTAAATGAATACTTTTACAAAGTCTACTTTTTGTT'.
'CAAGGATATGCTGACCCATATAGTTTACTCTTAAAATTGTGTCAAGGTATTTCTCACTAT'.
'ACTCTAAAACAACTAGACTTGAAAAGAAACCATTTGAGATTTGAATCTAATGGTTAACGC'.
'TATTCAGATTTTCCCAAAGATCTTACCTCATGAAAGTAGTTCTGGGTCAGAATGATCTAC'.
'TCAGTTAAAAAACAACAACAACAAAAAACTAAGCGATTGGGAAAAAACAGGAATTTTATC'.
'TGGTTATTGCATCTGGTGATAGAGGCCTTCAAAGCCTATTATTTCTAACCTAAGTAAAGG'.
'CCCCAGTGAAAAACATACTGGGGAAATAAAACCTCTGAGAAAAGGTTCAAGCACCTTTTC'.
'CAAATTTAAATCTTGCCTTAAATTCTCTCTACCACACTGCCTTTGACACTCTTGGAAGTC'.
'CATGTAGTTCTCTACAGACAGACTTCAAAGAAACGTTACCTTATCAAAGACTAATCTGTG'.
'CCACCTCTGATTCAGTGTTTTATGTCTTTCACTTTCCCTGGGAAGGAGTAAAGTTCTTTT'.
'CTACAGCTCTGGGACTATTACATTTAATTCTGCTCTTGATAGTCAAAGACATGGACAACA'.
'ACTGTCATCTGAAGGACTCTTCTAGAAGCCAGAGACTGGTGTTTGATGGATGTTTTATAC'.
'TAAATAAAACCCATCAGCATGGGGTTATGTAGAAAAGCAATTTATTCCATTTTAAGCACT'.
'TACACAGTTAGTCATGGAGAGTAACAGGCCTGCTGGTGAAACAGGTCACCCAAAATGGAG'.
'ATGGCATCAAACTAGTGGTCAAGGACTAACTCCTAAAAAAAAAAAGCAACTCTTATCAAG'.
'GATTAATTTAATTTTTAAAACAAATACAAGTTATTGATTCACTCTTCTCAACTTGACAGT'.
'CTACCTGTGGTATAACTGTCAGGTAAAAACATACATCTTTACAACTTGGTGGTCCCAAGT'.
'TAAAAAAAAAAAAAAAAAAAACCAACAAAAAAAAAAAAAACACCATTTCACAGACAGGAA'.
'ATAAACAACATGAAAACAGCTCAAGAAATACACTAACGAGCAAAAATATATGAATATATG'.
'GGGAAAGAGGAACGTGTTGTTTTGACTTAACTGAAGAAACCAAGAGGAAACTGGTCTACG'.
'TATGAAAATGTGCATCCTGGAAAGTCAGGTGTCAAGATTTTCGAGTAGGAATCTATATGA'.
'CTTGAATCTCCCCCTATTTCCTGAATAAAAGTGACATCTTTCAGTATTTATACTTCATGG'.
'CTCAGACACCTACCTCATTTGGCTCTATTCCTTACTCACTCTAGCCTTTACTTAAATGAG'.
'TCTGAAAAACTTGGGGATATAGCATAAGAAGAAAAATAATCACACATAATATTCCCCTTT'.
'CTGTAGCTACTTTAGACCTGGGTTACTAGAAAATTCCTGAAGAAAATTTCAACGTTAAGT'.
'CTGTGGCTTTGTTGAATCAAGCCCCCCTATTAATATTTAGAAAACACCCACGGTTTGGGC'.
'TAATAGCATTATCGGTGGTACCTATTATATAGAGGGATAGCTGAATAAAGTCTGTCTCAA'.
'AACCAGTGTTAAATCACTCTCAGGGTTGAGAAGAAAAAAGGGGAGTCTAAAATCACAACA'.
'AGTAAAGACATATCTAGGACCCTTGTCCTTCTGGATCCACGCTTCCTTCAGGGTCTTCAT'.
'CATTATAAATGTTCTCTGCCTGCCCAAAAACAAGAAAAAGAATTTAAACATGAAGACTTC'.
'TTCTAAAACTCAAGGTTTCAACAACAGATTAGGCCAGGAAGCCAGAGAGTAAATACTTTA'.
'TAGCTTTTGGGCCACACAATCTGTGTTACAACTATTCAACTCTTGGATGAAAGTATCCGG'.
'AGACAACCTATAATGGGTAATGAAATATTAATTAGCATGATCATGTTCCAATAAAAATAA'.
'GCAGCTGATCCCCAGACGCCTGATTAGGACATTCCCACAAAACTGCAGTGTGGATACTAT'.
'TTGTCTTGATAGCCAACATTCTTGAGTTCTTTAACCAGGCATTATTATTTTTCTTTCCTT'.
'TTGAGATGGAGCCTTGCTCTGTCTCCCAGGCTGGAGTGCAGTGGCACCATCTCGGCTCAC'.
'TGCAACCTATGCCTCCCAGATTCAAGCAATTCTCCTGCCTCAGCCTCCAGAGTAGCTAGG'.
'ATTACAGGCACATGCCACTACGCCTGGCTAATTTTTGTATTTTTAATAGAGATGGGGTTT'.
'CACCATGTTGGCCAGGCTGGTCTCGAACTCCTGATCTCAGGTGATCTGCCCACCTCGGCC'.
'TCTCAAAGTGCTAGGATTATAGGAGTAAGCCACTGTGCCCAGCCTAACCAGACATTATTA'.
'ATAATAGCCAAAAAGTAAAAACAACCCAAATATCCATCAACTACTAAAATGGATACACGG'.
'TATATCCAATCCATATGATGGAATATTATTTGGCATAAAAAAGCCAGTCAGGCCAGGTGT'.
'GGTGGCTCATACCTGTAATCCCAGCACTTGGGAGGCTGAGGCAGACAGATCACTTGAGGT'.
'CATGAGTTTGAGACTAGCCTGACCAACAAGGCGAAACTGCATCTCTACTACAAATACAAA'.
'AATCAGCCATGTGTGGGGGTGCACCCCTGTGGTCCCAGCTACTTGGGAGGCTGAGGCATA'.
'AGAATTGATTGAACCTGGGAGGTGGTGGTTGTAGTGAGCCAAGATTGCACCACTGCACTC'.
'CAGCCTGGGTGGCAAAGCAAGACTGTGTGCCAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'.
'AAGCTGTCACATACTTTAGGATTTTATTTATATAAGGTGTCCAGGCCAGGTGTGGTGGCA'.
'CACGCCTGTAATCCCAGCATTTTGGGAGGCCAAGGCAGGCGTATCACCTGAGGTCAGGAG'.
'TTCGAGACCAGCCTGGCCAACATGGTGAAACGCTGTCTCTACTAAAAATATAAAAATTAG'.
'CCAGGCGTGGTGACAGGCGCCTGTAATCCCAGCTATTTGGGAGGCTAAGGCAGGAGAATC'.
'GCTTGAACCCAGGAGGCGGAGGTTTCAGTGAGCCGAGATCACACCACTGCACTCCAGCCT'.
'GGGGGGCAAGACTTCGTCTAAAAAAAACAGGGGTCCAAAACAGGCAAATCCATAGCTTGG'.
'TGGCTGCCTAGGGCTGGGGGACTATGAGAAAAATAGGAAATGATGGCTAATGGGTACAGG'.
'GTTTCTTTTTCAGATGATGAAAATGTTCTCAAATTGACTGTGGTTGATGGTTGCACAACT'.
'GTAAATACACTGAAGACTGCTGAACTGCACACTTAAAACTTCCAAAACAATATGTTCCGA'.
'ATCTCTATATATTGAAGAGAAAAACTGTTCTTGTATAGAATAAACTCTACTTCTACTGCT'.
'TGACAGAATACCTGTATCCAACGGCATAATCTTAAAATACAGGAACCACTTTCACAGGAG'.
'CAAAATTTACTGCTCTTAGCACCTACCATGCACATATCACTATGATAGGTACTGCAGAGG'.
'ACAGGATAGTCTTACCTTCAAAGAGCTTGTGATCTGACCCCAGAGAAAAGAATACATACA'.
'ATTGTGTGATGCTTTCTGACGTTACTTCTAACACCAAATGTGGGGTACCCTTTCTTAGGA'.
'CACCAACTGGGTGTACAACAACTCAATCCTATTCTGACACTATCTGAAGTTAGCTTTGGA'.
'GAAGACTGTCCTTACTTCAGAAGCCAGTTGCAATTCCCTGGTCCCAGGCTACCTGCACAC'.
'TTCTATCCCACTTGACTACAAATTTCAGGGTTCCCACTACTGCCTCCTCAGGTCTGATAA'.
'TTTGATGGAATGACTCACAGAACCCAAGAAAGCTTTTTACTATTACTGTTTTTTGTTTGT'.
'TTTTTGTTTTGTTTTTTTTTTTTAAATAAAGGATACAACTGAGGAACCACATGGAAGAGA'.
'TGCATACGGCAAGGTGGGGAGGGGCTGCAGAGTTTCCATCAAGTCTCTGGGCATGCTACC'.
'CACCCAGTATGTCGAGTTGTTCACCAATCCAGAAGCACATCAAATTAGGAGTTTTTATAG'.
'AGTTCAATCTCTGGCCCTGCAACCCCAAGGTTGGCAAGTGGGCTGACAAGTTTTAACCCT'.
'CAAATCAAGTGATTGGCCTTTCTGACTAAACCAACTATGAGGCTATCTAGGGGCCCCACC'.
'AAAATCACCTCACAGTAGAACAAACTCAGGTGTGGTCCAAAGTGGATCACTAGGAACGAC'.
'AAAGACACTCCTAGCACTCTGCAAACTCCGAGTGTTTTTGGAGAGCTCTGTGCCAAGAAC'.
'TGGGACAAAGACCAAATATTTACTTACTCTATTACAATGCTAAAAACACCAAATAAAGTA'.
'ACAACTTGGAATGGAGGTGATGGCCTTGCAGGGATCTAGTTTAACCTTGAATTCTTCAGT'.
'ATTTTTTTTTTGAGACAGGGTCTCGCTCTGTCACCCAGGCTGGAGTGCAGTGGCGCCATC'.
'TTAGCTCACTGCAACCTCTGCCTCCTGGGATCACGCTAGCCTCCCACTTCAGCCTCCCAA'.
'GGAACTGGGACTACAGGTACGTGCCATCACGCCCAGCTATTAAGTTTCTGTATTAATATT'.
'GAAGGGATTTATTACAAAGAGAGTGAGGTGAATTTTCTGTTTTCAAGTTACACATCTTTT'.
'TTGTAAAAAAATTATAATACAGAAAGGTCTAAAGAAACCAAGAACTAGGTACCAAGCACA'.
'TTTTAGCAAACAGCTTTTTTCTTTTTTTTTTTTTTTGAGATGGAGTTTTGCTCTTGTTGC'.
'CCATGTTCGAGTGCAATGGTGCGATCTTGGCTCACCGCAACTCCTCCGCCTCCTGGGTTC'.
'AAACAAGTCTCCTGCCTCAGCCTCCCAAGTAGCTGGGATTACAGGCGCCCGTCACCATGC'.
'CTGGCTAATTTTTGTATTTATTTTTTAGTAGAGATGGGGTTTCACTATGTTGACCAGGCT'.
'GGTCTCAAACTACTGACCTCAGGTGATCTGCCCACCTCGGCCTCCCAAAGTGTTGGAATT'.
'ACAGGCGTGAGCCACCACACCTGGCCAGTAATCAGCTTTCTAAATATAGACTAGATACAC'.
'AAAATTTTAATATGAGGAATACCATTATGCTATTCTTCAGTCTGCGCTTCCCCTTTAACA'.
'GCATGTCATGAATATCTTATAACCCTAACCGTACTTCTTTCTTTTCTTCCTTTAGAGACA'.
'GGGTCTCGCTATGTCATCTAGGCTGGAGTGCAGTGGTGTGATCACAGCCCACTGTAGCCT'.
'CAAACTCCTGGCCTCAAGGGATCCTTCTGTCACGGCCTCCCAAAGAGCAGGGACTAAAGG'.
'CACATGCCACCATGTCTCACAGCAGCCTCTACCCGCTGGATTCAAGGTATCCTCCTGCCT'.
'CGGCCTCCCAAGTAGCTGGGATCACAGGCACGTACCACCAAGCCTGGCTAATTTTTTTTT'.
'GGTAGAGACACGGTCTCACTTTATTGCCCAGGCTAGTCTAGAACTTCTGGGCTCAAGTGA'.
'TCCTCCGGCTTTGGCCTCCCAAAGTATTTGGATTACAGGTGTGAGCCACTGAGCACAGCC'.
'CCTAATCATACTTTTTAAATTTATTTTTATTATTTTTTTTGAGACAGAGTCTCGCCCTGT'.
'CACCCAGGCTAGAGTGCAGTGGCACGATCTCGGCTCACTGCAAGTCCTGCCTCCCGGGTT'.
'CACGCCATTCTCCTGCCTCAGCCTCCCGAGTAGCTGGGACTACAGGCGCCCGCCACCACG'.
'CCCGGCTAATTTTTTGTATTTTTAGTAGAGTCGGGGTTTCACCATGTTAGCCAGGATGGT'.
'CTCAATCTCCTGATCTTGTGATCCACCCGCCTCGGCCTCCCAAAGTGCTGGGAGTACAGG'.
'CGTGAGCCACCGCACCTGGCCCATCCTTCTTTTTGATAAGTAATATTACAAAGTATGAAT'.
'GTTGTGATGGTATTTGGAGGTAAAAGAAAAAAAAAGTATGGATGTAGTACAATCTGTTAG'.
'TCTGGCAGGTCACAAACTTATTTTATTTCTGTCTTCAATTAATAGTGCTATTACGCCAGG'.
'CGCGGTGGCTCACGCCTGTAATTCCAGCACTTTGGGAGGCCGAGGCAGGCAGATCACCTG'.
'AGGTCAGGAGTTCGAGGCCAGCCTGACCAACATGGAGAAACCCAGTCTCTACTAAAAAAA'.
'ATTACAAAAATTTAGCCAGGCGTGGTGGCGCATGCCTGTAATCTCAGCTACTCGGGAGGC'.
'TGAGGCAGGAGAATCGCTTGAACCCAGGAGGCGGAGGTTGCAGAGAGCCAAGATCGCACC'.
'ATTGCACTCCAGGCTGGAAAACAAGAACAAAACTCCGTCTCAAAAATAAAAATGCCGGGC'.
'ACGGTGGCTCACGTCTGTAATTCCAGTACTTTGGGAGGCCAAAGAGGGCGGATCATGAGG'.
'TCAGGAGATCGAGACCACCCTGACCAACATGGTGAAACCCCGTCTCTACTAAATAAAAAA'.
'CAACAACAAAAAAACTAGCCGGGCATGGTGGTGCATGCCTGTAATCCTAGCTAATCAGCA'.
'GGCCGAGGCAGGAGAATTGCTTGAACCTGGGAGGCAGAGGTTGCAGTGAGCTGAGATCTC'.
'ACCACTGAACTCCAGCCTGGGCAACAAGAGCGAAACTCCATCTCAAAAAAAGAATGAACC'.
'AACATTTATTTTGTCATAAATGCATATCCAGGTCTCCACTGTACAAAACATTTTTCTAGG'.
'TGCTTCCATCTGGAAAATGTTACCCATTTGTCATACCGGCAATTTTACAAATAAAACATT'.
'TATTCTACTTTTTATTAATGAGGAAATTAGTGACAACTAAGACTATCTGGCTATAAGAGG'.
'CAGACTTGGGACTTCAGACTCTAGTCAATGTATTTACACAAGATTCTTTTTTTTTTGAGA'.
'CAGAGTCTCACTCGGTTGCCAGGCTGGAGAAAATGGCGTGATCTTGGCTCACTGCAGCCT'.
'CCACGTTCTGCCTTTAAATGATNTNCCTAGTTAACTACAATAGCGGGCAAAAT';

return $seq;
}
