use lib 't';
use Test;
use strict;

BEGIN { $| = 1; plan test => 11;}

use Bio::EnsEMBL::Pipeline::Runnable::Genscan;
use Bio::PrimarySeq;
use Bio::Seq;
use Bio::SeqIO;
use Bio::EnsEMBL::Exon;
use Bio::EnsEMBL::CoordSystem;
use Bio::EnsEMBL::Slice;
ok(1);

ok(my $seq =  set_seq());
uc($seq);
my $length = length($seq);

my $cs;
ok( $cs = Bio::EnsEMBL::CoordSystem->new(
     -NAME            => 'contig',
     -VERSION         => '',
     -DEFAULT         => 1,
     -SEQUENCE_LEVEL  => 1,
     -TOP_LEVEL       => 0,
    ));

ok( my $slice = Bio::EnsEMBL::Slice->new(
   -seq_region_name  => 'HSAC74',
   -start            => 1,
   -end              => $length,
   -strand           => 1,
   -coord_system     => $cs,
   -seq => $seq));



ok(my $genscan = Bio::EnsEMBL::Pipeline::Runnable::Genscan->new(
    -QUERY => $slice,
    -GENSCAN => 'genscan',
    -MATRIX  => 'HumanIso.smat'
));
 

ok($genscan->run);

ok(my @results = $genscan->output);

ok(display (@results));

my $all_exons_found = 1;

ok(my @peptides = $genscan->genscan_peptides);

foreach my $exon (@results) {

    if ($all_exons_found == 1) {

      foreach my $full_pep (@peptides) {
	
	my $exon_pep = $exon->translate->seq;
	
	$exon_pep =~ s/^M//i; # remove leading M's
	$exon_pep =~ s/\*$//; # remove strailing tops
	$exon_pep =~ s/X$//;  # remove trailing Xs - should track these


	if (index ($full_pep, $exon_pep) > -1) {

	  $all_exons_found = 1;
	  last;
	}
      }
    }
}

ok($all_exons_found);

sub display {
  my @results = @_;
  
  foreach my $obj (@results) {

    foreach my $exon (@{$obj->get_all_Exons}) {
    	print STDERR "Exon: ".$exon->start." ".$exon->end." ".$exon->strand.
      " ".$exon->phase."\n";
    }
  }
  return 1;
}

sub set_seq {
  #embedded sequence! Because I can't create Bio::PrimarySeqs from files
my $seq = 
'cctgggctgcctggggaagcacccagggccagggagtgtgaccctgcaggctccacacaggactgccagaggcacac'.
'acctgctctgtctacccgagggcaccagagggcacgagaaggctggctccctggcgctgacacgtcaggcaactgag'.
'gcacaaggctggcatttctgaaccttgcccctctgcaaacacaagggggcgatggtggcactccaagcaaaggggcg'.
'tgtgggtgctgcaggaggagcacagagcactggcgcccctcccctcccgccctgcagatgccggaggccccgcctct'.
'gctgttggcagctgtgttgctgggcctggtgctgctggtggtgctgctgctgcttctgaggcactggggctggggcc'.
'tgtgccttatcggctggaacgagttcatcctgcagcccatccacaacctgctcatgggtgacaccaaggagcagcgc'.
'atcctgaaccatgtgctgcagcatgcggagcccgggaacgcacagagcgtgctggaggccattgacacctactgcga'.
'gcagaaggagtgggccatgaacgtgggcgacaagaaaggtggggtccgggccagcaggtgctcagctctgggacagg'.
'gacccaggaccaggcatcaaagcccttacaggagaagctgttatcaccccatttccagggggctgggaaccctggga'.
'tatgcccagatagggctggggggctcctctggagtcccagggtgccagggtccctgatgacccctgcaggccctgct'.
'gcctgctgccccaggacaacaggcccccacactcacagggtctgacggtggtgcagttccccttgaactctgttctg'.
'gccaccatgggacctgcctggggaccagtcagacaggttctcctgggcccgcctcccgcttgaacttcagcctgggg'.
'cacaggatgtgttaccgggctcacggagtgactcagggaactagtgccgccccagggccccaaggtgggcggttcgg'.
'tgattcagagagggcagctctgtgttaggacacactggggccagccaggaagggtggaaaagatagggaccagcgtg'.
'agcatagaggctaagggaccatgggagctccaagcgcgctcacagtggggaccaggtcctgggggctggggacacca'.
'gggaggtgaaatacccctccagcgggtagggagggtgggcagaggagggccagcggccaggcatttgggaggggctc'.
'ctgctctttgggagaggtggggggccgtgcctggggatccaagttcccctctctccacctgtgctcacctctcctcc'.
'gtccccaaccctgcacaggcaagatcgtggacgccgtgattcaggagcaccagccctccgtgctgctggagctgggg'.
'gcctactgtggctactcagctgtgcgcatggcccgcctgctgtcaccaggggcgaggctcatcaccatcgagatcaa'.
'ccccgactgtgccgccatcacccagcggatggtggatttcgctggcatgaaggacaaggtgtgcatgcctgacccgt'.
'tgtcagacctggaaaaagggccggctgtgggcagggagggcatgcgcactttgtcctccccaccaggtgttcacacc'.
'acgttcactgaaaacccactatcaccaggcccctcagtgcttcccagcctggggctgaggaaagacccccccagcag'.
'ctcagtgagggtctcacagctctgggtaaactgccaaggtggcaccaggaggggcagggacagagtggggccttgtc'.
'atcccagaaccctaaagaaaactgatgaatgcttgtatgggtgtgtaaagatggcctcctgtctgtgtgggcgtggg'.
'cactgacaggcgctgttgtataggtgtgtagggatggcctcctgtctgtgaggacgtgggcactgacaggcgctgtt'.
'ccaggtcacccttgtggttggagcgtcccaggacatcatcccccagctgaagaagaagtatgatgtggacacactgg'.
'acatggtcttcctcgaccactggaaggaccggtacctgccggacacgcttcttttggaggtgagccccaaccaggat'.
'ggcatccgtgccagctgctgcccagagcccattcagtcagcctcagcctctccaaagagccaggcattccagtagag'.
'ccctgtgtggacacagctcgctctggaggcaccacctgaggtctgggagtgtgggggactgaggaggccctgtggtg'.
'ggtggagatgggtggggagctgggccaggggcctggctgggtggcctgttgggaactggggagccagctgcctgtgc'.
'aggtgcaaaatgggtggcagaagtggggtgcacaccccagaccagacaccagggcagaaacggcacaggaccaagga'.
'gatggggtggggaagggccgctctgggcccagcctgctctcccccaagcaagccactgctcgtgcaaagaaagcatg'.
'tgtctcctgcagatcttcctcctgaggccccatcttgtgcattcccccaacccagccccactggcgaggaccctgag'.
'tgccccgagtgaggctagacagcgggtggggctgtcctcgcttccctggggggcgtggggcactggtggcccttcac'.
'agactgatgcttaaggagcctcacatcagtgacacactgccccatccctccctggtggtcagcgacactgagtggct'.
'ctgtgatcctccactgggcttgggacacccaccctcacggcctctccacctggtgctcgctcacctgcagctctccc'.
'agaaactggacactgctgttagcagccagactaggagcacgaggggcacagcccccatgcctggctaggtagggccg'.
'ctggaccctggacacggattggaaggaaccagcactagcagaagcctgaggtgtgaaagggcagagaatgttccagg'.
'aacaatgggagtcagggcacacaggactttgggcaggtgaggatgaggttagacctgtcttctggagctgggctcag'.
'gggctcatgcctgtaacccttgcactttgggaggctacggcaggaggagcgcttgaggccaggagagttcgagacca'.
'gcctgggcaacatggcaaaagaaaaaatatatatatatattttagatggagtcttgctctgtcaccaggctggagtg'.
'cagtggcacgatcacggctcactgcaacctccacctcttgggttcaagcgattaccctgccttagcctcctgagtag'.
'ctgggactacaggcgcgcgctgccacacccggctagttttttgtagtttagtagagatggggtctcaccacattggc'.
'caggatggtctcaatatcctgacttcgtgatccgcccgcctcggcctcccaaagtgctgggattacaggcgtgagcc'.
'actgcgtccggccgtattccagcttttaaaacaacaaaaaacaacaaaaacttttctggaaagatccctgtcagcct'.
'tgtggagtgtggagagggctgtggggagggcatttcagatgccctgaactcacgaggaggcactgaaccctggccgt'.
'ggagagggaggacctgtagtggccaagggggtgggcattgggagggtgggagggagacctacaggccaagacagggt'.
'agctggaggggggctcacccctgacaaaggagcatgatgctggcaattgggtattgatggcagagagctggcactca'.
'gccagatgggcttcacttgggcaggaaagacacccacagctgggcctgcgttactgcggccgagtttcagcagctgt'.
'gatgtgggtgctaattacaggggcctgccttcatagaaaagtagcaaacattgcagtttagtaactaggaaactaat'.
'agttttctcagtgctgcttgcgcaaagctggtaattatctcaaaagaagcaaagtcatgaagtgggaagtcatgaat'.
'tgggaatgggtgtccttgttaaacgcacatctgcacactcagggctggggccctgtgcccccttgtggagggttagg'.
'ggacaacctggctcttgtgagggtctagccatcccctcagtgggttctgtgagcatcggaggcacggggggtgaggg'.
'gctcaggagcaggttgcaattcaaaatcaagggctgctttgaggaggcctctccaccgggctgctgtagtcaccaag'.
'tccagcccatgcccaaaggaagaggaatgagttcccccttaaaaaaaaaaaaaaaaagaaaaagacagagtcttgct'.
'ctgtgcccaggctggagtgcagtgatgacatcatagctcactgtagcctcaaactcctgagctccagtgatcctccc'.
'acctcagcctcctgagtagctaggactaaaggcatgcaccactacacctggctaatttaaaaattttttgtagaaat'.
'ggggtctccctatgttgcccagactggtctcaaactcctggcctcaagcgatcctcttgcctcaacctcccaaagtg'.
'ctgggagtacaggtgtgtgcttggtctgaggctccaactttttgttgttgtttctcgagacagtctctcgctctgtt'.
'gcccaggctggagtgcagtggcgcgatcttggctccctgcaacctctgtgaggctccaactcttgaagggaggagag'.
'tctaaggagggtgggccagatgaaaaccacctcagcatagtgtcacctgctcctctgacactgtcgcttctccatgg'.
'cattagattttcagtcctgctcagacgctgatgcatgtttagccagttctccaggtggtctgagtagctggtaggag'.
'gcttgcagtgtcgggcgacaggcaggacaggtgctgccttctttcccctcttgaccagtttcgtaaaggagtgggcc'.
'cctggcagcctccaaaggtgacccatgctcctttctgcccttccctccttctttcctgtttaactcgtgcaggtgca'.
'gtggtctggtgtctttcagtccgctgacgtcttctgtatccctgatgaccagattgggctcctgagtcccctggcgc'.
'aacccgagaagtccaggagcccaggcccctcactcatgcattccctggcccagactggaaggcagccgccctgctca'.
'aggcctaggccattgtcctcctcccgggtggcgctttgttctacgtcttttcagctgacattgctaggacatttttt'.
'tttttttctaaatgaaaacacatcatgattcatggtggtacttcctgctcaactccggaccttggggctgtcccctg'.
'acctcactgaccttgcagccgtgtggtgtccatactgtcacatgaaagccccctgctttctctgcagcatacaggct'.
'ggaaacgaccgccacccaccaccaggacagctgcaagccctgtgggactctccaggcccatcccagaggcatgtggg'.
'gtcggataccagtgtttcaaggcacctgcctgcaaattgattttattatactttagatgtttgagattgcttgttaa'.
'cttttgtttggtgactaagtcaaatttccaagacaaggtgactggggtgtcccttgccctggtaggtccttcctccc'.
'cataggcaaacacttcctctcaaggtttcttgtttatgtgatgtaagcaaacccttttctgatagcatagataggca'.
'agcatcctatgaggtttctcccgatagtggaccccacgggccatgccctatggctgcgtgtccagtaacaactcctt'.
'ccttctgcacagaacccaggcagaggaactctgtgtcctcccagggcccaggcactggtgaagatggggggtctgca'.
'aatgcaggagcttggggatgtccagaactgaccccaaggggcaggcttgttgatgggaggtctgccccacctcagcc'.
'ctgcagggtcaccctggtcaggccaatattgtctccagggaccataccagcaacccctctccttgggtgcctctccc'.
'tcataggcctgagttcctggcactgggtgttgagggccccattgtttccactcacccagctagcatttattgagcac'.
'ctactgtgtgccacatgctgttctaagggatggatactcctgagatggatacaggagttgatgagagaaaggtccct'.
'gtcctcacggggcccatgttctgaaggtggcacccaagtcttgtacagtcctttcctgcaggagtcacgctgggcag'.
'aaagtggaaacctggccccaggggctaggcacaggcgtggtgccgtggcctagtgaggagcacccatcctggtttgg'.
'ggcaggttctctgggcacctctgaccctcacctcccccaccccccggtctgtttgcaggaatgtggcctgctgcgga'.
'aggggacagtgctactggctgacaacgtgatctgcccaggtgcgccagacttcctagcacacgtgcgcgggagcagc'.
'tgctttgagtgcacacactaccaatcgttcctggaatacagggaggtggtggacggcctggagaaggccatctacaa'.
'gggcccaggcagcgaagcagggccctgactgccccccccggcccccctctcgggctctctcacccagcctggtactg'.
'aaggtgccagacgtgctcctgctgaccttctgcggctccgggctgtgtcctaaatgcaaagcacacctcggccgagg'.
'cctgcgccctgacatgctaacctctctgaactgcaacactggattgttcttttttaagactcaatcatgacttcttt'.
'actaacactggctagctatattatcttatatactaatatcatgttttaaaaatataaaatagaaattaagaatctaa'.
'atatttagatataactcgacttagtacatccttctcaactgccattcccctgctgcccttgacttgggcaccaaaca'.
'ttcaaagctccccttgacggacgctaacgctaagggcggggcccctagctggctgggttctgggtggcacgcctggc'.
'ccactggcctcccagccacagtggtgcagaggtcagccctcctgcagctaggccaggggcacctgttagccccatgg'.
'ggacgactgccagcctgggaaacgaagaggagtcagccagcattcacacctttctgaccaagcaggcgctggggaca'.
'ggtggaccccgcagcagcaccagcccctctgggccccatgtggcacagagtggaagcatctccttccctactcccca'.
'ctgggccttgcttacagaagaggcaatggctcagaccagctcccgcatccctgtagttgcctccctggcccatgagt'.
'gaggatgcagtgctggtttctgtccacctacacctagagctgtccccatctcctccaaggggtcagactgctagcca'.
'cctcagaggctccaagggcccagttcccaggcccaggacaggaatcaaccctgtgctagctgagttcacctgcaccg'.
'agaccagcccctagccaagattctactcctgggctcaaggcctggctagcccccagccagcccactcctatggatag'.
'acagaccagtgagcccaagtggacaagtttggggccacccagggaccagaaacagagcctctgcaggacacagcaga'.
'tgggcacctgggaccacctccacccagggccctgccccagacgcgcagaggcccgacacaagggagaagccagccac'.
'ttgtgccagacctgagtggcagaaagcaaaaagttcctttgctgctttaatttttaaattttcttacaaaaatttag'.
'gtgtttaccaatagtcttattttggcttatttttaatgctttttctcagtgtttttcttctgtttctgagtcacgaa'.
'cagcaggcactgaaagcagtcccccagccactgccgaaggtcagtcccggaggtgctgcccaggctccaggcagatg'.
'cggcagccccggccacagccagcatgggctggagaaaggctctctactgcacaggggcctcacgtgactgcagggct'.
'ctggggaggtggggcacctgtagcctgacccccaccttgctgcttccaaagcttccttgcccagggctgagccttgt'.
'ggggcaccccccacactgtggtctgcctgcctgcagggtgcccagggagaccctccgcctttagaagtccaagttct'.
'ttcccagccccctccctgcctagctgcctgcccctggcgccagacctggcccgcaccactggggcactgtgttccca'.
'ggggcaccctcctatcccaccagccccaaagcccagccaggcacccttccctgccacctccctgggccctgccccag'.
'cagcccagtcggcctcctcgggccttctgtcactcgctcacacacagcaccatgtcagtaaacagctaactcaggcc'.
'tagggagttaggtaggatggggggagtggggtgggggggcaggagggtgtccccaaagtcaggcttggctggggcga'.
'ggcgctgccaacccctgccgccagggggctccaagctccacggcacgatctgctcagggtggcccttcttccacgat'.
'ccaagccctaagaacaagaggctgggcctgggccctgcagagggaaaggggatggtggacgctgcagccactgagtg'.
'gcacaggaccacgtgtaacctcagggcagggcagccaactccacaggctacatggatggagatgtggatagaagcat'.
'ctgccctgggtggtgtgggctgaccccaagggtcttggcaccagggctgatcctgacttgctggtccccgaagggcg'.
'ttggagggtatggtgcccatccctactctggtcccatttcctcaggcccctgatcccacagtgcctgggacagggct'.
'gtgggcccagggagcaccctccctctctgacctctgcctggtctttccgggaatgggccactgggctgctggactgg'.
'aggccaaagtcctgcggggaacgtgcgggaagagcagagcgtgcaggcagcagagactaacaagaagccctggccca'.
'gagggcaggaacaggtggacgaacaaccagatgagagaacgtaccaggcatgcaagctagacccaggaatcaacggg'.
'ctgaggcttagcgtcccctacggcgtccaccagcctgaccgcgggcctgctgggcccggggggaggggccttcctgc'.
'tggggtcgagctgcagcgcacgggtgggcattagaggcacaatagagcaggttagttagagctcctggggggacagg'.
'gcaggggcagggccgaggctggcgatgtaagggttggcctgccaggacagcacaggtagcaccaagggcgcagggag'.
'ccggaaacgtgtggctcacacgggcccagggcgggcacgtgcacacacacaggcctgcacaggaagccaggggattg'.
'gcacacagcaggcagcaggtcctgccatcgctggtggaccctggtgggctctcacacgcacatgcacagaagggtgc'.
'acacacactagctcacaggctctggcccatgcagggtgtggccgggcagtgttgtccccagtgggtgggagctgcaa'.
'acttgtcagtacccacagactgactggcgtgaaggggctgcttcctgggcttggccccacaacccagctgtacccca'.
'gggcccagaccagacccagcatggcctaggctgctctccagcaacccctagacacagggcctcaccggggacctgcc'.
'cacagccacatgaccacttactttcaagggttccttctcagaggcctctcctgcagagctggcgccccgtggcctcc'.
'gctccctctggtccaccgtggagtatccgtctgtagatggggtaaggtggggcatgaggggcgctctgagggaggcc'.
'ctgtaggagcagatctccctctcagcccagacacaggggactcgtgggacaggggctttgggagacagcccccaccc'.
'accctgtcctggagatccaggctggtgccagctctcaccaacaccctgccaactctccagactcccctccacttgtg'.
'ggtcagagcccctggctgagcactaatccctctctagctgccctgtacctcaccctctaagcacccctaaaccaaat'.
'atctctcctccacccagcaccatctacaccccataaaaccagcaggcccacttcaggccttggtcccctcccggcac'.
'agaaaaccaaccacactgcatctgcactcacctgggcccagcgcatccatggggatcacatcccggctgccagtttt'.
'ctcgccctctgcaaggcaggaggaggaggcgggctgcatgtggcagccaggggggatcggggcagagaagcccacac'.
'agggctggcccaggtagccctagaggctctctgtcactaaggtgcccaacctctgccagctggcagcctcaccccag'.
'cttgacaacagcgcggatgctgtgggaagggagtagccaagaggcagagggcagggaaagtggcctatggaagccgt'.
'ctcagtgggaggcctgactcctccttcaccctcacccaagggtcaggcaactggggcagctggggtcgccaccctct'.
'aggctccctaagctccaccactcaccaaggctcttgtccaccagtggcagcgtgctgtcatcgaagcccccaggact'.
'cagtgctcccttaggccccttggcagtagcagcagctgactgagacataaaacacagacacagggtgggtgaagcac'.
'atggagtgggaataaggcaaagtgagcagggaatggaaggaaggccagggaagccgcacctggaagcgcgccttggt'.
'ccaaccatctttctgcaaggtaccacgcagctccttgtagctccacactgtctgcagcacgtgtgacgccgccttcg'.
'cttcgcgtaccgattggctgtggggccgggggcggggtcagtggtggcccctcccccacctccgcggctccccaagc'.
'caccgaccccgcccctccacacctggaggccacgagagccaccaacgctggcaccccgcgtgcctgcaggagcgagc'.
'gcgcgttatccaggctgtcggacacgatttcgtggatggtgttgagcaccgccaccacggtgtcttcctccaggcag'.
'gcccccggtcgcggcggagcctgtgcattgcgcacattccgcacaagctcagccatggcgtagctccctgaggggca'.
'ggactaggtgtcagaacacacctctgccccacctctccaggaaggagcagggatcccgcgagggcgaggggcactgc'.
'caggagagcccctggagaccgcctgtgtgcaggcggtcacaggagcccctgtgagcagggcgctgagcttcagagac'.
'agggccggggggactggagctacctccagttgggacagcgcccaagcgagagggccggggcctggactcccaaacca'.
'ctcatcctccaagcccctccgatgggaccccaaagctgcaggcacagttcggtgcccaggcgtgggctttgcaggcg'.
'tcctcaccgatgaggtctttgttgcgccggtccagcgagaggttgcgcagagcgatggcgacggcgcgcaccacctt'.
'gtcggtctcagactgcagcagttccacaagcaccggcagcccgcgctctttgcgcactgtggcgcggatgtacgtgg'.
'cccactgcggaggcggggagagggttgctcagacatacatgccaggcactctcccacctccagacgctgaccgctct'.
'ctccagctggaccttcctgctcccgtgcccgacaaagccctaccccaaaagctcaacggcacctccaccgaggtttt'.
'cccaccgtccagggtgcacgcattgcccgcagcccatacacctcttggatcctggggtggtggtgtggcccctcctt'.
'tccccgccagccgaggcaggagctgcaccagtgaggtgcctgggattccctctctcaggacttgcccaccctgcccg'.
'acctggtccctcaccatccagttgccggcactgaggttctgcagagcgccggcggcagcctccagggtgttgaagtt'.
'ccggctctccgtgaggagggagaggtagagacgtaccacctcgggctggtacagcagctcaaagcctaggtgcaggg'.
'caaccgccacccacggtcacccagaatctgctctcatccatcatacccctcccgcttcccgcttcagagctcccagg'.
'gcgtgggtgagctggggccagggatgggtgtggatgagtcacgtaatatttactatcaacatatagtcacccaaggg'.
'gaaaagcgttcccatttcacagaggagcaaactgaggctcaaatcagttggacctgcctggcagcaggagcatccag'.
'gaggcctggggtggggagggaggtgtcaaccaggaacgctctcctagcaacaagacccgcatttcccggtaggtccc'.
'tgaagctatgcatcctggccacgcccctggtaatagggcccaccctccctggcaacaagaccagcattggccagtaa'.
'ctgagagttgtataaccaaggccacacccctagcaagaggacctgctttcaccagtaactgaagctgtgcagagagc'.
'tacgccccctagcaacagggcccaccctcccccactgacaatagagcccaccctctgtaagtcaactgatgcagtgc'.
'aaccagggcagctgccctagcaacaggaggcactcttcctggcaaccactccaagttcccgggcaattgaggcgccg'.
'tcctgctgctctgcccagtgctccagaaatgaggggtcaaaacagccttccaagcttgcctgtctccaaactggggc'.
'ttcagcctggcttgggtactacctcgatctcccctgtacccacccagtgacatttcatcacaccctcgccagtcctc'.
'atgccccatgctccctctactcctgccctgctgggctttctgctccaacacactccaagcacactccccgctggggt'.
'atctgcatcagccctgctctgcctgtaatactcccccacagccctcctgcggctggagccctccaccctggtgacat'.
'gcaggctcttccaactggctaggccccaccaggacagacctctctctcaagccagatcccagcatacagctcaatag'.
'gcactgccctgcccctgcaggtgttcgtctggcccagcctctgaacctggatgtgagcatgcccgcctggctcccag'.
'ccccctcagataactcagctttgtggctaacacaggaggccctgcctccactggaggcgtccctccaaaccttccca'.
'cctcttacgcaccgtgaggccgagcaagccctctgcctctctgtgcctgtctcccccaaccttgcctgacatgaccc'.
'atggcacttcctcccattctaaaccctcagcaggtgtcctggtgctgaatcaccctccaggaaatcctgcacctagg'.
'ggcctgtttccccatctgttccctgaggccctccaggcctgcttgatggctcaaagcttcactaccagggcaatcct'.
'gagcccagacatcccccagtggagctggcttcatctcagcccactcacctttggcggcctcagttcgcttgggcagg'.
'tctagcgtgtcaaagttccggtccatctcaccatccttctttcctggaagggaaaggtggtgggaggtgaggcagac'.
'cccatatggggaatgggtgtatcaggagagttgggcacagttctctcctacccaggccccaaaaggcacccccatgt'.
'ccaggcctgggcacctgtgggagtggagcaccgttgtcagagtttgggcagacagtttagcctaggggtaggagttg'.
'gtggcagtggggcctggggatgtcccagccctgcccctaggactcatctcccaccaggtgctgggagctgtaccaca'.
'gaccctcccggtggctcccttgcaactgccaggtatgtagactgagggaagccaggagccctggctggatggtaggt'.
'ggatacaagccaagaaactgaaggctgaccaggacaagactcatttgggtcacacagtaaggcagaactagggggaa'.
'actcccccagctggggtcaggacattgtcccaggatctactagccaggagaaaccccacagcagcccacctaacatt'.
'tgtgtagccctggcttgcacacgtctgtgacagtgagcccactgtcaaccactctccccatgtcagatgatgcttct'.
'accccttcagaaggcagcagagtggagccagatgacctggggtccctgccctgctcaccctcatgggacccttgtat'.
'ccctccgagccacatgatgccccattctatcagagaaacagactgctccttggtgcccctagagataagtacccccg'.
'ggccctgcccactcttggctctgcccaactctgcccaggtaggcaagtctgaggttacagaatgagccccgtggcct'.
'tcccacctgccactgtcataaagatggcagcccgagtgatgaagccaggggtggggcagggccctggggctggaacg'.
'tgctcgcctcttcccaggtacccactgcacacgccaggcctggagagcaggataaaaagggactcaccttggtggaa'.
'ccactcctctgggaggccggaggaagcagaggagagaggagaggagcctgaacaggcagcactcatcacccccccat'.
'gccctcccggaagcctcaggttcccactgcacaccctggatcaagcaggcagcatgtggaacctcatcccatcactt'.
'ctgggcactgagcacccaccagggggacaagaagagggaggcctggggtcagtggggcaggggcaggtggcgtacag'.
'gtcccccacagctgctggggaggtcctgggaacctacaccctgctagtgcagtagagaaggtgtgcagggcatcttg'.
'cccaggcagatgggggctgccccacaggttggtggcagtctacagctattctgtgaacagtgagcaggcagcagcca'.
'tggctccttcccaactcatgggcaagtggaactctccccggagtagaaagactgggtctgggcattggttggtttcc'.
'cttgtgtactccctgggggtcccacagtgtagatggggaaggttggacctgggtcccatcaaccatgtgacccaggg'.
'cagtccagcctccttgactcctggcttccctgcctgcctgttgggggctgaccaggtgtcctctagcctccatgatg'.
'ggctgctgtgggtgtacagagagccttccgctggggcaggagttgagatggtagagatgataccccagtccgcccca'.
'cccacctttggccttcttgcctccaaagcagctggcatcatcccgcctccggcgctgggagcctacagcactgccca'.
'ggggcccgggctcggcctcctggtacctgtcggccccgggcacctccttgtgcacgtggtaggacaggttccgcatg'.
'atgcacacgcagttctccaccgactgcagggagaggtgagtgggtggggcagggcaccctaggcacagggctggccc'.
'tcaggaaagactggccacagctggtgtgcatgagggcaccgggagcaaaggaacagggagtcctcagtggaggggag'.
'caaaagggcggtaaccgccaggaagggtccatgggaggaagcctctgccctcacggcacaccttctgcctgcaggac'.
'ggtgcccacttcagtgtggtcactgcgaggcgggccacacccagaacgccaccccagacccacaagcccattcccct'.
'gtgctgctcccacagttccagcctcctgggacctgcatgatcgtctctccagcccttggtatgaggctgtgaccgtc'.
'cctgcccaccttgttgtcagtgtccttccggcccacagccgactgcagggcatgcaggagcgcgtccaccagccctt'.
'cacactcccggagtcgccgccgggcctcagcaccatcggagctcacattcctgtgtggccaagagcaggccaggtga'.
'cccctggctaccagaaactccctggctccaccctggccttgtgggcttgtcttcatctgcaaaataggccctgctgc'.
'tgccctcctagcactaatgggaaaggaccccacagtctggagctcagtgaagggggagaagctaactgcccccaggc'.
'ctcaggaggggagccctggcagacaactatcttggctggggatagctgggcagggaaagacagggtttccctgcctc'.
'ccagctgacctggaaagggacaggtgcactctcagagagacctgaacctgtgcaagggcaattctgggtccctcgcc'.
'accccaatggcagctctgggccccaccttaccccaaggtcaagagcctgcagggctgcgcgggaacaccctgatgga'.
'caagcaggactgtggggacccaggactctgtggggtcagcagggcctcccaggggtaggaggggaagggcagaggtc'.
'acaggtggctgggatgagcctcccaggcagatgaacaggaaggtcccagctccccctctggctgtcaagtgatggga'.
'aggtaggtgagagctgggcagggctacggtaccacagagacccctccagagggtgcccctgggaagactgggacacc'.
'acttgggggtgaggacagctccatcaggccccacttctcatccacaggacttgtgccacagctctgaagctcctaag'.
'ctctggcgctcctaagctcgccgccatcttccacactatctgggaccacgaggacggggcctggtgtgcatgtgggc'.
'tttagcaccaggtctggtccacacctcaggcagcccgacgtgttcttgaagacagttgtccactcggcgtcccgtgg'.
'cttggagtcctcgttgggctcacgctcccatcctgagtggggcacgatcacctcgtgggtcagcgtctgcaggccat'.
'ggtcaatgatgaccatcttcaggggctcataggatgacaggttccacagggtgcctgtggggtgcgattggccaatc'.
'tgtgctgaccatatgcaccgcctgcctacctccccaggtggccacgctcaggacctgtcccactctcctcatgtccc'.
'agctcatgcagaacagtaggaagtaacaaaagccgtgagtggttccgggggacacccagtactggtttccagctagg'.
'aaggagccccaaaggggaggaggtgcagaggagggtgtggcagtgctgtcccgtcccacccattccctgccatgtgg'.
'caggtggcactaacactcctgaggccacagggcctcacagagacacggtgaccctacctgtccctcagctctcacaa'.
'ggcacaagccccaccactgcacggttggggtgggaaccaaggaggtgggtcccaggagagtttctgtgggggcagga'.
'ggtgtgaaggcaggaggtgaggggacatgcccgaggggcgcagcgtcagcctccctactatggtagagactggggaa'.
'cctgtcacagtgtctgggcctgatgcctggctcctggggcaagcgtctcagcagctgcactcctgcctaccgggtgc'.
'tttcccaggcggtcgcaggccgagtggcctcgttcctcccgggttgagcctcacactcttctcttcccaggggatgt'.
'gagcatggccaggtcccactcaccagtgacaagctcacggacctcgttgtcccgggcagccctcagcaggcgcacca'.
'gggcaggcacaccaccgcagtcccggatggcggccttgttgtcagtgtcgcggccataggagaggttgcgcagtgcc'.
'ccacaggcccggcgccgcacctcagcccgcgggtggtccagcagtgccacaagcagcggcagcccccgcaactgccg'.
'tacacgccgcttgacaccctcgttctcaaagcacagatgctgcaggtaggcggccgcattggccttcacggggtcca'.
'cggggtgccgcagcatggccagcacctcaggcagctcagggtcccgccagcgcggctccttgcgggcgctatccact'.
'gagggcgagcgccgcaccagccggtccaggctgcccatgctgccccgttcaggctgggccaggggcgccgtcaccat'.
'tgggaacgcaggccgctcgtccgccagctcgccgccatcatctgctgtgtcctcgtaggccctgcacaggcaagtgg'.
'ggcgcgtggacatcgtcacagcagccgccagccctgcctctgagctgccccatcacaccttcttcaggactgcaaac'.
'tcacccagcagcgctgggctgagagcacctgtatcttggcccggagcatggtggggacacagagagtcatgcaccag'.
'cccagtgagaaccaattcagagccaaatgccaaaccccagccagcggctaccaggacccaggcaaccctcccaggac'.
'agcaaactcactcactgctgtcaccgggcagtttcccaatcccgagcaaaacaagtttctgtgagacatctgctatg'.
'gctgctggagagaccgtctcacctcccttccacaaaaccaccccatcttccatgaggcccatctctggctgtgccag'.
'gatgtagggggagtaaatggccctctccgcatgaagccatcccagtaggaccacctgaggagtattcaggccaccag'.
'ccccttggggcacaagatctccttagctctcagtagccctgtgggttgctgtcatcaaaccgcctgccctgaggcta'.
'ggagtgacggtcaggtgacttggccagggtcacacaacaaaatcctgacccgggctgtggtcacatccccactccag'.
'agatgcagaaactgagggcaatggggacagaaccaggggctgtgacaagggccagggctctgggttctggttaccca'.
'gagtgtggctggagcaaggccagtggccggcactcttcccagctttcctgggccctgggcctgcaggacagtgccca'.
'gccgaactcctaccaccccagggtccacctttcttctgtccctgacgagagccaaggccaattcaaactaacatgca'.
'tgactaactcaactgcgccacttgacaagtggggcactctgtagttggggggtggagggcagacttcccagaggagg'.
'tagccacaggggacggggtgcagctcacctggtatgaaggccccgcccacactcaggcctcctccttgtggccgtgc'.
'catagtcaggctccagctcagggccaccctcgtcatcagcggccaggctgcgcgtgtcatcctccaagccatacggc'.
'tctgcctggaagcgctcgggcagggagcggccacctggtggcccaggctcaggacccaccgggaaggcttcccggtg'.
'gccaggcagtgtgaagcagccatcaccagggcctgggccaagggggccagcacgtgggggccgcatgcccagccctc'.
'gggacaggctgccatagctggggctgtcccggggctcggggccttcgggaaagccacccccgctgctgaggtaggct'.
'cgagagagtgtggccactgggccaccaccacgcagcaggaaatgccggtccagggcaccatctgcaaaagggcctag'.
'tggggggccgccatccagcagggggagtccatctgggcccacgggcacctggcgtactgtccgagtggtcaccgtct'.
'tgacagtcttggtgacctggtggatggataggcaggtaggtggggtagcacgagaggcctagaaactgctttgctgg'.
'ggtctggctggccttaatttcccactcgagcaatgagaggccccacgtggcaagcttccatgtccactctgcaggtg'.
'ggacagctgcagcagcctggccctgctcacccacccactgcctgggcctggccataccttggtctcggtgcgccggg'.
'ttgtgccatcttcggatgtgacaatagacacatgggaagtgggtgtgccggggtcctcctccaccgtcacggtctcc'.
'tccagcacatcaggtgcctccggcatcgtggccagtgaggcctggctgcctgggctctgctcctggggcaaggaggg'.
'acattggtgggcaggcctgctgctcagtcacccctggagtgcaggtctccacacacagcagctctgcctcagctcat'.
'gctggccagcacaccagggtgccttcctcctggtcctgaacccacccaccccaaggcctgtttcggcccaagctgac'.
'aaggacagcaataagttcttgccctctgaacatcgaggtgctaaccctgccccggcaccccatcctggggggaccct'.
'ggggctggacccccatctcaggtctcctcaggctgagttggcagataaggacatagaccctggggggtgaagtcttc'.
'agggccctccccaagctgcatggccttgctgccacaggctcctccaggccccaggaggtgccagtgagacctgcagg'.
'atgccttcctgatgtcaaccaccacccctagctgggacatcatggtgtcctggggcctcctccctcacctgccccag'.
'acaccttgagtatagaagccttgtgggggctgtttcagcactgcctactgactcctgtggccacactaaggttcccg'.
'ccaccaacgccagccagacgccctcaagggacagaaatacgcagttcccagaacaccccatgcacctgcagcaccag'.
'tatgtccttattccttccagcccagacattcttgagtgttgtgtaggcacaggtttgccctacctcgggccagtggc'.
'tggcgcccccagtgactgagactctgggcatcatatcagagaccagacacagtagatttgagcctatgggtgccctt'.
'gccaccattctgcatggggtgacgacactggaattctaggcaagacaactctggactgagacttttctatccacatg'.
'cctactgactggacttgccagtgggaaaactgaggctcaaagaggataggctggcccacatcagagccaggcccaac'.
'ccctgccgcgctgagtggcttgaggacctaagactcacagcctgccccgggcctctgactgcacaggtgcctggccc'.
'cagggccacatggcaccaacatccggggatcggcatctagccaggatgggcaggagctgaaacccaagccctggtgg'.
'gtgggtcaggcggagcacattcccaggcagccagggcagggtcagcaggaggacaggtcctgctttgtggcccaggc'.
'ccctggtccctgcacaatgggtcccttgcctgggccccctggggcctgcacagacactaagctctgccaggctccag'.
'aggcagactctgcccattcttgggcctgggaggtgagccaggttagatgctcagcgctgccctcaggacctgcctgc'.
'caaggctcgtgggctgggaagcctccccaggtcagggtcctatcctgggggaatacttgacccccaaatgcatgcag'.
'tgcaggtgtccaggaaggggcctgcaccaacatgttaggacaggtgtatccctcaggctgacagaggaaagaagtgg'.
'ccacagaaggcacctccccctctcccacaggcagggtcttggaggatgacagataactttatagatggggaaactga'.
'ggcctggcagggggaagaggatttacctagaacttcacagtccaagtgggatttcaagcacccccagagaaggcaat'.
'ctggcaaggaaggctttgggcctcatctcgccctcagtcttgagatgtaggtggaatgcctgctgtggacctggcta'.
'ggaaaaggggacctgttccctgggaaaaagaaatagactgaggcctagagtggggacaactggcacgctgccaggca'.
'gggcaggctgggctcttctccaaaggcactggggagctgggactgctctgaagcaggagaaggcttgtgtggcccat'.
'cactgctggggctgggctgccccatctgtatctggcaaatgtgtgtcaggccctgagctctctctgctgggccctgg'.
'gcggggctcatctgagttcaagcaggggcccaggcactgaggggctgcagttctggcgacagagtgaggagggtata'.
'aagcaagactgaggaaacgttacccaggactctgccagtgggatgtagcccctcatatatgtatatatttacatcta'.
'ttaaaaactcagagaaaaaccccctcttccctagctaggcagtgggggtaagcgggagaggaaaaggggaggacatc'.
'tcaggaccccgatgccactctgtggcccagcttatccctcccaccaaggctgtggtgagggtctgacaggcagagct'.
'ggggtggtccaggagagccacgcccccgcagcaagacctggcaaccctgcggcaccacccatcagccccggcctagc'.
'agccccgcagtaggatccagaggccccaagagtccctgctggcaaatgacctcagggagctaaaaacgagggatgac'.
'ttcacccgggtggcaggtgcatgagtcagccagtgatcacaggaaagcccggcccctgctacacatgcccaggcaca'.
'cacacatgcatatacatgacccctcagacagggacacatgcatgtacatacacgtgtgcaagtacccagcccggcac'.
'aggccgagcacatcaacccgtgtgctctaacagcaccccaagggcacggcgcccactgttcccagaggcacactcgt'.
'gagcacacatcctcccgtcctccaccgtgtatcggagacccttatccatgcagggcctcacagagtctcaacacaca'.
'gggacaggggccaccaactctgccaatcatctgcccagcatccactctgggagtctcagagctggctggcagatgga'.
'gaaactgaggtgtagagtagtgagaggcccatagccagctggtggctcagctctctgcaacatctttagggtggggc'.
'tgtggaatggtgggctgactctcaacaggagttggctgcagtccctggatccctgtctggccccagtgtccatgtct'.
'gacgtgcacctgcccaggctggcccactctcagggaccctggccctgcagccccacacagcctctgcctcagaccca'.
'actctgggctgctcccctctgtaccctagacatgggctctaccctgaacaccccacctccagcccaatcccacatgc'.
'tgcatcctgtcagtcgtctctcatcaccccctccccagctggggccccatccttgctcctcttgcaccccgcccggc'.
'ctcccagcactcatccctcccttggctcttcaatctctggtgcaccaggtctggggcccccaggactggcccagaaa'.
'caggctgctgcccaggcctggggtttcccatgagctcccttgggcttgtgggaggggccagagtgaccagggaggta'.
'gaccacctacccctgctcacaagagggtcccgggaacacagggctgagcccagcataggggctctgggccccatcac'.
'gcaccttcggctcagcttcttcacaaggaggtgagaaggacagagggggctggggtcgtgggacgtgctgggtagca'.
'tcagtctcacttttgtggcaaaatgcaaggaacacagggagcagaaaagcaagattggaccaacacacagagggatg'.
'ctggggcacaggtggctgggccctggtcccatattacttatctacccaaaccaccggacttcacagatgcaccacgg'.
'tctgtgtcctgaagaacagactgcaggggcaggcccctcccctgtccaaggcctggctagcacacacagagaatgag'.
'ttaaggtgagattgcacacctggatcccacacctgcaggccaggctcccagagggcaggaggtggctgctgtccgat'.
'ggatgaatgaatgaatcttctccatccccattatggccctcccaggtagagtccaggacaagccaggctggcatctc'.
'tcaccaggcagcaagcccttggccaccacaaaatgccctttcccttggtgccacagcctctgaccagtctccaagac'.
'ctggagcttacttctccacacagcagtgcacctgccagggcgtggccccaggcagagatgccaaaaagccaagctgg'.
'gggagcaaacttggggtgggagagcagggctgactgtcatccacctcagcttccccaagctcagcttggggtcatca'.
'gacacactgtgaccatggatttcccaaaaactggtccctccacctctgagggccagaccctgggggccacaccaggg'.
'ccgtaggacaggcaggggcctagttgcccaggtagcaggtgtgtgggagacctgcctcccaccacagagggtcttgg'.
'ctggtctctcctctgctcagtttccctgcctgttactgaacccagcactgctctgagcagaggacaaactgcctatg'.
'cctccccccacctcaatgctgagagggggaggatcccgttttccttagagatctcctccagcatccattagtgggca'.
'gggcctgtctctatccctcccatcacgtgcgcctcggaggcagagaagacttccattaaagctccggaagctccttt'.
'gcaggtcccgggagtcagagccggcgtatggggtgtggaggggagaggaggaaccctctcagggagcagaaggccta'.
'cccgggcttccctcttcagacttcagcctccttcctgcacagacagaagccgctcaggaaggccctggctctccacc'.
'cgtgtccccaggcacctgtcctgggcgctggccaagaagcgtccatccggtccgggccggtgccaagaggagggtca'.
'aactgccaggggtcccgacccccccaggccccgcggatgggctccagagaccctgcggcccgccctgcatacccggg'.
'ggcaccgcgctcacaccgccacccgcccggccctggccccagcctgacgcagcccagccaggggcgcaagacaatag'.
'ctgcctcgggccagcggctccgcggaacaaaagcgggtcctcccgggcaggccgacgccccgccctctgcctccgac'.
'cccgggccagggtccccccaagccaacttccctccaacctgtctgagttcggccggcatcgggccgggactcggggg'.
'gcgctggccagcagcgggggaggcggtggctggaccaggctcggctccggcgcctcggccgctcgggctcaggctcg'.
'gcggactcgctccccgcgggggcggatctggcggcggtcacggcgagcagccaatcgggcggggccgcgcccaggtg'.
'gggcgtggcgggggccggggtgggcgtggcgggcggggggcgggcaatgtgaggtcccgccccccagagacaggggg'.
'cggggccctgcagccccgggtcgccccctgtccccccacttcccaccacctccccccacccactgccggcctggact'.
'tctgctccctccccctccctgcggcaggggtgtcactttcccgccgaaagactttggccaagtccttcccaggcctc'.
'ggtttggcctcggtttatgaccacacttcagtccgcctgcaaagggggaaacagttccggcagggcaggtgcccgtg'.
'ctgcgatgcacagagcacaaggcctccctcactggcacaaacctggctgcgactcagtttcacctgccatgaaatgg'.
'gggccgatgagacagtagtcacggctctgtgagatctctccagtctcccagatcccccctcaccctcctgcccagcc'.
'gccactctgaatgggcctgcgaagaactgtccccacagagttcgatggggacctggaaaagggccctgcaggggacc'.
'cccactttgtatcttgggttctccccatcgaggcacagaagccccgaatgcacccccactgctcccccaggccagcc'.
'tcaatgtgggccacaccctagggaatctagttctgctgcagtgaaaaatgggaggggaagggccaggctggagccac'.
'cttcttatgtcaaaccccacaaaggccaagccaatggctccagcatcacgaacagggaaacaggttctgagattaaa'.
'tgagctgagaccaacccagggagactcagtgggtctggcaagagaaagggctcgggcccaggcctcccactggcttc'.
'tccgcagacccctcagaaaacagcctccgcagggaccactccctgctgccctgagcgccatatacagaggccactcg'.
'gctagcatgctcaagattctaggtacccaccatgtgcccctctgagcctcagttcccccacctgcagaggggtgagc'.
'taccctaccactggctggacccctgtatcttgcatctagggccaacctgcctggaacccctggagcagagcgcagaa'.
'gaccagacactgcgccaaaaacgcgcccgcatcttatctttaagctggctccatcttctcaactgcaccagcagcta'.
'gtgccccagccacctatccacctaagacgagcccaaggcaagttccctgatggcacccctccccactgggtgggcgt'.
'cagccctgtttcagctggctgtctagaggaggggccccttcctgctggaagatgaagggcaggtagccaggaccctg'.
'gagcagcccagtgagtgcagcagcactccccctagcctggttccccagcctcagcccccagctacctgccttgccat'.
'tgccctggcttcccaaagcccgggctctgaccctgtggctcagcaggtagatcgctaggcacttcctactgaaacca'.
'atctgggaaacctggccagcccaaggaggccctgcctcccctagtatcctcatcagcccagccagttgagctgcagc'.
'cctggcaacacatgctctcttcaatcccagcctgagaaaatcaagggtagggggtcggggggagagttcaggggcag'.
'gggtggtaggtggaggggcagtagcctgaggtcttgaagtcttttgcctgaggaggtcagggtagctccaggctgtg'.
'ggaacatcttcccaccagggcatcaaccctccggggtgccttgggtcctcccacactgcctgtccgaggacagttcc'.
'ggtctgggagggttggactgagcacactggcgcctgagaggcggcctcggggtcactggcttccactgtccctatat'.
'ggcccagctgggcccagcgttctgcttccccgcctcaagtttgagggtagaggcctcacattttggagtatctcaag'.
'tctgagggctgtgagagtggccccagcaccgagacccaccagaggcctctgagcaccaggggccatgaaaaagggcc'.
'ccctagtgagtctcggaccctctggggacattaatttgactctgaccatgcactggtgctgggctgggccttctatg'.
'tgggtctcatgagcagacgtaggaagcatgacgcctgctggccgacaccaagtctggacaccaagactcaaggagta'.
'gtcaccaaccccaggtccctcggcctgacacaggctgctggttctgagccccacatgccccagccaggtgaggagag'.
'cccatggggctgcctcaacagagaccagcgtttgctccctttctctctagatgagaagggccaggctgccccaagct'.
'cctggcatgtgtgtgccaggcgcaggtccccagagtcagggcccagcaggaccaaagaagggcgggtggaggtgcag'.
'gtgctgggagtatgctggggggaggtctggctgctgggtttagcggggcagggagctgagccagggagacaggactc'.
'tgcagggagagccctctagggtcactctgtgaagaacccagaggccgcagcaggaggcaacccccccagcctctaag'.
'ctgggtggtgaggagagcccccttccccgtggctgctgggacagctccaccctgactccccactgtgctagccctca'.
'gtcagtaacaggaaccatgataatcacaccacatcccaagtctccctgcatgtacttgttccggcctcctaacccca'.
'agccaggggctcttgctgtttcatctacaggttagagcactggggtgctgggaatggggtgtcccagtggtctaact'.
'gctcactgcataccccaactttagagttcttagggcctggccatggaacacagaaggctctatacctcctgaggctg'.
'agtaggggccggagcccagtctgaggataatggccagcagagaaaatgaggctcccaggtcagcctctaagctgcag'.
'gcagagctctgggcctcctcctggggctgacccaccagtgcatgcaatgaacactgtggcagggttaggcatggtgc'.
'aggcaaacccctaaagtgtctctaggcagaccaaagagctgcccagaacagaccccatccagctgcctgggccctga'.
'gggctcagtggagggtgctgttctgagtgttgggctgtgtcctgcccactcttcacatggtgcctagtacacccaag'.
'tgggacttccagcccaacctgggatcccattttcctttcctccccaggagccccagcaaatcttgcaataagcgagc'.
'gcatgctggcttgtggtccaccaggacccactgattgttttcccacttggcaattttcacccttcccaagtcactag'.
'gctgttacctggaggaccagctgttgccaggccattggcaggggctgcccactgcccatgccaccactgaccatgcc'.
'aggctgctgggcacgctccagctgtagggcaacatggcgccgctcctgctccagtgcccgtgtcagcctctcgaagc'.
'gggcctcctgctccttcaccgaggccaggatgctggcggccgagtgcacattgcagtcctccatgaccagagcgccc'.
'gccagctgcaggcaaagcagagtaagctcagtggggtggggcacagcctggcaaggccatcatgggcccctgcccgc'.
'cccactcacagaccatacaactcactcccagaccagagcatccagccctctagagggaagcacactgattaaattct'.
'aaattaaaagccattaatccgaggctggccggaagcagccggctcactccccatgggttttgggactctaacccggc'.
'tcctctgcttcctgctagacctagcagaaacatgggccgtgggcggcttggagcccgctgggaagggcaggaagagc'.
'tcattagagcttcttacctcccaggccctctgccactcataccacatgccagcccaccctccatttcacagggccac'.
'cccactcccatctcacagaggcagatgccagggccaagaaagggtgggggaccatttgtagccacacagctggtgtg'.
'gcatggccagtgtggccagcaagcagggagtgagaagctgctccactgatgggtgcccaagaccccgaggcaggcgc'.
'aggtgaccatagcctgagagctcctggcaacactggtctgcagaccagcagtccagcctccactcatatccacattg'.
'gccagaaacaagagtggtgctgctacacatgacagagtaaaaactgaggacaagcctggttgaggttctggctggga'.
'ctgcatgaagttaagagaccataagcctgaagtggctggtgtgtgtgatgcctcatccagaaaagggcaggggccag'.
'gcatctgaggccaagcacagggtgggattgggcctgctgggcccagcccagtgttgcccctcagggccccagagccc'.
'caggggagcaggcgggggccatgagggcttggcagccgcagagacaaaccagcactttccctcccagcttgccccct'.
'ggctgcccagaatgtttgtttttcatgggtaaaaagaagcaggacaagtatgcggagctccaatccaggctcaccac'.
'agtgggcagggcatagccacgaggccacactgcccggagcacagtgagcatggccgggtgcccagggctgctcaggc'.
'atcctcctgcccagtcccgccagcccactgaggccaactccgctggatcccttgcccttgcaccaatatagggccct'.
'ccacggggaggacacgcactgcgggtgacatccccagagcgtcagcactgctgctcactggtctggatggagccagc'.
'tgcaaggacagagagcccccaagaggaaaagcagcgctgggctcagctgcgccagcaacacggtgcggggacatggg'.
'tgcacctcataggtgaagagacactgtggagcccagccccaccgacagctgggaaaacaggcccagcaagagcgaga'.
'gaccagtgcaggcccccaaagctgctctccatttccccagcacctgtcccacaaatgaaactgtcaacacaaccttt'.
'cggggaagccagcatgagtggaggagctgttttaagccagccacagaatggaagaatgcagggagagctgggggccg'.
'ccgcccgagactgaggtgcagactgggcgctccagcaaagggataaacagcactgcactccccaagcatggtcacac'.
'agctcttctctacacacctgatgctgtctacccacaggccccagacccaacacaggggagccttgtgcactaatgga'.
'ctgaacctagtgctaggcccgaggtgggaatggtagggtattccccctgggacggccagggcggatggcagggccca'.
'tatcactccagccctcagcccagtcctggctgcagcaccagcccatctcagccgaacctcagaagcaagggacagaa'.
'ggaaatgggacgctgccttggatggcaacaatcaggaccacaggatagccactggcctcatggacctggggtggctt'.
'acttccctccctgtgcagagacatggaccctcgtctacaccacataccccatcccccatctagcaggaccaggcttg'.
'ggctgcagaccctgcggacagcttccctgacctaagcccctccagcacaccctggctctggggactaaagatgccca'.
'ccctaaagggggcccactggctctggctgagggctcagtactccaaggccacagtgggaaggtgaccaaaccccacg'.
'atgaccttctcattgccgaacttggcttgattggtgcaaaacaatcatgtatctccctggagacatccagaaacact'.
'ggccagtgttgtggggagagtctggcagccatgctcaggagagcagagaccttggtgctgggcctgtgccatctgcc'.
'ccagccgcagggtgcaccctgcatttgccctggggggaagtgccctaggcccgcaggtcatggcctcggcatctcag'.
'gtgtctcaagagcaacccgggatatgctccaggcagagcacagaaggcccaggcccactcccctgacatggtggact'.
'ctggcctatgacaggagccagtctggatacaagggatcctggcccagaaccaaagagggctgcttttcagatggtaa'.
'ctcaaaatgctgtttttatattcaagtaataaatatatgatgtcaaggaaagcaaaatgtgcatggattcttaagat'.
'cgatggggcctgagtggatgctgggcagagtgggcaccggatttgcttttgctagagcccaggagggccctggggga'.
'aggctaggaagggggacactgcagggaccttggctgtccagccaatgccaccttggcctcccctaacctggtaaggg'.
'cccagcattgccttgtcgggtggacccctcatgaccccccacccaaaacacagcaaccagcttcatgcccaactctg'.
'aggaggccacttcttgccaaacatgctggccccagaagtttacttagccgcaaggcaggaatgacattgcacagccc'.
'acgagtgaccagacttcaggaccatgtggacaacaccatgttccaaccagaaaacatcaggaactgaaggggggctg'.
'gaaaggtcggggctaaactgaaactctgaaaaataaactgcaaaacaaaagtgacgacccagcccccacccagcccc'.
'agccacaatggacattggccacgtacccaagggaatccaggaccaggacgtgagcctccaggtgctctcacaggaca'.
'aactgctgggcaagcaggtggcccgaggagagaagcatggcaggagaagagggtggccccaggcacacagcccatgg'.
'aagactagagggagggcaagcaaaggagagacagcgaaggatggacagacagatggatacaggggtggatgggggat'.
'ggatgaatgaatggagggtggctggggcagtggtggaggatggacagagggacggacagattgatggacaggtcgga'.
'ggatcgtgggagatggacagagatgaatggatggatgggggatggtggggaatggacagatggatgaatgaatgggt'.
'cggggggatgctgaaggatgaacttatagatgaatgaatggatgggtgggtggagggatggtgggagatagacatac'.
'agatgaatggatggatgggtgggtggggggatggtggaggatgaacaaataaatgaatggatggatgggtgggtcgg'.
'gggatagtggaggaagaacatatagatgaatggatggatgggtgggtggggggatggtggaggatgaacatatagat'.
'gaatggatggatgggtgggtggggggatggtggaggatgaacaaacagatgaatggatggatgggtgggtgggggga'.
'tggtggaggatgaacatatggatgaatggatggatgggtgggtggggggatggtggaggatgaacatatggatgaat'.
'ggatggatgggtgggtgggggatggtggaggatgaacatatggatgaatggatggatgggtgggtaggtggggggga'.
'atgatgggagatggacatatagatgaatggatggatgggtgggtcgggggatggtgggagatgaagatatagatgaa'.
'tggatggatgggtgggtaggaggatggtaggcgatggacagagagaaaaacagacgcatagatgggatggtggggga'.
'tggatggatgaacgtatggatggatggggggggatggtggaggatggacagacggatggacagattggggaatgagg'.
'ggtatggacagacagacgggtgaatggatagggaggtggatgaagtcatagaagggtagacagctagatggatgatt'.
'ggatgggtttacagatgaatggatggatgagtaatagatttgtgggtgggtggctggagggatgggagaagaggagg'.
'ccagatagaagggggtgtaactgagtgagtgaacaagtgtgtggacaggagactaataggtggttatataagaaaat'.
'gaggggagatgagaggatgggtgaatggtggctagttggatgggaaggtggctggatggatacgggtggtggtagag'.
'ggataaaatgatgatggaagaatgtgtaggagggtgggcagatgggatgctgaaggctgggtggatggaggagtgga'.
'tgaaggagaaaacagagtgcgatgcatgaatggaagggggggtgggctgtgtaagggccggtgggcaggaaggaaat'.
'gctggaacctcactaagtggggaaagccccggcccgcaaaccctctggggcaaaccatggtcaacacacactgtcag'.
'gaacacgaaggcatggtgaggaacctgagggtagaagctaaatcctttccctgaaaccaaagctgacatttgacgac'.
'atcttgacaacccagacattcctcctcgggagtgcggccagagccttgtccggaaaatgaaattatggggcccgagt'.
'ccagtgtgggttgaggaattagaggaatttccgaagggtcaggccagtgaagggtggcaggcggggcctggctccca'.
'tcctgaccccttgccagctgtctaccagaacacagccagggctgcgctggcccccccctcgaggggagagacgggac'.
'ggatgaccatcgagcctcctcccataccccctttcccctccacccttccctacaaggaggaaatgatgccagaagtg'.
'ccctggcaggagttggacccaggcccagcacccaccttctgcctgggaggacatcctgggagctgccagcacagaga'.
'cttcctcgtccccctagctggccaggccttgtgggggccccatgtttaccctgttgcccctactgtggtcagatggt'.
'gcccaaagccttgtgggtagcttctggccaagcccactggccgggcactgtactcaagctgggacagggccagagcc'.
'gggggcctggggttcacagggcggagtccacatccatctgtgccaaggccaggaccacagtcccttgcagactgtgt'.
'tggatccggggtgcctgggctggggatgactgttctcagcctccaagcagcagaaagaacccccgaggaaagacgca'.
'caagcgtgactttgtgagaatgaaactttctgtatatccaaaaaaaaaaaaaagggccacacagtgtggtcatgttt'.
'tttaaagaactgacaccatttagagcaacacatgcagtgagcgttttgatgaaatgacgggtgctggcgttactcgc'.
'agaccatgactccagcatggtgaggctggtgtggggtgtgcaggacccatcacactaggctctccacttctgtgctt'.
'ttgtaattttccataatggaagaagcagccacaaagaaaatgaaaagacaatcgacatgttgggatcaagtatttgt'.
'aacatacaacaacaaagtggcatcctcagcccattaggtgctctcataggctgctccagagccccacagtcctgccc'.
'ctgccagtctaccactcctcgaagcacgcgccgctggcataatcagaacctcagtaggaaatagacaaaccagatac'.
'cctccccaccaggcaggcgagtgaaagcagaggccagggaccaatctccccaggggccagggcggtgcccactgtca'.
'gagagccataatcagattcagcctggaaatttgatttccccagcagaggcaatgagccaggctggatgagacgccat'.
'cgggggttgggtagagggacagagatagctccccaggctgtccacatgctcactcagtggcacccgctgatcatgtg'.
'agggaccactcccatgtccagggagaatactcagaaagggcctcttcccacgctgctcctgccctgcactaatgcag'.
'tgcccaaggccaaaggtggccaagaccaaagctacactggccaggcccagggggcatgctggatgggaggtccaggg'.
'ggactaggggctgtgtggggctgatacggaagctggggtccggtcaaggcagggtcactgctgggggccagggagct'.
'gggaagcctaaggttagggcaagggctggctctagtggccgaacgagcccagtgactgcaggcaggacgtgacaggt'.
'gagcaggcagggcaggcgagtgtcccagcaactgtccctcctctgtgggaggcatgagccacagggagccactgctg'.
'gaggtccctaaagggtctgggcttaagattctcaatccagcaggtcacagacacctgctccctgtgccaacagcagc'.
'atcctttaagtctccttggtctcctgagacctgcctctccatgaggagacatgagatggggtggaaaggagtcctcc'.
'aggtcccgattcaaaacagcccccaatgcccttcctgtgcctgacccagactctagctacagctgcagcagtgggtg'.
'gtcctgcagactccaagccgtggagtagtggcagtgaggggccacattctctgggctccctgctgcatcctgcccag'.
'ggcaccaccaagggctcaaaggctggggagctccagggagagggctgcagaggctgccagtgcagtgtcttctcccc'.
'tgcacactcagcccacccactccgcccccaatgatgagcatgaagtttgtaggagtgtggagaggtgtagtgcccta'.
'ctaagtgggccggacattggtggcggtggctggcccattgcctccacggcttaccgggacgggcacccaccccgcaa'.
'ggtgccgtgtggcccatgccctgccttagggagggcaggcgcagtggaggcggaggcggggtgtaaaaggcccagac'.
'atggagctgagccccatcctctgtactctggggtgggcacagggaccaaagcatccctgaggagcgaactgacaggg'.
'ttcacagctaggctgggatcagaggcagacagccacagggcctgggagccctgccctaccatgccctacggccccac'.
'tgaggcactgtaggagacagctgtccaccaggctgaggggcctcagcgggcaggtgcagcagtcaccacgctggcca'.
'ccagcctgagtgcacagggccgtccgcctgcaacgccctttcccccctcattggaagacggggttagaccccttctt'.
'cccagcccctctatcaccatggaaacacccaggcttctcctgagggacagagcctctttgtggtgacacaaagcccc'.
'tttgaggggaggtggggtgcagcccctgggagcctgtggccaaagggcccctggggggtaaagcagggcccgccggc'.
'ccagcccccctcccaggtttcggagccaaggaagctgaggtaggagagccttcaggttaggccagcccgccccagct'.
'gcccacccagaagggtctccggatggatgagccggacagcccaggaggccaggctgaggctgggcagagacagcacc'.
'gagaagcctctctgcaggagctggggggttcctgctttcctctctgttgttttgacaaagaacacactctgcttaga'.
'taagtggaaaacagcactggcaggggagctcccgccagtcaggaaatgcccaggatggctgcaggaacagtgcctgg'.
'tgggagatggggacaggaagtcctccgtgggagggcaggcaggggccgtgagacggcaggtcagacagtgggaggtc'.
'tggcaccaggtgtgccgagaggactggccctggcatctgggccccactcagtttactgtcctctcacttctcaagcc'.
'tcagcctccgtcttcacctatccgcccagggggaaatgtcactggccttgctgcagccacaactctgggacaggcca'.
'gagttggataaaacggaacctcaccatggcttggcttattccagggctggggaaatggaaccctgaggatgatgtgg'.
'gtccctggcacagtgacagcatggctgtcccatccatgctacagccccacagccagggaggcagaggaggccaggcc'.
'acatttccccagactcccagccctggagcccctcctgtactggcctgagagtccctgcccccacccactgactgctg'.
'ctgaccaggcacctggcagctccctgcatgtgggcgccctgcctagaggccctcccgagttgacctcactctgaccc'.
'acagcagctttgctaactaagcccctggggtggggttggggtggggatcactggccccctgcggcagcacgaggagg'.
'cactggcccagggagagatccatccttttgtaggcaaatctacctgactactagggagtggggccaagggctgcccc'.
'cacagggcagtgcctgggtcagcaagcacttgctgcacccccaatggaggccctcaccacacccctcccaacctgcc'.
'ttccccactggcaccccactctctgctgacacctgcaggcacaggggtgggggttgggaccctccagctgccgtggc'.
'agggagtggccatagggtggttgctgtggtggacgtaggccatatggttcagaatggatcagaggatggtgtgggtg'.
'ggagaattaagtctgggctgaccgcaagggatcaggcctgggtggctggagggaggggccgggaccctgagtgggag'.
'ggtgcaaagggagtctctgaggctggagaggctgagggaccactagatgcatgaagttctggaagaaaggggttcag'.
'gctggagacagaaccaccggcaccttcagcctgtgaagccgagagataagacaggtgcaagccccagtgcctcctcc'.
'aaaggaccctcccctgaccttctagaacaaggggacaaagtcactttcccagccatcatcttccctgcactggaagg'.
'ggcagaacgaggacccagcactgagaggtgagcctcaggaaggaggcagtgctgccagcccttggggacaacagcct'.
'gtcccctgaaagtcccaaaacccttgggaaaggtgctcctcactgtacccttctcccacccagcacatcagaggagc'.
'cagtggtgtgagatcttgacccagcatgaagtagagcccaccctgtcatatgcagggaggttccatgtcccctttgg'.
'tctgcccttgccccagggtcctgtgtggcctctggccagcgctggctgctcccagggtgcctggggcaccgctcatc'.
'ccttccagagcctgagctggatgctggccttgccgctcccaaccccctcctctgctgggagccagctccactccgga'.
'gtgcccatggcaacaggcctagacaccaacctccagcaagtgcacaaagtcctgcctttcatatgcaagcaacacag'.
'agggccaggcagggggctgcaccaccccatccagggcagattccaggccctgcagcctcccatctggctcccaccgc'.
'cacataccaggagagcctcgggacttgactgtgtgtccagtccccactacaaagaggtgggagaagtgctgacagtt'.
'tggggccctcctcaaaggcacctactggcacatgtgtgcagccacccacactgctacggtgtgaatgctagtgttcc'.
'ccaaattcacattaaaacctaatctccaatgtgacagtattaagaggtagggcctttaagaggtgattagtgccctt'.
'atatgatcagtgtccttatcaaagcggctcttgagggctggtttaccccttccaccatgagaggacacacagcgcca'.
'tctatcaatagccctcaccagacacggaatctgctggcgcctcgatcttggacttcccagcctccagcactgtgaac'.
'agtatgtttctgttgtttataaaggactccatctaaggtatttggtggcagagcgtgaatgaactaagacacacaca'.
'gacacacacacaagcacacccacgcacagggacccacagctgccccacaggcacacgcaccagcaggcacactcgtc'.
'cacacccatatggctgctgcttatcccacctagaagtcccgacaggccctttggggggtgggggacatcttggctcc'.
'tggtgaagatcagcatgctaggcagaccccattcctgtcttggacaccgggcaaggcagaccccctctgagacccct'.
'gaggccgggtcaagcctgcccctgacaccaagatctgcaggaccccctgcctctgatcccacatgaggttcctctga'.
'gacaggtgggagtggctgggcctgcagaccccgagcttgcacagacccacctgcagggacaagcacaacttacagca'.
'gcctagtgcccagggaagacccttccaccatgggaggactcaggaagccgcttcccgctgagtcacatttagcgcat'.
'ttcttaggaaacagctggtatgtgccctagaaggttaaagacggtgttcaactccgctggccacagaccacaatgaa'.
'aaggagctgctggctgggcacgatggctcatacctataatcccagcactttggaaggccaaggtgggaggatcacct'.
'gaggttgggagttcgagacctgcctgaccaacatggagaaaccccatctctactaaagatacaaacaaaattagctg'.
'ggtgtggtggtgcatgcctgtaatcccagctactcaggactgaggctgaggcaggaggcagaggttgtggtgagcca'.
'ggatcacctcactgtactccagcctgggcaacaaaagcaaaacttcatctcaaaaaaagaaaagaaagaaagaaaag'.
'gagccgctataaataatgaggatcccatggagatttaaaggaaatcccagcagaggcagtaaacagcagactgtaga'.
'aaacacgcagtgtgaggctggagaaagtacactaagacggtcctcccaaccccaacagcaaacaggagagatgacaa'.
'gaggatggtaggagccacagaagacagagcccagggccaaacttccacatgataggagtttccagagcgagaacgac'.
'agacagtgctcttccaaccacagaaaaacggccagaaaccacctcaacaggagtacgtccaacggggctatcagcgt'.
'cagggctggaatctgagttagggtgtgagccttctgtccagaaaagaagcccaggaagtcacggatgtgtctacctc'.
'tggcttttacaattcagtctcatttcctctggctcctaaatgcgctgtgtccacttcgaggtgtagggaggagggtg'.
'cccagctctgacctgcgggctgtgctgaagcctgggcctctctctataccaggccgtctgcaggcctgcaggggctg'.
'catactgtccctctgtaaatgtcagcctcaacacgctgctgcctgctgcctggctcccgtctctcacagctcagaag'.
'ctgttttatgataaaaaagagctgacagctttgttaaaacaaacaaacgcctctcctctctacttgagatcttttac'.
'aaagttaacatcgctctgaaaccccataaggaaaaattatggtgaggtttctggattttcagaggcagcaaactcat'.
'cttacctagagccctggactacccagagaagtagttttaagaaccaaaagaagagaagaattcaggagtaaatgagg'.
'cctggataacccaagggatcctgtgcttgcactgctgggattcaaatttgggggctgccaccaccacaagtttgtga'.
'gaagcccacagcctgcgcatgaagattgtgtcaagggaatagcagctgctgatgtgtggaattgattttttcagcaa'.
'gggcctgcgattctgaatgcattaaggcagctccagttgtctgtagcagtcctctgtcagctgcccattggaagcat'.
'ttttactggctcaggaaattcatgggtttgtggactgatgactccaacagattaggtacaaatccaagaaccacaaa'.
'acaaaatctaaccaagccaaacaacaatcaaacaataaaacagaacaaaaaaaaacctcaatttgttttccttttct'.
'ttgtataacattaaaataaaaagatggtaacagactaccataaagaattatacaccaacaaattagataacccagat'.
'gaaatggaaaaatttcctagaaacacacaacctaccaagactgaatcatgaagaaatagaaaacattgattagattt'.
'acaactagcaacaaaactgaatcagtaatcaaaaacctccagcaaagatggtttcactggtgtattctaccaaacat'.
'tcaagtaattttaacaccaatcgtcctcaaacttttcccaaaaataaagaggaaggaacacttcctaattcatttta'.
'tgaggtcagccttaccctaataccaaagccaggaaaagacactacaagaaaagaaaaccacaggccaataaccctta'.
'tgaatactgaaacaaaaattctcaaaacaaacaaacaaacaaaaaaacactagcaaaccaaattcagctgcatttta'.
'caagaattataaacctaaccaagtgggattttactcctggaatgcaaggatggttccatgtacaaaaatcaatcaat'.
'gtaatacgccacagtaatagaataaaggacaaaaatcacaatcatgtcaaatgatgcaggaaaaacatttaacaaaa'.
'ttcaatagtctgtcatgataaaaacactcaaactaggaaaagaaggaaactttctcaacatgatgaaagctatatgt'.
'gaaaagcccataacatcatactcaatggtgaaagactgaaagcttttctcctaagatcataaacaagacaaagatgg'.
'ctgttttgaccacttccattcaacatagtactagaagttttagacagagtaattaggcaagaaaaagaaataaaaga'.
'catccaaattagaaagaaagaaaaaccatctctgttcatagacgacataaccttatataaaaccgtaaagattctac'.
'atgcattttttaaaaactctattagatgtaaaaaatgaaatcagcaaaggtgcaggataaaaaatgaatacccagaa'.
'atcagttgcatttctatatatgaacaatgaacaacctgaaagggaaatttaaaaaaactattccatttacaatacca'.
'ttaaaaagaatagaatacataatactaaacttaagaaacttaagatctgtacactgaaaactataaaacattaccaa'.
'gaaaaatttaaaaagacctaaatcagtggaaagatatcccatgttcatggctgggaagatttaccactgtcacaatg'.
'acgatactactgaaagggatctacagattcagtgcaattcctattaaaatcccaatgacagccaggcatagtagcat'.
'gtatctgtaatcctagctagtcagaggctgaggctaaagaactgcttgaacccaggggttcaaggccgcagtaagct'.
'aggatcacaccattgcattccagcctagatgacagaacaagacctgtcaaaaaaagaaaagaaaagaaaaaaaaaat'.
'cccaatgacattgtttgcagaaacagagaaatctatcataagatttatatcgatctttaaggagcccaaagagccaa'.
'aacaatctggaaaaagaacaacatttaaggactcacacttcctgatttcaaaacttactacaaagctacagtaatca'.
'aaacagtgtggtattagcataaggacagacacaaagaccaatggaatagaatacagagcccagaaacaaaccctcat'.
'gaatacggtcaaatgaccttcaataaaggtgccaagaccattcattagggaaatgatggtattttcaacaaatgatg'.
'gaactggatacacacacgtaaatgaatgaactcacacccttaccttattacatacacaaaaattaactcaaaataga'.
'tgaaagatctaaacataagacctcaaactataaaactcttagaagaaaatataggggaaagtcttcatgacactgga'.
'tttggcaatgatatcttagataagataccaaaaacacaggcaacagaaggaaaaataaattgtactacatccaaatt'.
'taaaatgtatgttcatcaaaggacacaatcaatatagtgaaaaagcaaccaacagaatgggagaaaagatttgtaaa'.
'tcatatatctgaaaaggaattcatatccagaatatgtaaagaactcccaaaacttaacaacagcaaaaaaacacaaa'.
'taacccaatttaaaaatgagtggagttgaactgacatttctccaaagaagatatataaacggccaacaagcacgtta'.
'aaaaatttgctcaacatttctatcattagggaagagcaaatcaaggctgcaatgaaatatcaccttacacctattag'.
'gatggctagtctaaaaaaaaaaaaaaagttttggcagagatacagacaaattaagacccttgtgcactgctggtggg'.
'aatgtaagatcagtatggcaattcctcaaaaaattaaaaatagaattaccatatggtccagcaatcagaaaattctg'.
'cattatgtatctaaaagaattgaggccaggcgtggtggctcacgcctgtaatcccaacactttgggaggccgaggcg'.
'ggtggatcacaaggtcaggagatcgagaccatcctggctagcacggtgaaaccccgtctctactaaaaacacaaaaa'.
'aattagccgggcgtggtgacaggcgcctgtagtcccagctacttgtgaacttgggaggcggagcttgcagtgagcca'.
'agatcgtgccactgcactccagcctgggcggcagagcgagactccgtctaaaaaaaaaaaaaaaaagaattgaaagc'.
'agagtctccaagagatatgtgcacaatcatattcacagcagcattattcacaatagccaaaaaggggaagcaaccca'.
'agtgtccaccagtggaaaaatggataaacaaaatgtggtatagatatacaatggaatatcaggcatcaaattctgac'.
'atatgatattctcatgatactaagtgaaataagccagtcacaaaaagacagatactgtgagattctatttatgtaag'.
'gcatctaaagtagtcaaacaataggaaaagtagaagcacttcaagaaaggggcaaacggggagttttctaatgggta'.
'cagagtttctattttgcaagaataaaaaaaagttctgaaattggttgcacagcaatgtgaacaaacaacactactga'.
'attgtacacttgaaaatggttaagatagtaaattttgttatgtgtattctaccataattaaaaattaaaattaaaaa'.
'agaggctccctggccaggcgtggtggctcacgcctgtaatctcagcactttgggaggccaaggcgggcggatcacga'.
'ggtcaggagatcgagaccatcctggctaacatggtgaaaccccgtctctactaaaagtacaaaaaaaattagccggg'.
'tgtggcggtgagcgcctgtagttccagctacttgggaggctgaggcaggagaatggtgtgaacccaggaggcggagc'.
'ttgcagtgagccgagatcgcgccactgcactccagcctgggcggtagagcgtgactctgtctcaaaaaaaaaaagag'.
'gctccctcacataataagtaagaaattgcataatacccttttatttatttattttttgagacggagtcttgccctgt'.
'cgccaggctagagtgcagtgg';

return $seq;
}
