## Bioperl Test Harness Script for Modules
##
# Before `make install' is performed this script should be runnable with
# `make test'. After `make install' it should work as `perl test.t'
#-----------------------------------------------------------------------
## perl test harness expects the following output syntax only!
## 1..3
## ok 1  [not ok 1 (if test fails)]
## 2..3
## ok 2  [not ok 2 (if test fails)]
## 3..3
## ok 3  [not ok 3 (if test fails)]
##
## etc. etc. etc. (continue on for each tested function in the .t file)
#-----------------------------------------------------------------------


## We start with some black magic to print on failure.
BEGIN { $| = 1; print "1..5\n"; 
	use vars qw($loaded); }

END { print "not ok 1\n" unless $loaded; }


use Bio::EnsEMBL::Pipeline::Runnable::Halfwise;
use Bio::PrimarySeq;
use Bio::Seq;
use Bio::SeqIO;

$loaded = 1;
print "ok 1\n";    # 1st test passed.
my ($seq) =  set_seq();


my $clone =  Bio::PrimarySeq->new(  -seq         => $seq,
                                    -id          => 'HSAC74',
                                    -accession   => 'ACOOOO74',
                                    -moltype     => 'dna');


unless ($clone) 
{ print "not ok 2\n"; }
else
{ print "ok 2\n"; }

#create VectorMasker object    
my $halfwise = Bio::EnsEMBL::Pipeline::Runnable::Halfwise->new (-CLONE => $clone);
 
unless ($halfwise)
{ print "not ok 3\n"; }
else
{ print "ok 3\n"; }

#run Halfwise                                                
$halfwise->run();
print "ok 4\n"; # 4th test passed

#get and store the output
my @results = $halfwise->output();

unless (@results) 
{ print "not ok 5\n"; }
else
{ print "ok 5\n"; }

my @methods = qw( seqname start end strand hseqname hstart hend hstrand );
#Display output
foreach my $obj (@results)
{
    print "\n";
    foreach my $method_name (@methods) {
        my $value = $obj->$method_name();
        printf ("%10s = $value\n", $method_name);
    }
}

sub set_seq {

my $seq = 
'cctgggctgcctggggaagcacccagggccagggagtgtgaccctgcaggctccacacaggactgccagaggcacac'.
'acctgctctgtctacccgagggcaccagagggcacgagaaggctggctccctggcgctgacacgtcaggcaactgag'.
'gcacaaggctggcatttctgaaccttgcccctctgcaaacacaagggggcgatggtggcactccaagcaaaggggcg'.
'tgtgggtgctgcaggaggagcacagagcactggcgcccctcccctcccgccctgcagatgccggaggccccgcctct'.
'gctgttggcagctgtgttgctgggcctggtgctgctggtggtgctgctgctgcttctgaggcactggggctggggcc'.
'tgtgccttatcggctggaacgagttcatcctgcagcccatccacaacctgctcatgggtgacaccaaggagcagcgc'.
'atcctgaaccatgtgctgcagcatgcggagcccgggaacgcacagagcgtgctggaggccattgacacctactgcga'.
'gcagaaggagtgggccatgaacgtgggcgacaagaaaggtggggtccgggccagcaggtgctcagctctgggacagg'.
'gacccaggaccaggcatcaaagcccttacaggagaagctgttatcaccccatttccagggggctgggaaccctggga'.
'tatgcccagatagggctggggggctcctctggagtcccagggtgccagggtccctgatgacccctgcaggccctgct'.
'gcctgctgccccaggacaacaggcccccacactcacagggtctgacggtggtgcagttccccttgaactctgttctg'.
'gccaccatgggacctgcctggggaccagtcagacaggttctcctgggcccgcctcccgcttgaacttcagcctgggg'.
'cacaggatgtgttaccgggctcacggagtgactcagggaactagtgccgccccagggccccaaggtgggcggttcgg'.
'tgattcagagagggcagctctgtgttaggacacactggggccagccaggaagggtggaaaagatagggaccagcgtg'.
'agcatagaggctaagggaccatgggagctccaagcgcgctcacagtggggaccaggtcctgggggctggggacacca'.
'gggaggtgaaatacccctccagcgggtagggagggtgggcagaggagggccagcggccaggcatttgggaggggctc'.
'ctgctctttgggagaggtggggggccgtgcctggggatccaagttcccctctctccacctgtgctcacctctcctcc'.
'gtccccaaccctgcacaggcaagatcgtggacgccgtgattcaggagcaccagccctccgtgctgctggagctgggg'.
'gcctactgtggctactcagctgtgcgcatggcccgcctgctgtcaccaggggcgaggctcatcaccatcgagatcaa'.
'ccccgactgtgccgccatcacccagcggatggtggatttcgctggcatgaaggacaaggtgtgcatgcctgacccgt'.
'tgtcagacctggaaaaagggccggctgtgggcagggagggcatgcgcactttgtcctccccaccaggtgttcacacc'.
'acgttcactgaaaacccactatcaccaggcccctcagtgcttcccagcctggggctgaggaaagacccccccagcag'.
'ctcagtgagggtctcacagctctgggtaaactgccaaggtggcaccaggaggggcagggacagagtggggccttgtc'.
'atcccagaaccctaaagaaaactgatgaatgcttgtatgggtgtgtaaagatggcctcctgtctgtgtgggcgtggg'.
'cactgacaggcgctgttgtataggtgtgtagggatggcctcctgtctgtgaggacgtgggcactgacaggcgctgtt'.
'ccaggtcacccttgtggttggagcgtcccaggacatcatcccccagctgaagaagaagtatgatgtggacacactgg'.
'acatggtcttcctcgaccactggaaggaccggtacctgccggacacgcttcttttggaggtgagccccaaccaggat'.
'ggcatccgtgccagctgctgcccagagcccattcagtcagcctcagcctctccaaagagccaggcattccagtagag'.
'ccctgtgtggacacagctcgctctggaggcaccacctgaggtctgggagtgtgggggactgaggaggccctgtggtg'.
'ggtggagatgggtggggagctgggccaggggcctggctgggtggcctgttgggaactggggagccagctgcctgtgc'.
'aggtgcaaaatgggtggcagaagtggggtgcacaccccagaccagacaccagggcagaaacggcacaggaccaagga'.
'gatggggtggggaagggccgctctgggcccagcctgctctcccccaagcaagccactgctcgtgcaaagaaagcatg'.
'tgtctcctgcagatcttcctcctgaggccccatcttgtgcattcccccaacccagccccactggcgaggaccctgag'.
'tgccccgagtgaggctagacagcgggtggggctgtcctcgcttccctggggggcgtggggcactggtggcccttcac'.
'agactgatgcttaaggagcctcacatcagtgacacactgccccatccctccctggtggtcagcgacactgagtggct'.
'ctgtgatcctccactgggcttgggacacccaccctcacggcctctccacctggtgctcgctcacctgcagctctccc'.
'agaaactggacactgctgttagcagccagactaggagcacgaggggcacagcccccatgcctggctaggtagggccg'.
'ctggaccctggacacggattggaaggaaccagcactagcagaagcctgaggtgtgaaagggcagagaatgttccagg'.
'aacaatgggagtcagggcacacaggactttgggcaggtgaggatgaggttagacctgtcttctggagctgggctcag'.
'gggctcatgcctgtaacccttgcactttgggaggctacggcaggaggagcgcttgaggccaggagagttcgagacca'.
'gcctgggcaacatggcaaaagaaaaaatatatatatatattttagatggagtcttgctctgtcaccaggctggagtg'.
'cagtggcacgatcacggctcactgcaacctccacctcttgggttcaagcgattaccctgccttagcctcctgagtag'.
'ctgggactacaggcgcgcgctgccacacccggctagttttttgtagtttagtagagatggggtctcaccacattggc'.
'caggatggtctcaatatcctgacttcgtgatccgcccgcctcggcctcccaaagtgctgggattacaggcgtgagcc'.
'actgcgtccggccgtattccagcttttaaaacaacaaaaaacaacaaaaacttttctggaaagatccctgtcagcct'.
'tgtggagtgtggagagggctgtggggagggcatttcagatgccctgaactcacgaggaggcactgaaccctggccgt'.
'ggagagggaggacctgtagtggccaagggggtgggcattgggagggtgggagggagacctacaggccaagacagggt'.
'agctggaggggggctcacccctgacaaaggagcatgatgctggcaattgggtattgatggcagagagctggcactca'.
'gccagatgggcttcacttgggcaggaaagacacccacagctgggcctgcgttactgcggccgagtttcagcagctgt'.
'gatgtgggtgctaattacaggggcctgccttcatagaaaagtagcaaacattgcagtttagtaactaggaaactaat'.
'agttttctcagtgctgcttgcgcaaagctggtaattatctcaaaagaagcaaagtcatgaagtgggaagtcatgaat'.
'tgggaatgggtgtccttgttaaacgcacatctgcacactcagggctggggccctgtgcccccttgtggagggttagg'.
'ggacaacctggctcttgtgagggtctagccatcccctcagtgggttctgtgagcatcggaggcacggggggtgaggg'.
'gctcaggagcaggttgcaattcaaaatcaagggctgctttgaggaggcctctccaccgggctgctgtagtcaccaag'.
'tccagcccatgcccaaaggaagaggaatgagttcccccttaaaaaaaaaaaaaaaaagaaaaagacagagtcttgct'.
'ctgtgcccaggctggagtgcagtgatgacatcatagctcactgtagcctcaaactcctgagctccagtgatcctccc'.
'acctcagcctcctgagtagctaggactaaaggcatgcaccactacacctggctaatttaaaaattttttgtagaaat'.
'ggggtctccctatgttgcccagactggtctcaaactcctggcctcaagcgatcctcttgcctcaacctcccaaagtg'.
'ctgggagtacaggtgtgtgcttggtctgaggctccaactttttgttgttgtttctcgagacagtctctcgctctgtt'.
'gcccaggctggagtgcagtggcgcgatcttggctccctgcaacctctgtgaggctccaactcttgaagggaggagag'.
'tctaaggagggtgggccagatgaaaaccacctcagcatagtgtcacctgctcctctgacactgtcgcttctccatgg'.
'cattagattttcagtcctgctcagacgctgatgcatgtttagccagttctccaggtggtctgagtagctggtaggag'.
'gcttgcagtgtcgggcgacaggcaggacaggtgctgccttctttcccctcttgaccagtttcgtaaaggagtgggcc'.
'cctggcagcctccaaaggtgacccatgctcctttctgcccttccctccttctttcctgtttaactcgtgcaggtgca'.
'gtggtctggtgtctttcagtccgctgacgtcttctgtatccctgatgaccagattgggctcctgagtcccctggcgc'.
'aacccgagaagtccaggagcccaggcccctcactcatgcattccctggcccagactggaaggcagccgccctgctca'.
'aggcctaggccattgtcctcctcccgggtggcgctttgttctacgtcttttcagctgacattgctaggacatttttt'.
'tttttttctaaatgaaaacacatcatgattcatggtggtacttcctgctcaactccggaccttggggctgtcccctg'.
'acctcactgaccttgcagccgtgtggtgtccatactgtcacatgaaagccccctgctttctctgcagcatacaggct'.
'ggaaacgaccgccacccaccaccaggacagctgcaagccctgtgggactctccaggcccatcccagaggcatgtggg'.
'gtcggataccagtgtttcaaggcacctgcctgcaaattgattttattatactttagatgtttgagattgcttgttaa'.
'cttttgtttggtgactaagtcaaatttccaagacaaggtgactggggtgtcccttgccctggtaggtccttcctccc'.
'cataggcaaacacttcctctcaaggtttcttgtttatgtgatgtaagcaaacccttttctgatagcatagataggca'.
'agcatcctatgaggtttctcccgatagtggaccccacgggccatgccctatggctgcgtgtccagtaacaactcctt'.
'ccttctgcacagaacccaggcagaggaactctgtgtcctcccagggcccaggcactggtgaagatggggggtctgca'.
'aatgcaggagcttggggatgtccagaactgaccccaaggggcaggcttgttgatgggaggtctgccccacctcagcc'.
'ctgcagggtcaccctggtcaggccaatattgtctccagggaccataccagcaacccctctccttgggtgcctctccc'.
'tcataggcctgagttcctggcactgggtgttgagggccccattgtttccactcacccagctagcatttattgagcac'.
'ctactgtgtgccacatgctgttctaagggatggatactcctgagatggatacaggagttgatgagagaaaggtccct'.
'gtcctcacggggcccatgttctgaaggtggcacccaagtcttgtacagtcctttcctgcaggagtcacgctgggcag'.
'aaagtggaaacctggccccaggggctaggcacaggcgtggtgccgtggcctagtgaggagcacccatcctggtttgg'.
'ggcaggttctctgggcacctctgaccctcacctcccccaccccccggtctgtttgcaggaatgtggcctgctgcgga'.
'aggggacagtgctactggctgacaacgtgatctgcccaggtgcgccagacttcctagcacacgtgcgcgggagcagc'.
'tgctttgagtgcacacactaccaatcgttcctggaatacagggaggtggtggacggcctggagaaggccatctacaa'.
'gggcccaggcagcgaagcagggccctgactgccccccccggcccccctctcgggctctctcacccagcctggtactg'.
'aaggtgccagacgtgctcctgctgaccttctgcggctccgggctgtgtcctaaatgcaaagcacacctcggccgagg'.
'cctgcgccctgacatgctaacctctctgaactgcaacactggattgttcttttttaagactcaatcatgacttcttt'.
'actaacactggctagctatattatcttatatactaatatcatgttttaaaaatataaaatagaaattaagaatctaa'.
'atatttagatataactcgacttagtacatccttctcaactgccattcccctgctgcccttgacttgggcaccaaaca'.
'ttcaaagctccccttgacggacgctaacgctaagggcggggcccctagctggctgggttctgggtggcacgcctggc'.
'ccactggcctcccagccacagtggtgcagaggtcagccctcctgcagctaggccaggggcacctgttagccccatgg'.
'ggacgactgccagcctgggaaacgaagaggagtcagccagcattcacacctttctgaccaagcaggcgctggggaca'.
'ggtggaccccgcagcagcaccagcccctctgggccccatgtggcacagagtggaagcatctccttccctactcccca'.
'ctgggccttgcttacagaagaggcaatggctcagaccagctcccgcatccctgtagttgcctccctggcccatgagt'.
'gaggatgcagtgctggtttctgtccacctacacctagagctgtccccatctcctccaaggggtcagactgctagcca'.
'cctcagaggctccaagggcccagttcccaggcccaggacaggaatcaaccctgtgctagctgagttcacctgcaccg'.
'agaccagcccctagccaagattctactcctgggctcaaggcctggctagcccccagccagcccactcctatggatag'.
'acagaccagtgagcccaagtggacaagtttggggccacccagggaccagaaacagagcctctgcaggacacagcaga'.
'tgggcacctgggaccacctccacccagggccctgccccagacgcgcagaggcccgacacaagggagaagccagccac'.
'ttgtgccagacctgagtggcagaaagcaaaaagttcctttgctgctttaatttttaaattttcttacaaaaatttag'.
'gtgtttaccaatagtcttattttggcttatttttaatgctttttctcagtgtttttcttctgtttctgagtcacgaa'.
'cagcaggcactgaaagcagtcccccagccactgccgaaggtcagtcccggaggtgctgcccaggctccaggcagatg'.
'cggcagccccggccacagccagcatgggctggagaaaggctctctactgcacaggggcctcacgtgactgcagggct'.
'ctggggaggtggggcacctgtagcctgacccccaccttgctgcttccaaagcttccttgcccagggctgagccttgt'.
'ggggcaccccccacactgtggtctgcctgcctgcagggtgcccagggagaccctccgcctttagaagtccaagttct'.
'ttcccagccccctccctgcctagctgcctgcccctggcgccagacctggcccgcaccactggggcactgtgttccca'.
'ggggcaccctcctatcccaccagccccaaagcccagccaggcacccttccctgccacctccctgggccctgccccag'.
'cagcccagtcggcctcctcgggccttctgtcactcgctcacacacagcaccatgtcagtaaacagctaactcaggcc'.
'tagggagttaggtaggatggggggagtggggtgggggggcaggagggtgtccccaaagtcaggcttggctggggcga'.
'ggcgctgccaacccctgccgccagggggctccaagctccacggcacgatctgctcagggtggcccttcttccacgat'.
'ccaagccctaagaacaagaggctgggcctgggccctgcagagggaaaggggatggtggacgctgcagccactgagtg'.
'gcacaggaccacgtgtaacctcagggcagggcagccaactccacaggctacatggatggagatgtggatagaagcat'.
'ctgccctgggtggtgtgggctgaccccaagggtcttggcaccagggctgatcctgacttgctggtccccgaagggcg'.
'ttggagggtatggtgcccatccctactctggtcccatttcctcaggcccctgatcccacagtgcctgggacagggct'.
'gtgggcccagggagcaccctccctctctgacctctgcctggtctttccgggaatgggccactgggctgctggactgg'.
'aggccaaagtcctgcggggaacgtgcgggaagagcagagcgtgcaggcagcagagactaacaagaagccctggccca'.
'gagggcaggaacaggtggacgaacaaccagatgagagaacgtaccaggcatgcaagctagacccaggaatcaacggg'.
'ctgaggcttagcgtcccctacggcgtccaccagcctgaccgcgggcctgctgggcccggggggaggggccttcctgc'.
'tggggtcgagctgcagcgcacgggtgggcattagaggcacaatagagcaggttagttagagctcctggggggacagg'.
'gcaggggcagggccgaggctggcgatgtaagggttggcctgccaggacagcacaggtagcaccaagggcgcagggag'.
'ccggaaacgtgtggctcacacgggcccagggcgggcacgtgcacacacacaggcctgcacaggaagccaggggattg'.
'gcacacagcaggcagcaggtcctgccatcgctggtggaccctggtgggctctcacacgcacatgcacagaagggtgc'.
'acacacactagctcacaggctctggcccatgcagggtgtggccgggcagtgttgtccccagtgggtgggagctgcaa'.
'acttgtcagtacccacagactgactggcgtgaaggggctgcttcctgggcttggccccacaacccagctgtacccca'.
'gggcccagaccagacccagcatggcctaggctgctctccagcaacccctagacacagggcctcaccggggacctgcc'.
'cacagccacatgaccacttactttcaagggttccttctcagaggcctctcctgcagagctggcgccccgtggcctcc'.
'gctccctctggtccaccgtggagtatccgtctgtagatggggtaaggtggggcatgaggggcgctctgagggaggcc'.
'ctgtaggagcagatctccctctcagcccagacacaggggactcgtgggacaggggctttgggagacagcccccaccc'.
'accctgtcctggagatccaggctggtgccagctctcaccaacaccctgccaactctccagactcccctccacttgtg'.
'ggtcagagcccctggctgagcactaatccctctctagctgccctgtacctcaccctctaagcacccctaaaccaaat'.
'atctctcctccacccagcaccatctacaccccataaaaccagcaggcccacttcaggccttggtcccctcccggcac'.
'agaaaaccaaccacactgcatctgcactcacctgggcccagcgcatccatggggatcacatcccggctgccagtttt'.
'ctcgccctctgcaaggcaggaggaggaggcgggctgcatgtggcagccaggggggatcggggcagagaagcccacac'.
'agggctggcccaggtagccctagaggctctctgtcactaaggtgcccaacctctgccagctggcagcctcaccccag'.
'cttgacaacagcgcggatgctgtgggaagggagtagccaagaggcagagggcagggaaagtggcctatggaagccgt'.
'ctcagtgggaggcctgactcctccttcaccctcacccaagggtcaggcaactggggcagctggggtcgccaccctct'.
'aggctccctaagctccaccactcaccaaggctcttgtccaccagtggcagcgtgctgtcatcgaagcccccaggact'.
'cagtgctcccttaggccccttggcagtagcagcagctgactgagacataaaacacagacacagggtgggtgaagcac'.
'atggagtgggaataaggcaaagtgagcagggaatggaaggaaggccagggaagccgcacctggaagcgcgccttggt'.
'ccaaccatctttctgcaaggtaccacgcagctccttgtagctccacactgtctgcagcacgtgtgacgccgccttcg'.
'cttcgcgtaccgattggctgtggggccgggggcggggtcagtggtggcccctcccccacctccgcggctccccaagc'.
'caccgaccccgcccctccacacctggaggccacgagagccaccaacgctggcaccccgcgtgcctgcaggagcgagc'.
'gcgcgttatccaggctgtcggacacgatttcgtggatggtgttgagcaccgccaccacggtgtcttcctccaggcag'.
'gcccccggtcgcggcggagcctgtgcattgcgcacattccgcacaagctcagccatggcgtagctccctgaggggca'.
'ggactaggtgtcagaacacacctctgccccacctctccaggaaggagcagggatcccgcgagggcgaggggcactgc'.
'caggagagcccctggagaccgcctgtgtgcaggcggtcacaggagcccctgtgagcagggcgctgagcttcagagac'.
'agggccggggggactggagctacctccagttgggacagcgcccaagcgagagggccggggcctggactcccaaacca'.
'ctcatcctccaagcccctccgatgggaccccaaagctgcaggcacagttcggtgcccaggcgtgggctttgcaggcg'.
'tcctcaccgatgaggtctttgttgcgccggtccagcgagaggttgcgcagagcgatggcgacggcgcgcaccacctt'.
'gtcggtctcagactgcagcagttccacaagcaccggcagcccgcgctctttgcgcactgtggcgcggatgtacgtgg'.
'cccactgcggaggcggggagagggttgctcagacatacatgccaggcactctcccacctccagacgctgaccgctct'.
'ctccagctggaccttcctgctcccgtgcccgacaaagccctaccccaaaagctcaacggcacctccaccgaggtttt'.
'cccaccgtccagggtgcacgcattgcccgcagcccatacacctcttggatcctggggtggtggtgtggcccctcctt'.
'tccccgccagccgaggcaggagctgcaccagtgaggtgcctgggattccctctctcaggacttgcccaccctgcccg'.
'acctggtccctcaccatccagttgccggcactgaggttctgcagagcgccggcggcagcctccagggtgttgaagtt'.
'ccggctctccgtgaggagggagaggtagagacgtaccacctcgggctggtacagcagctcaaagcctaggtgcaggg'.
'caaccgccacccacggtcacccagaatctgctctcatccatcatacccctcccgcttcccgcttcagagctcccagg'.
'gcgtgggtgagctggggccagggatgggtgtggatgagtcacgtaatatttactatcaacatatagtcacccaaggg'.
'gaaaagcgttcccatttcacagaggagcaaactgaggctcaaatcagttggacctgcctggcagcaggagcatccag'.
'gaggcctggggtggggagggaggtgtcaaccaggaacgctctcctagcaacaagacccgcatttcccggtaggtccc'.
'tgaagctatgcatcctggccacgcccctggtaatagggcccaccctccctggcaacaagaccagcattggccagtaa'.
'ctgagagttgtataaccaaggccacacccctagcaagaggacctgctttcaccagtaactgaagctgtgcagagagc'.
'tacgccccctagcaacagggcccaccctcccccactgacaatagagcccaccctctgtaagtcaactgatgcagtgc'.
'aaccagggcagctgccctagcaacaggaggcactcttcctggcaaccactccaagttcccgggcaattgaggcgccg'.
'tcctgctgctctgcccagtgctccagaaatgaggggtcaaaacagccttccaagcttgcctgtctccaaactggggc'.
'ttcagcctggcttgggtactacctcgatctcccctgtacccacccagtgacatttcatcacaccctcgccagtcctc'.
'atgccccatgctccctctactcctgccctgctgggctttctgctccaacacactccaagcacactccccgctggggt'.
'atctgcatcagccctgctctgcctgtaatactcccccacagccctcctgcggctggagccctccaccctggtgacat'.
'gcaggctcttccaactggctaggccccaccaggacagacctctctctcaagccagatcccagcatacagctcaatag'.
'gcactgccctgcccctgcaggtgttcgtctggcccagcctctgaacctggatgtgagcatgcccgcctggctcccag'.
'ccccctcagataactcagctttgtggctaacacaggaggccctgcctccactggaggcgtccctccaaaccttccca'.
'cctcttacgcaccgtgaggccgagcaagccctctgcctctctgtgcctgtctcccccaaccttgcctgacatgaccc'.
'atggcacttcctcccattctaaaccctcagcaggtgtcctggtgctgaatcaccctccaggaaatcctgcacctagg'.
'ggcctgtttccccatctgttccctgaggccctccaggcctgcttgatggctcaaagcttcactaccagggcaatcct'.
'gagcccagacatcccccagtggagctggcttcatctcagcccactcacctttggcggcctcagttcgcttgggcagg'.
'tctagcgtgtcaaagttccggtccatctcaccatccttctttcctggaagggaaaggtggtgggaggtgaggcagac'.
'cccatatggggaatgggtgtatcaggagagttgggcacagttctctcctacccaggccccaaaaggcacccccatgt'.
'ccaggcctgggcacctgtgggagtggagcaccgttgtcagagtttgggcagacagtttagcctaggggtaggagttg'.
'gtggcagtggggcctggggatgtcccagccctgcccctaggactcatctcccaccaggtgctgggagctgtaccaca'.
'gaccctcccggtggctcccttgcaactgccaggtatgtagactgagggaagccaggagccctggctggatggtaggt'.
'ggatacaagccaagaaactgaaggctgaccaggacaagactcatttgggtcacacagtaaggcagaactagggggaa'.
'actcccccagctggggtcaggacattgtcccaggatctactagccaggagaaaccccacagcagcccacctaacatt'.
'tgtgtagccctggcttgcacacgtctgtgacagtgagcccactgtcaaccactctccccatgtcagatgatgcttct'.
'accccttcagaaggcagcagagtggagccagatgacctggggtccctgccctgctcaccctcatgggacccttgtat'.
'ccctccgagccacatgatgccccattctatcagagaaacagactgctccttggtgcccctagagataagtacccccg'.
'ggccctgcccactcttggctctgcccaactctgcccaggtaggcaagtctgaggttacagaatgagccccgtggcct'.
'tcccacctgccactgtcataaagatggcagcccgagtgatgaagccaggggtggggcagggccctggggctggaacg'.
'tgctcgcctcttcccaggtacccactgcacacgccaggcctggagagcaggataaaaagggactcaccttggtggaa'.
'ccactcctctgggaggccggaggaagcagaggagagaggagaggagcctgaacaggcagcactcatcacccccccat'.
'gccctcccggaagcctcaggttcccactgcacaccctggatcaagcaggcagcatgtggaacctcatcccatcactt'.
'ctgggcactgagcacccaccagggggacaagaagagggaggcctggggtcagtggggcaggggcaggtggcgtacag'.
'gtcccccacagctgctggggaggtcctgggaacctacaccctgctagtgcagtagagaaggtgtgcagggcatcttg'.
'cccaggcagatgggggctgccccacaggttggtggcagtctacagctattctgtgaacagtgagcaggcagcagcca'.
'tggctccttcccaactcatgggcaagtggaactctccccggagtagaaagactgggtctgggcattggttggtttcc'.
'cttgtgtactccctgggggtcccacagtgtagatggggaaggttggacctgggtcccatcaaccatgtgacccaggg'.
'cagtccagcctccttgactcctggcttccctgcctgcctgttgggggctgaccaggtgtcctctagcctccatgatg'.
'ggctgctgtgggtgtacagagagccttccgctggggcaggagttgagatggtagagatgataccccagtccgcccca'.
'cccacctttggccttcttgcctccaaagcagctggcatcatcccgcctccggcgctgggagcctacagcactgccca'.
'ggggcccgggctcggcctcctggtacctgtcggccccgggcacctccttgtgcacgtggtaggacaggttccgcatg'.
'atgcacacgcagttctccaccgactgcagggagaggtgagtgggtggggcagggcaccctaggcacagggctggccc'.
'tcaggaaagactggccacagctggtgtgcatgagggcaccgggagcaaaggaacagggagtcctcagtggaggggag'.
'caaaagggcggtaaccgccaggaagggtccatgggaggaagcctctgccctcacggcacaccttctgcctgcaggac'.
'ggtgcccacttcagtgtggtcactgcgaggcgggccacacccagaacgccaccccagacccacaagcccattcccct'.
'gtgctgctcccacagttccagcctcctgggacctgcatgatcgtctctccagcccttggtatgaggctgtgaccgtc'.
'cctgcccaccttgttgtcagtgtccttccggcccacagccgactgcagggcatgcaggagcgcgtccaccagccctt'.
'cacactcccggagtcgccgccgggcctcagcaccatcggagctcacattcctgtgtggccaagagcaggccaggtga'.
'cccctggctaccagaaactccctggctccaccctggccttgtgggcttgtcttcatctgcaaaataggccctgctgc'.
'tgccctcctagcactaatgggaaaggaccccacagtctggagctcagtgaagggggagaagctaactgcccccaggc'.
'ctcaggaggggagccctggcagacaactatcttggctggggatagctgggcagggaaagacagggtttccctgcctc'.
'ccagctgacctggaaagggacaggtgcactctcagagagacctgaacctgtgcaagggcaattctgggtccctcgcc'.
'accccaatggcagctctgggccccaccttaccccaaggtcaagagcctgcagggctgcgcgggaacaccctgatgga'.
'caagcaggactgtggggacccaggactctgtggggtcagcagggcctcccaggggtaggaggggaagggcagaggtc'.
'acaggtggctgggatgagcctcccaggcagatgaacaggaaggtcccagctccccctctggctgtcaagtgatggga'.
'aggtaggtgagagctgggcagggctacggtaccacagagacccctccagagggtgcccctgggaagactgggacacc'.
'acttgggggtgaggacagctccatcaggccccacttctcatccacaggacttgtgccacagctctgaagctcctaag'.
'ctctggcgctcctaagctcgccgccatcttccacactatctgggaccacgaggacggggcctggtgtgcatgtgggc'.
'tttagcaccaggtctggtccacacctcaggcagcccgacgtgttcttgaagacagttgtccactcggcgtcccgtgg'.
'cttggagtcctcgttgggctcacgctcccatcctgagtggggcacgatcacctcgtgggtcagcgtctgcaggccat'.
'ggtcaatgatgaccatcttcaggggctcataggatgacaggttccacagggtgcctgtggggtgcgattggccaatc'.
'tgtgctgaccatatgcaccgcctgcctacctccccaggtggccacgctcaggacctgtcccactctcctcatgtccc'.
'agctcatgcagaacagtaggaagtaacaaaagccgtgagtggttccgggggacacccagtactggtttccagctagg'.
'aaggagccccaaaggggaggaggtgcagaggagggtgtggcagtgctgtcccgtcccacccattccctgccatgtgg'.
'caggtggcactaacactcctgaggccacagggcctcacagagacacggtgaccctacctgtccctcagctctcacaa'.
'ggcacaagccccaccactgcacggttggggtgggaaccaaggaggtgggtcccaggagagtttctgtgggggcagga'.
'ggtgtgaaggcaggaggtgaggggacatgcccgaggggcgcagcgtcagcctccctactatggtagagactggggaa'.
'cctgtcacagtgtctgggcctgatgcctggctcctggggcaagcgtctcagcagctgcactcctgcctaccgggtgc'.
'tttcccaggcggtcgcaggccgagtggcctcgttcctcccgggttgagcctcacactcttctcttcccaggggatgt'.
'gagcatggccaggtcccactcaccagtgacaagctcacggacctcgttgtcccgggcagccctcagcaggcgcacca'.
'gggcaggcacaccaccgcagtcccggatggcggccttgttgtcagtgtcgcggccataggagaggttgcgcagtgcc'.
'ccacaggcccggcgccgcacctcagcccgcgggtggtccagcagtgccacaagcagcggcagcccccgcaactgccg'.
'tacacgccgcttgacaccctcgttctcaaagcacagatgctgcaggtaggcggccgcattggccttcacggggtcca'.
'cggggtgccgcagcatggccagcacctcaggcagctcagggtcccgccagcgcggctccttgcgggcgctatccact'.
'gagggcgagcgccgcaccagccggtccaggctgcccatgctgccccgttcaggctgggccaggggcgccgtcaccat'.
'tgggaacgcaggccgctcgtccgccagctcgccgccatcatctgctgtgtcctcgtaggccctgcacaggcaagtgg'.
'ggcgcgtggacatcgtcacagcagccgccagccctgcctctgagctgccccatcacaccttcttcaggactgcaaac'.
'tcacccagcagcgctgggctgagagcacctgtatcttggcccggagcatggtggggacacagagagtcatgcaccag'.
'cccagtgagaaccaattcagagccaaatgccaaaccccagccagcggctaccaggacccaggcaaccctcccaggac'.
'agcaaactcactcactgctgtcaccgggcagtttcccaatcccgagcaaaacaagtttctgtgagacatctgctatg'.
'gctgctggagagaccgtctcacctcccttccacaaaaccaccccatcttccatgaggcccatctctggctgtgccag'.
'gatgtagggggagtaaatggccctctccgcatgaagccatcccagtaggaccacctgaggagtattcaggccaccag'.
'ccccttggggcacaagatctccttagctctcagtagccctgtgggttgctgtcatcaaaccgcctgccctgaggcta'.
'ggagtgacggtcaggtgacttggccagggtcacacaacaaaatcctgacccgggctgtggtcacatccccactccag'.
'agatgcagaaactgagggcaatggggacagaaccaggggctgtgacaagggccagggctctgggttctggttaccca'.
'gagtgtggctggagcaaggccagtggccggcactcttcccagctttcctgggccctgggcctgcaggacagtgccca'.
'gccgaactcctaccaccccagggtccacctttcttctgtccctgacgagagccaaggccaattcaaactaacatgca'.
'tgactaactcaactgcgccacttgacaagtggggcactctgtagttggggggtggagggcagacttcccagaggagg'.
'tagccacaggggacggggtgcagctcacctggtatgaaggccccgcccacactcaggcctcctccttgtggccgtgc'.
'catagtcaggctccagctcagggccaccctcgtcatcagcggccaggctgcgcgtgtcatcctccaagccatacggc'.
'tctgcctggaagcgctcgggcagggagcggccacctggtggcccaggctcaggacccaccgggaaggcttcccggtg'.
'gccaggcagtgtgaagcagccatcaccagggcctgggccaagggggccagcacgtgggggccgcatgcccagccctc'.
'gggacaggctgccatagctggggctgtcccggggctcggggccttcgggaaagccacccccgctgctgaggtaggct'.
'cgagagagtgtggccactgggccaccaccacgcagcaggaaatgccggtccagggcaccatctgcaaaagggcctag'.
'tggggggccgccatccagcagggggagtccatctgggcccacgggcacctggcgtactgtccgagtggtcaccgtct'.
'tgacagtcttggtgacctggtggatggataggcaggtaggtggggtagcacgagaggcctagaaactgctttgctgg'.
'ggtctggctggccttaatttcccactcgagcaatgagaggccccacgtggcaagcttccatgtccactctgcaggtg'.
'ggacagctgcagcagcctggccctgctcacccacccactgcctgggcctggccataccttggtctcggtgcgccggg'.
'ttgtgccatcttcggatgtgacaatagacacatgggaagtgggtgtgccggggtcctcctccaccgtcacggtctcc'.
'tccagcacatcaggtgcctccggcatcgtggccagtgaggcctggctgcctgggctctgctcctggggcaaggaggg'.
'acattggtgggcaggcctgctgctcagtcacccctggagtgcaggtctccacacacagcagctctgcctcagctcat'.
'gctggccagcacaccagggtgccttcctcctggtcctgaacccacccaccccaaggcctgtttcggcccaagctgac'.
'aaggacagcaataagttcttgccctctgaacatcgaggtgctaaccctgccccggcaccccatcctggggggaccct'.
'ggggctggacccccatctcaggtctcctcaggctgagttggcagataaggacatagaccctggggggtgaagtcttc'.
'agggccctccccaagctgcatggccttgctgccacaggctcctccaggccccaggaggtgccagtgagacctgcagg'.
'atgccttcctgatgtcaaccaccacccctagctgggacatcatggtgtcctggggcctcctccctcacctgccccag'.
'acaccttgagtatagaagccttgtgggggctgtttcagcactgcctactgactcctgtggccacactaaggttcccg'.
'ccaccaacgccagccagacgccctcaagggacagaaatacgcagttcccagaacaccccatgcacctgcagcaccag'.
'tatgtccttattccttccagcccagacattcttgagtgttgtgtaggcacaggtttgccctacctcgggccagtggc'.
'tggcgcccccagtgactgagactctgggcatcatatcagagaccagacacagtagatttgagcctatgggtgccctt'.
'gccaccattctgcatggggtgacgacactggaattctaggcaagacaactctggactgagacttttctatccacatg'.
'cctactgactggacttgccagtgggaaaactgaggctcaaagaggataggctggcccacatcagagccaggcccaac'.
'ccctgccgcgctgagtggcttgaggacctaagactcacagcctgccccgggcctctgactgcacaggtgcctggccc'.
'cagggccacatggcaccaacatccggggatcggcatctagccaggatgggcaggagctgaaacccaagccctggtgg'.
'gtgggtcaggcggagcacattcccaggcagccagggcagggtcagcaggaggacaggtcctgctttgtggcccaggc'.
'ccctggtccctgcacaatgggtcccttgcctgggccccctggggcctgcacagacactaagctctgccaggctccag'.
'aggcagactctgcccattcttgggcctgggaggtgagccaggttagatgctcagcgctgccctcaggacctgcctgc'.
'caaggctcgtgggctgggaagcctccccaggtcagggtcctatcctgggggaatacttgacccccaaatgcatgcag'.
'tgcaggtgtccaggaaggggcctgcaccaacatgttaggacaggtgtatccctcaggctgacagaggaaagaagtgg'.
'ccacagaaggcacctccccctctcccacaggcagggtcttggaggatgacagataactttatagatggggaaactga'.
'ggcctggcagggggaagaggatttacctagaacttcacagtccaagtgggatttcaagcacccccagagaaggcaat'.
'ctggcaaggaaggctttgggcctcatctcgccctcagtcttgagatgtaggtggaatgcctgctgtggacctggcta'.
'ggaaaaggggacctgttccctgggaaaaagaaatagactgaggcctagagtggggacaactggcacgctgccaggca'.
'gggcaggctgggctcttctccaaaggcactggggagctgggactgctctgaagcaggagaaggcttgtgtggcccat'.
'cactgctggggctgggctgccccatctgtatctggcaaatgtgtgtcaggccctgagctctctctgctgggccctgg'.
'gcggggctcatctgagttcaagcaggggcccaggcactgaggggctgcagttctggcgacagagtgaggagggtata'.
'aagcaagactgaggaaacgttacccaggactctgccagtgggatgtagcccctcatatatgtatatatttacatcta'.
'ttaaaaactcagagaaaaaccccctcttccctagctaggcagtgggggtaagcgggagaggaaaaggggaggacatc'.
'tcaggaccccgatgccactctgtggcccagcttatccctcccaccaaggctgtggtgagggtctgacaggcagagct'.
'ggggtggtccaggagagccacgcccccgcagcaagacctggcaaccctgcggcaccacccatcagccccggcctagc'.
'agccccgcagtaggatccagaggccccaagagtccctgctggcaaatgacctcagggagctaaaaacgagggatgac'.
'ttcacccgggtggcaggtgcatgagtcagccagtgatcacaggaaagcccggcccctgctacacatgcccaggcaca'.
'cacacatgcatatacatgacccctcagacagggacacatgcatgtacatacacgtgtgcaagtacccagcccggcac'.
'aggccgagcacatcaacccgtgtgctctaacagcaccccaagggcacggcgcccactgttcccagaggcacactcgt'.
'gagcacacatcctcccgtcctccaccgtgtatcggagacccttatccatgcagggcctcacagagtctcaacacaca'.
'gggacaggggccaccaactctgccaatcatctgcccagcatccactctgggagtctcagagctggctggcagatgga'.
'gaaactgaggtgtagagtagtgagaggcccatagccagctggtggctcagctctctgcaacatctttagggtggggc'.
'tgtggaatggtgggctgactctcaacaggagttggctgcagtccctggatccctgtctggccccagtgtccatgtct'.
'gacgtgcacctgcccaggctggcccactctcagggaccctggccctgcagccccacacagcctctgcctcagaccca'.
'actctgggctgctcccctctgtaccctagacatgggctctaccctgaacaccccacctccagcccaatcccacatgc'.
'tgcatcctgtcagtcgtctctcatcaccccctccccagctggggccccatccttgctcctcttgcaccccgcccggc'.
'ctcccagcactcatccctcccttggctcttcaatctctggtgcaccaggtctggggcccccaggactggcccagaaa'.
'caggctgctgcccaggcctggggtttcccatgagctcccttgggcttgtgggaggggccagagtgaccagggaggta'.
'gaccacctacccctgctcacaagagggtcccgggaacacagggctgagcccagcataggggctctgggccccatcac'.
'gcaccttcggctcagcttcttcacaaggaggtgagaaggacagagggggctggggtcgtgggacgtgctgggtagca'.
'tcagtctcacttttgtggcaaaatgcaaggaacacagggagcagaaaagcaagattggaccaacacacagagggatg'.
'ctggggcacaggtggctgggccctggtcccatattacttatctacccaaaccaccggacttcacagatgcaccacgg'.
'tctgtgtcctgaagaacagactgcaggggcaggcccctcccctgtccaaggcctggctagcacacacagagaatgag'.
'ttaaggtgagattgcacacctggatcccacacctgcaggccaggctcccagagggcaggaggtggctgctgtccgat'.
'ggatgaatgaatgaatcttctccatccccattatggccctcccaggtagagtccaggacaagccaggctggcatctc'.
'tcaccaggcagcaagcccttggccaccacaaaatgccctttcccttggtgccacagcctctgaccagtctccaagac'.
'ctggagcttacttctccacacagcagtgcacctgccagggcgtggccccaggcagagatgccaaaaagccaagctgg'.
'gggagcaaacttggggtgggagagcagggctgactgtcatccacctcagcttccccaagctcagcttggggtcatca'.
'gacacactgtgaccatggatttcccaaaaactggtccctccacctctgagggccagaccctgggggccacaccaggg'.
'ccgtaggacaggcaggggcctagttgcccaggtagcaggtgtgtgggagacctgcctcccaccacagagggtcttgg'.
'ctggtctctcctctgctcagtttccctgcctgttactgaacccagcactgctctgagcagaggacaaactgcctatg'.
'cctccccccacctcaatgctgagagggggaggatcccgttttccttagagatctcctccagcatccattagtgggca'.
'gggcctgtctctatccctcccatcacgtgcgcctcggaggcagagaagacttccattaaagctccggaagctccttt'.
'gcaggtcccgggagtcagagccggcgtatggggtgtggaggggagaggaggaaccctctcagggagcagaaggccta'.
'cccgggcttccctcttcagacttcagcctccttcctgcacagacagaagccgctcaggaaggccctggctctccacc'.
'cgtgtccccaggcacctgtcctgggcgctggccaagaagcgtccatccggtccgggccggtgccaagaggagggtca'.
'aactgccaggggtcccgacccccccaggccccgcggatgggctccagagaccctgcggcccgccctgcatacccggg'.
'ggcaccgcgctcacaccgccacccgcccggccctggccccagcctgacgcagcccagccaggggcgcaagacaatag'.
'ctgcctcgggccagcggctccgcggaacaaaagcgggtcctcccgggcaggccgacgccccgccctctgcctccgac'.
'cccgggccagggtccccccaagccaacttccctccaacctgtctgagttcggccggcatcgggccgggactcggggg'.
'gcgctggccagcagcgggggaggcggtggctggaccaggctcggctccggcgcctcggccgctcgggctcaggctcg'.
'gcggactcgctccccgcgggggcggatctggcggcggtcacggcgagcagccaatcgggcggggccgcgcccaggtg'.
'gggcgtggcgggggccggggtgggcgtggcgggcggggggcgggcaatgtgaggtcccgccccccagagacaggggg'.
'cggggccctgcagccccgggtcgccccctgtccccccacttcccaccacctccccccacccactgccggcctggact'.
'tctgctccctccccctccctgcggcaggggtgtcactttcccgccgaaagactttggccaagtccttcccaggcctc'.
'ggtttggcctcggtttatgaccacacttcagtccgcctgcaaagggggaaacagttccggcagggcaggtgcccgtg'.
'ctgcgatgcacagagcacaaggcctccctcactggcacaaacctggctgcgactcagtttcacctgccatgaaatgg'.
'gggccgatgagacagtagtcacggctctgtgagatctctccagtctcccagatcccccctcaccctcctgcccagcc'.
'gccactctgaatgggcctgcgaagaactgtccccacagagttcgatggggacctggaaaagggccctgcaggggacc'.
'cccactttgtatcttgggttctccccatcgaggcacagaagccccgaatgcacccccactgctcccccaggccagcc'.
'tcaatgtgggccacaccctagggaatctagttctgctgcagtgaaaaatgggaggggaagggccaggctggagccac'.
'cttcttatgtcaaaccccacaaaggccaagccaatggctccagcatcacgaacagggaaacaggttctgagattaaa'.
'tgagctgagaccaacccagggagactcagtgggtctggcaagagaaagggctcgggcccaggcctcccactggcttc'.
'tccgcagacccctcagaaaacagcctccgcagggaccactccctgctgccctgagcgccatatacagaggccactcg'.
'gctagcatgctcaagattctaggtacccaccatgtgcccctctgagcctcagttcccccacctgcagaggggtgagc'.
'taccctaccactggctggacccctgtatcttgcatctagggccaacctgcctggaacccctggagcagagcgcagaa'.
'gaccagacactgcgccaaaaacgcgcccgcatcttatctttaagctggctccatcttctcaactgcaccagcagcta'.
'gtgccccagccacctatccacctaagacgagcccaaggcaagttccctgatggcacccctccccactgggtgggcgt'.
'cagccctgtttcagctggctgtctagaggaggggccccttcctgctggaagatgaagggcaggtagccaggaccctg'.
'gagcagcccagtgagtgcagcagcactccccctagcctggttccccagcctcagcccccagctacctgccttgccat'.
'tgccctggcttcccaaagcccgggctctgaccctgtggctcagcaggtagatcgctaggcacttcctactgaaacca'.
'atctgggaaacctggccagcccaaggaggccctgcctcccctagtatcctcatcagcccagccagttgagctgcagc'.
'cctggcaacacatgctctcttcaatcccagcctgagaaaatcaagggtagggggtcggggggagagttcaggggcag'.
'gggtggtaggtggaggggcagtagcctgaggtcttgaagtcttttgcctgaggaggtcagggtagctccaggctgtg'.
'ggaacatcttcccaccagggcatcaaccctccggggtgccttgggtcctcccacactgcctgtccgaggacagttcc'.
'ggtctgggagggttggactgagcacactggcgcctgagaggcggcctcggggtcactggcttccactgtccctatat'.
'ggcccagctgggcccagcgttctgcttccccgcctcaagtttgagggtagaggcctcacattttggagtatctcaag'.
'tctgagggctgtgagagtggccccagcaccgagacccaccagaggcctctgagcaccaggggccatgaaaaagggcc'.
'ccctagtgagtctcggaccctctggggacattaatttgactctgaccatgcactggtgctgggctgggccttctatg'.
'tgggtctcatgagcagacgtaggaagcatgacgcctgctggccgacaccaagtctggacaccaagactcaaggagta'.
'gtcaccaaccccaggtccctcggcctgacacaggctgctggttctgagccccacatgccccagccaggtgaggagag'.
'cccatggggctgcctcaacagagaccagcgtttgctccctttctctctagatgagaagggccaggctgccccaagct'.
'cctggcatgtgtgtgccaggcgcaggtccccagagtcagggcccagcaggaccaaagaagggcgggtggaggtgcag'.
'gtgctgggagtatgctggggggaggtctggctgctgggtttagcggggcagggagctgagccagggagacaggactc'.
'tgcagggagagccctctagggtcactctgtgaagaacccagaggccgcagcaggaggcaacccccccagcctctaag'.
'ctgggtggtgaggagagcccccttccccgtggctgctgggacagctccaccctgactccccactgtgctagccctca'.
'gtcagtaacaggaaccatgataatcacaccacatcccaagtctccctgcatgtacttgttccggcctcctaacccca'.
'agccaggggctcttgctgtttcatctacaggttagagcactggggtgctgggaatggggtgtcccagtggtctaact'.
'gctcactgcataccccaactttagagttcttagggcctggccatggaacacagaaggctctatacctcctgaggctg'.
'agtaggggccggagcccagtctgaggataatggccagcagagaaaatgaggctcccaggtcagcctctaagctgcag'.
'gcagagctctgggcctcctcctggggctgacccaccagtgcatgcaatgaacactgtggcagggttaggcatggtgc'.
'aggcaaacccctaaagtgtctctaggcagaccaaagagctgcccagaacagaccccatccagctgcctgggccctga'.
'gggctcagtggagggtgctgttctgagtgttgggctgtgtcctgcccactcttcacatggtgcctagtacacccaag'.
'tgggacttccagcccaacctgggatcccattttcctttcctccccaggagccccagcaaatcttgcaataagcgagc'.
'gcatgctggcttgtggtccaccaggacccactgattgttttcccacttggcaattttcacccttcccaagtcactag'.
'gctgttacctggaggaccagctgttgccaggccattggcaggggctgcccactgcccatgccaccactgaccatgcc'.
'aggctgctgggcacgctccagctgtagggcaacatggcgccgctcctgctccagtgcccgtgtcagcctctcgaagc'.
'gggcctcctgctccttcaccgaggccaggatgctggcggccgagtgcacattgcagtcctccatgaccagagcgccc'.
'gccagctgcaggcaaagcagagtaagctcagtggggtggggcacagcctggcaaggccatcatgggcccctgcccgc'.
'cccactcacagaccatacaactcactcccagaccagagcatccagccctctagagggaagcacactgattaaattct'.
'aaattaaaagccattaatccgaggctggccggaagcagccggctcactccccatgggttttgggactctaacccggc'.
'tcctctgcttcctgctagacctagcagaaacatgggccgtgggcggcttggagcccgctgggaagggcaggaagagc'.
'tcattagagcttcttacctcccaggccctctgccactcataccacatgccagcccaccctccatttcacagggccac'.
'cccactcccatctcacagaggcagatgccagggccaagaaagggtgggggaccatttgtagccacacagctggtgtg'.
'gcatggccagtgtggccagcaagcagggagtgagaagctgctccactgatgggtgcccaagaccccgaggcaggcgc'.
'aggtgaccatagcctgagagctcctggcaacactggtctgcagaccagcagtccagcctccactcatatccacattg'.
'gccagaaacaagagtggtgctgctacacatgacagagtaaaaactgaggacaagcctggttgaggttctggctggga'.
'ctgcatgaagttaagagaccataagcctgaagtggctggtgtgtgtgatgcctcatccagaaaagggcaggggccag'.
'gcatctgaggccaagcacagggtgggattgggcctgctgggcccagcccagtgttgcccctcagggccccagagccc'.
'caggggagcaggcgggggccatgagggcttggcagccgcagagacaaaccagcactttccctcccagcttgccccct'.
'ggctgcccagaatgtttgtttttcatgggtaaaaagaagcaggacaagtatgcggagctccaatccaggctcaccac'.
'agtgggcagggcatagccacgaggccacactgcccggagcacagtgagcatggccgggtgcccagggctgctcaggc'.
'atcctcctgcccagtcccgccagcccactgaggccaactccgctggatcccttgcccttgcaccaatatagggccct'.
'ccacggggaggacacgcactgcgggtgacatccccagagcgtcagcactgctgctcactggtctggatggagccagc'.
'tgcaaggacagagagcccccaagaggaaaagcagcgctgggctcagctgcgccagcaacacggtgcggggacatggg'.
'tgcacctcataggtgaagagacactgtggagcccagccccaccgacagctgggaaaacaggcccagcaagagcgaga'.
'gaccagtgcaggcccccaaagctgctctccatttccccagcacctgtcccacaaatgaaactgtcaacacaaccttt'.
'cggggaagccagcatgagtggaggagctgttttaagccagccacagaatggaagaatgcagggagagctgggggccg'.
'ccgcccgagactgaggtgcagactgggcgctccagcaaagggataaacagcactgcactccccaagcatggtcacac'.
'agctcttctctacacacctgatgctgtctacccacaggccccagacccaacacaggggagccttgtgcactaatgga'.
'ctgaacctagtgctaggcccgaggtgggaatggtagggtattccccctgggacggccagggcggatggcagggccca'.
'tatcactccagccctcagcccagtcctggctgcagcaccagcccatctcagccgaacctcagaagcaagggacagaa'.
'ggaaatgggacgctgccttggatggcaacaatcaggaccacaggatagccactggcctcatggacctggggtggctt'.
'acttccctccctgtgcagagacatggaccctcgtctacaccacataccccatcccccatctagcaggaccaggcttg'.
'ggctgcagaccctgcggacagcttccctgacctaagcccctccagcacaccctggctctggggactaaagatgccca'.
'ccctaaagggggcccactggctctggctgagggctcagtactccaaggccacagtgggaaggtgaccaaaccccacg'.
'atgaccttctcattgccgaacttggcttgattggtgcaaaacaatcatgtatctccctggagacatccagaaacact'.
'ggccagtgttgtggggagagtctggcagccatgctcaggagagcagagaccttggtgctgggcctgtgccatctgcc'.
'ccagccgcagggtgcaccctgcatttgccctggggggaagtgccctaggcccgcaggtcatggcctcggcatctcag'.
'gtgtctcaagagcaacccgggatatgctccaggcagagcacagaaggcccaggcccactcccctgacatggtggact'.
'ctggcctatgacaggagccagtctggatacaagggatcctggcccagaaccaaagagggctgcttttcagatggtaa'.
'ctcaaaatgctgtttttatattcaagtaataaatatatgatgtcaaggaaagcaaaatgtgcatggattcttaagat'.
'cgatggggcctgagtggatgctgggcagagtgggcaccggatttgcttttgctagagcccaggagggccctggggga'.
'aggctaggaagggggacactgcagggaccttggctgtccagccaatgccaccttggcctcccctaacctggtaaggg'.
'cccagcattgccttgtcgggtggacccctcatgaccccccacccaaaacacagcaaccagcttcatgcccaactctg'.
'aggaggccacttcttgccaaacatgctggccccagaagtttacttagccgcaaggcaggaatgacattgcacagccc'.
'acgagtgaccagacttcaggaccatgtggacaacaccatgttccaaccagaaaacatcaggaactgaaggggggctg'.
'gaaaggtcggggctaaactgaaactctgaaaaataaactgcaaaacaaaagtgacgacccagcccccacccagcccc'.
'agccacaatggacattggccacgtacccaagggaatccaggaccaggacgtgagcctccaggtgctctcacaggaca'.
'aactgctgggcaagcaggtggcccgaggagagaagcatggcaggagaagagggtggccccaggcacacagcccatgg'.
'aagactagagggagggcaagcaaaggagagacagcgaaggatggacagacagatggatacaggggtggatgggggat'.
'ggatgaatgaatggagggtggctggggcagtggtggaggatggacagagggacggacagattgatggacaggtcgga'.
'ggatcgtgggagatggacagagatgaatggatggatgggggatggtggggaatggacagatggatgaatgaatgggt'.
'cggggggatgctgaaggatgaacttatagatgaatgaatggatgggtgggtggagggatggtgggagatagacatac'.
'agatgaatggatggatgggtgggtggggggatggtggaggatgaacaaataaatgaatggatggatgggtgggtcgg'.
'gggatagtggaggaagaacatatagatgaatggatggatgggtgggtggggggatggtggaggatgaacatatagat'.
'gaatggatggatgggtgggtggggggatggtggaggatgaacaaacagatgaatggatggatgggtgggtgggggga'.
'tggtggaggatgaacatatggatgaatggatggatgggtgggtggggggatggtggaggatgaacatatggatgaat'.
'ggatggatgggtgggtgggggatggtggaggatgaacatatggatgaatggatggatgggtgggtaggtggggggga'.
'atgatgggagatggacatatagatgaatggatggatgggtgggtcgggggatggtgggagatgaagatatagatgaa'.
'tggatggatgggtgggtaggaggatggtaggcgatggacagagagaaaaacagacgcatagatgggatggtggggga'.
'tggatggatgaacgtatggatggatggggggggatggtggaggatggacagacggatggacagattggggaatgagg'.
'ggtatggacagacagacgggtgaatggatagggaggtggatgaagtcatagaagggtagacagctagatggatgatt'.
'ggatgggtttacagatgaatggatggatgagtaatagatttgtgggtgggtggctggagggatgggagaagaggagg'.
'ccagatagaagggggtgtaactgagtgagtgaacaagtgtgtggacaggagactaataggtggttatataagaaaat'.
'gaggggagatgagaggatgggtgaatggtggctagttggatgggaaggtggctggatggatacgggtggtggtagag'.
'ggataaaatgatgatggaagaatgtgtaggagggtgggcagatgggatgctgaaggctgggtggatggaggagtgga'.
'tgaaggagaaaacagagtgcgatgcatgaatggaagggggggtgggctgtgtaagggccggtgggcaggaaggaaat'.
'gctggaacctcactaagtggggaaagccccggcccgcaaaccctctggggcaaaccatggtcaacacacactgtcag'.
'gaacacgaaggcatggtgaggaacctgagggtagaagctaaatcctttccctgaaaccaaagctgacatttgacgac'.
'atcttgacaacccagacattcctcctcgggagtgcggccagagccttgtccggaaaatgaaattatggggcccgagt'.
'ccagtgtgggttgaggaattagaggaatttccgaagggtcaggccagtgaagggtggcaggcggggcctggctccca'.
'tcctgaccccttgccagctgtctaccagaacacagccagggctgcgctggcccccccctcgaggggagagacgggac'.
'ggatgaccatcgagcctcctcccataccccctttcccctccacccttccctacaaggaggaaatgatgccagaagtg'.
'ccctggcaggagttggacccaggcccagcacccaccttctgcctgggaggacatcctgggagctgccagcacagaga'.
'cttcctcgtccccctagctggccaggccttgtgggggccccatgtttaccctgttgcccctactgtggtcagatggt'.
'gcccaaagccttgtgggtagcttctggccaagcccactggccgggcactgtactcaagctgggacagggccagagcc'.
'gggggcctggggttcacagggcggagtccacatccatctgtgccaaggccaggaccacagtcccttgcagactgtgt'.
'tggatccggggtgcctgggctggggatgactgttctcagcctccaagcagcagaaagaacccccgaggaaagacgca'.
'caagcgtgactttgtgagaatgaaactttctgtatatccaaaaaaaaaaaaaagggccacacagtgtggtcatgttt'.
'tttaaagaactgacaccatttagagcaacacatgcagtgagcgttttgatgaaatgacgggtgctggcgttactcgc'.
'agaccatgactccagcatggtgaggctggtgtggggtgtgcaggacccatcacactaggctctccacttctgtgctt'.
'ttgtaattttccataatggaagaagcagccacaaagaaaatgaaaagacaatcgacatgttgggatcaagtatttgt'.
'aacatacaacaacaaagtggcatcctcagcccattaggtgctctcataggctgctccagagccccacagtcctgccc'.
'ctgccagtctaccactcctcgaagcacgcgccgctggcataatcagaacctcagtaggaaatagacaaaccagatac'.
'cctccccaccaggcaggcgagtgaaagcagaggccagggaccaatctccccaggggccagggcggtgcccactgtca'.
'gagagccataatcagattcagcctggaaatttgatttccccagcagaggcaatgagccaggctggatgagacgccat'.
'cgggggttgggtagagggacagagatagctccccaggctgtccacatgctcactcagtggcacccgctgatcatgtg'.
'agggaccactcccatgtccagggagaatactcagaaagggcctcttcccacgctgctcctgccctgcactaatgcag'.
'tgcccaaggccaaaggtggccaagaccaaagctacactggccaggcccagggggcatgctggatgggaggtccaggg'.
'ggactaggggctgtgtggggctgatacggaagctggggtccggtcaaggcagggtcactgctgggggccagggagct'.
'gggaagcctaaggttagggcaagggctggctctagtggccgaacgagcccagtgactgcaggcaggacgtgacaggt'.
'gagcaggcagggcaggcgagtgtcccagcaactgtccctcctctgtgggaggcatgagccacagggagccactgctg'.
'gaggtccctaaagggtctgggcttaagattctcaatccagcaggtcacagacacctgctccctgtgccaacagcagc'.
'atcctttaagtctccttggtctcctgagacctgcctctccatgaggagacatgagatggggtggaaaggagtcctcc'.
'aggtcccgattcaaaacagcccccaatgcccttcctgtgcctgacccagactctagctacagctgcagcagtgggtg'.
'gtcctgcagactccaagccgtggagtagtggcagtgaggggccacattctctgggctccctgctgcatcctgcccag'.
'ggcaccaccaagggctcaaaggctggggagctccagggagagggctgcagaggctgccagtgcagtgtcttctcccc'.
'tgcacactcagcccacccactccgcccccaatgatgagcatgaagtttgtaggagtgtggagaggtgtagtgcccta'.
'ctaagtgggccggacattggtggcggtggctggcccattgcctccacggcttaccgggacgggcacccaccccgcaa'.
'ggtgccgtgtggcccatgccctgccttagggagggcaggcgcagtggaggcggaggcggggtgtaaaaggcccagac'.
'atggagctgagccccatcctctgtactctggggtgggcacagggaccaaagcatccctgaggagcgaactgacaggg'.
'ttcacagctaggctgggatcagaggcagacagccacagggcctgggagccctgccctaccatgccctacggccccac'.
'tgaggcactgtaggagacagctgtccaccaggctgaggggcctcagcgggcaggtgcagcagtcaccacgctggcca'.
'ccagcctgagtgcacagggccgtccgcctgcaacgccctttcccccctcattggaagacggggttagaccccttctt'.
'cccagcccctctatcaccatggaaacacccaggcttctcctgagggacagagcctctttgtggtgacacaaagcccc'.
'tttgaggggaggtggggtgcagcccctgggagcctgtggccaaagggcccctggggggtaaagcagggcccgccggc'.
'ccagcccccctcccaggtttcggagccaaggaagctgaggtaggagagccttcaggttaggccagcccgccccagct'.
'gcccacccagaagggtctccggatggatgagccggacagcccaggaggccaggctgaggctgggcagagacagcacc'.
'gagaagcctctctgcaggagctggggggttcctgctttcctctctgttgttttgacaaagaacacactctgcttaga'.
'taagtggaaaacagcactggcaggggagctcccgccagtcaggaaatgcccaggatggctgcaggaacagtgcctgg'.
'tgggagatggggacaggaagtcctccgtgggagggcaggcaggggccgtgagacggcaggtcagacagtgggaggtc'.
'tggcaccaggtgtgccgagaggactggccctggcatctgggccccactcagtttactgtcctctcacttctcaagcc'.
'tcagcctccgtcttcacctatccgcccagggggaaatgtcactggccttgctgcagccacaactctgggacaggcca'.
'gagttggataaaacggaacctcaccatggcttggcttattccagggctggggaaatggaaccctgaggatgatgtgg'.
'gtccctggcacagtgacagcatggctgtcccatccatgctacagccccacagccagggaggcagaggaggccaggcc'.
'acatttccccagactcccagccctggagcccctcctgtactggcctgagagtccctgcccccacccactgactgctg'.
'ctgaccaggcacctggcagctccctgcatgtgggcgccctgcctagaggccctcccgagttgacctcactctgaccc'.
'acagcagctttgctaactaagcccctggggtggggttggggtggggatcactggccccctgcggcagcacgaggagg'.
'cactggcccagggagagatccatccttttgtaggcaaatctacctgactactagggagtggggccaagggctgcccc'.
'cacagggcagtgcctgggtcagcaagcacttgctgcacccccaatggaggccctcaccacacccctcccaacctgcc'.
'ttccccactggcaccccactctctgctgacacctgcaggcacaggggtgggggttgggaccctccagctgccgtggc'.
'agggagtggccatagggtggttgctgtggtggacgtaggccatatggttcagaatggatcagaggatggtgtgggtg'.
'ggagaattaagtctgggctgaccgcaagggatcaggcctgggtggctggagggaggggccgggaccctgagtgggag'.
'ggtgcaaagggagtctctgaggctggagaggctgagggaccactagatgcatgaagttctggaagaaaggggttcag'.
'gctggagacagaaccaccggcaccttcagcctgtgaagccgagagataagacaggtgcaagccccagtgcctcctcc'.
'aaaggaccctcccctgaccttctagaacaaggggacaaagtcactttcccagccatcatcttccctgcactggaagg'.
'ggcagaacgaggacccagcactgagaggtgagcctcaggaaggaggcagtgctgccagcccttggggacaacagcct'.
'gtcccctgaaagtcccaaaacccttgggaaaggtgctcctcactgtacccttctcccacccagcacatcagaggagc'.
'cagtggtgtgagatcttgacccagcatgaagtagagcccaccctgtcatatgcagggaggttccatgtcccctttgg'.
'tctgcccttgccccagggtcctgtgtggcctctggccagcgctggctgctcccagggtgcctggggcaccgctcatc'.
'ccttccagagcctgagctggatgctggccttgccgctcccaaccccctcctctgctgggagccagctccactccgga'.
'gtgcccatggcaacaggcctagacaccaacctccagcaagtgcacaaagtcctgcctttcatatgcaagcaacacag'.
'agggccaggcagggggctgcaccaccccatccagggcagattccaggccctgcagcctcccatctggctcccaccgc'.
'cacataccaggagagcctcgggacttgactgtgtgtccagtccccactacaaagaggtgggagaagtgctgacagtt'.
'tggggccctcctcaaaggcacctactggcacatgtgtgcagccacccacactgctacggtgtgaatgctagtgttcc'.
'ccaaattcacattaaaacctaatctccaatgtgacagtattaagaggtagggcctttaagaggtgattagtgccctt'.
'atatgatcagtgtccttatcaaagcggctcttgagggctggtttaccccttccaccatgagaggacacacagcgcca'.
'tctatcaatagccctcaccagacacggaatctgctggcgcctcgatcttggacttcccagcctccagcactgtgaac'.
'agtatgtttctgttgtttataaaggactccatctaaggtatttggtggcagagcgtgaatgaactaagacacacaca'.
'gacacacacacaagcacacccacgcacagggacccacagctgccccacaggcacacgcaccagcaggcacactcgtc'.
'cacacccatatggctgctgcttatcccacctagaagtcccgacaggccctttggggggtgggggacatcttggctcc'.
'tggtgaagatcagcatgctaggcagaccccattcctgtcttggacaccgggcaaggcagaccccctctgagacccct'.
'gaggccgggtcaagcctgcccctgacaccaagatctgcaggaccccctgcctctgatcccacatgaggttcctctga'.
'gacaggtgggagtggctgggcctgcagaccccgagcttgcacagacccacctgcagggacaagcacaacttacagca'.
'gcctagtgcccagggaagacccttccaccatgggaggactcaggaagccgcttcccgctgagtcacatttagcgcat'.
'ttcttaggaaacagctggtatgtgccctagaaggttaaagacggtgttcaactccgctggccacagaccacaatgaa'.
'aaggagctgctggctgggcacgatggctcatacctataatcccagcactttggaaggccaaggtgggaggatcacct'.
'gaggttgggagttcgagacctgcctgaccaacatggagaaaccccatctctactaaagatacaaacaaaattagctg'.
'ggtgtggtggtgcatgcctgtaatcccagctactcaggactgaggctgaggcaggaggcagaggttgtggtgagcca'.
'ggatcacctcactgtactccagcctgggcaacaaaagcaaaacttcatctcaaaaaaagaaaagaaagaaagaaaag'.
'gagccgctataaataatgaggatcccatggagatttaaaggaaatcccagcagaggcagtaaacagcagactgtaga'.
'aaacacgcagtgtgaggctggagaaagtacactaagacggtcctcccaaccccaacagcaaacaggagagatgacaa'.
'gaggatggtaggagccacagaagacagagcccagggccaaacttccacatgataggagtttccagagcgagaacgac'.
'agacagtgctcttccaaccacagaaaaacggccagaaaccacctcaacaggagtacgtccaacggggctatcagcgt'.
'cagggctggaatctgagttagggtgtgagccttctgtccagaaaagaagcccaggaagtcacggatgtgtctacctc'.
'tggcttttacaattcagtctcatttcctctggctcctaaatgcgctgtgtccacttcgaggtgtagggaggagggtg'.
'cccagctctgacctgcgggctgtgctgaagcctgggcctctctctataccaggccgtctgcaggcctgcaggggctg'.
'catactgtccctctgtaaatgtcagcctcaacacgctgctgcctgctgcctggctcccgtctctcacagctcagaag'.
'ctgttttatgataaaaaagagctgacagctttgttaaaacaaacaaacgcctctcctctctacttgagatcttttac'.
'aaagttaacatcgctctgaaaccccataaggaaaaattatggtgaggtttctggattttcagaggcagcaaactcat'.
'cttacctagagccctggactacccagagaagtagttttaagaaccaaaagaagagaagaattcaggagtaaatgagg'.
'cctggataacccaagggatcctgtgcttgcactgctgggattcaaatttgggggctgccaccaccacaagtttgtga'.
'gaagcccacagcctgcgcatgaagattgtgtcaagggaatagcagctgctgatgtgtggaattgattttttcagcaa'.
'gggcctgcgattctgaatgcattaaggcagctccagttgtctgtagcagtcctctgtcagctgcccattggaagcat'.
'ttttactggctcaggaaattcatgggtttgtggactgatgactccaacagattaggtacaaatccaagaaccacaaa'.
'acaaaatctaaccaagccaaacaacaatcaaacaataaaacagaacaaaaaaaaacctcaatttgttttccttttct'.
'ttgtataacattaaaataaaaagatggtaacagactaccataaagaattatacaccaacaaattagataacccagat'.
'gaaatggaaaaatttcctagaaacacacaacctaccaagactgaatcatgaagaaatagaaaacattgattagattt'.
'acaactagcaacaaaactgaatcagtaatcaaaaacctccagcaaagatggtttcactggtgtattctaccaaacat'.
'tcaagtaattttaacaccaatcgtcctcaaacttttcccaaaaataaagaggaaggaacacttcctaattcatttta'.
'tgaggtcagccttaccctaataccaaagccaggaaaagacactacaagaaaagaaaaccacaggccaataaccctta'.
'tgaatactgaaacaaaaattctcaaaacaaacaaacaaacaaaaaaacactagcaaaccaaattcagctgcatttta'.
'caagaattataaacctaaccaagtgggattttactcctggaatgcaaggatggttccatgtacaaaaatcaatcaat'.
'gtaatacgccacagtaatagaataaaggacaaaaatcacaatcatgtcaaatgatgcaggaaaaacatttaacaaaa'.
'ttcaatagtctgtcatgataaaaacactcaaactaggaaaagaaggaaactttctcaacatgatgaaagctatatgt'.
'gaaaagcccataacatcatactcaatggtgaaagactgaaagcttttctcctaagatcataaacaagacaaagatgg'.
'ctgttttgaccacttccattcaacatagtactagaagttttagacagagtaattaggcaagaaaaagaaataaaaga'.
'catccaaattagaaagaaagaaaaaccatctctgttcatagacgacataaccttatataaaaccgtaaagattctac'.
'atgcattttttaaaaactctattagatgtaaaaaatgaaatcagcaaaggtgcaggataaaaaatgaatacccagaa'.
'atcagttgcatttctatatatgaacaatgaacaacctgaaagggaaatttaaaaaaactattccatttacaatacca'.
'ttaaaaagaatagaatacataatactaaacttaagaaacttaagatctgtacactgaaaactataaaacattaccaa'.
'gaaaaatttaaaaagacctaaatcagtggaaagatatcccatgttcatggctgggaagatttaccactgtcacaatg'.
'acgatactactgaaagggatctacagattcagtgcaattcctattaaaatcccaatgacagccaggcatagtagcat'.
'gtatctgtaatcctagctagtcagaggctgaggctaaagaactgcttgaacccaggggttcaaggccgcagtaagct'.
'aggatcacaccattgcattccagcctagatgacagaacaagacctgtcaaaaaaagaaaagaaaagaaaaaaaaaat'.
'cccaatgacattgtttgcagaaacagagaaatctatcataagatttatatcgatctttaaggagcccaaagagccaa'.
'aacaatctggaaaaagaacaacatttaaggactcacacttcctgatttcaaaacttactacaaagctacagtaatca'.
'aaacagtgtggtattagcataaggacagacacaaagaccaatggaatagaatacagagcccagaaacaaaccctcat'.
'gaatacggtcaaatgaccttcaataaaggtgccaagaccattcattagggaaatgatggtattttcaacaaatgatg'.
'gaactggatacacacacgtaaatgaatgaactcacacccttaccttattacatacacaaaaattaactcaaaataga'.
'tgaaagatctaaacataagacctcaaactataaaactcttagaagaaaatataggggaaagtcttcatgacactgga'.
'tttggcaatgatatcttagataagataccaaaaacacaggcaacagaaggaaaaataaattgtactacatccaaatt'.
'taaaatgtatgttcatcaaaggacacaatcaatatagtgaaaaagcaaccaacagaatgggagaaaagatttgtaaa'.
'tcatatatctgaaaaggaattcatatccagaatatgtaaagaactcccaaaacttaacaacagcaaaaaaacacaaa'.
'taacccaatttaaaaatgagtggagttgaactgacatttctccaaagaagatatataaacggccaacaagcacgtta'.
'aaaaatttgctcaacatttctatcattagggaagagcaaatcaaggctgcaatgaaatatcaccttacacctattag'.
'gatggctagtctaaaaaaaaaaaaaaagttttggcagagatacagacaaattaagacccttgtgcactgctggtggg'.
'aatgtaagatcagtatggcaattcctcaaaaaattaaaaatagaattaccatatggtccagcaatcagaaaattctg'.
'cattatgtatctaaaagaattgaggccaggcgtggtggctcacgcctgtaatcccaacactttgggaggccgaggcg'.
'ggtggatcacaaggtcaggagatcgagaccatcctggctagcacggtgaaaccccgtctctactaaaaacacaaaaa'.
'aattagccgggcgtggtgacaggcgcctgtagtcccagctacttgtgaacttgggaggcggagcttgcagtgagcca'.
'agatcgtgccactgcactccagcctgggcggcagagcgagactccgtctaaaaaaaaaaaaaaaaagaattgaaagc'.
'agagtctccaagagatatgtgcacaatcatattcacagcagcattattcacaatagccaaaaaggggaagcaaccca'.
'agtgtccaccagtggaaaaatggataaacaaaatgtggtatagatatacaatggaatatcaggcatcaaattctgac'.
'atatgatattctcatgatactaagtgaaataagccagtcacaaaaagacagatactgtgagattctatttatgtaag'.
'gcatctaaagtagtcaaacaataggaaaagtagaagcacttcaagaaaggggcaaacggggagttttctaatgggta'.
'cagagtttctattttgcaagaataaaaaaaagttctgaaattggttgcacagcaatgtgaacaaacaacactactga'.
'attgtacacttgaaaatggttaagatagtaaattttgttatgtgtattctaccataattaaaaattaaaattaaaaa'.
'agaggctccctggccaggcgtggtggctcacgcctgtaatctcagcactttgggaggccaaggcgggcggatcacga'.
'ggtcaggagatcgagaccatcctggctaacatggtgaaaccccgtctctactaaaagtacaaaaaaaattagccggg'.
'tgtggcggtgagcgcctgtagttccagctacttgggaggctgaggcaggagaatggtgtgaacccaggaggcggagc'.
'ttgcagtgagccgagatcgcgccactgcactccagcctgggcggtagagcgtgactctgtctcaaaaaaaaaaagag'.
'gctccctcacataataagtaagaaattgcataatacccttttatttatttattttttgagacggagtcttgccctgt'.
'cgccaggctagagtgcagtgg';
return $seq;
}
