


BEGIN { $| = 1; print "1..4\n"; 
	use vars qw($loaded); }

END { print "not ok 1\n" unless $loaded; }


use Bio::EnsEMBL::Pipeline::Runnable::ORF;
use Bio::PrimarySeq;
use Bio::Seq;
use Bio::SeqIO;

my ($seq) =  set_seq();

$loaded = 1;
print "ok 1\n";    # 1st test passed.
my ($seq) =  set_seq();


$seq =  Bio::PrimarySeq->new(  -seq         => $seq,
                                    -id          => 'AI937824',
                                    -accession   => 'AI937824',
                                    -moltype     => 'dna');
unless ($seq) 
{ print "not ok 2\n"; }
else
{ print "ok 2\n"; }


my $orf = Bio::EnsEMBL::Pipeline::Runnable::ORF->new (   -seq => $seq , -length => 50);

print "ok 3\n";

$orf->run;

foreach $out ( $orf->output ) {
	#print "Got at $out\n";
	#print $out->start," ",$out->end," ",$out->strand," ",$out->{'_peptide'},"\n";
	}

print "ok 4\n";



sub set_seq {
#embedded sequence! Because I can't create Bio::PrimarySeqs from files
my $seq = 
'cctgggctgcctggggaagcacccagggccagggagtgtgaccctgcaggctccacacaggactgccagaggcacac'.
'acctgctctgtctacccgagggcaccagagggcacgagaaggctggctccctggcgctgacacgtcaggcaactgag'.
'gcacaaggctggcatttctgaaccttgcccctctgcaaacacaagggggcgatggtggcactccaagcaaaggggcg'.
'tgtgggtgctgcaggaggagcacagagcactggcgcccctcccctcccgccctgcagatgccggaggccccgcctct'.
'gctgttggcagctgtgttgctgggcctggtgctgctggtggtgctgctgctgcttctgaggcactggggctggggcc'.
'tgtgccttatcggctggaacgagttcatcctgcagcccatccacaacctgctcatgggtgacaccaaggagcagcgc'.
'atcctgaaccatgtgctgcagcatgcggagcccgggaacgcacagagcgtgctggaggccattgacacctactgcga'.
'gcagaaggagtgggccatgaacgtgggcgacaagaaaggtggggtccgggccagcaggtgctcagctctgggacagg'.
'gacccaggaccaggcatcaaagcccttacaggagaagctgttatcaccccatttccagggggctgggaaccctggga'.
'tatgcccagatagggctggggggctcctctggagtcccagggtgccagggtccctgatgacccctgcaggccctgct'.
'gcctgctgccccaggacaacaggcccccacactcacagggtctgacggtggtgcagttccccttgaactctgttctg'.
'gccaccatgggacctgcctggggaccagtcagacaggttctcctgggcccgcctcccgcttgaacttcagcctgggg'.
'cacaggatgtgttaccgggctcacggagtgactcagggaactagtgccgccccagggccccaaggtgggcggttcgg'.
'tgattcagagagggcagctctgtgttaggacacactggggccagccaggaagggtggaaaagatagggaccagcgtg'.
'agcatagaggctaagggaccatgggagctccaagcgcgctcacagtggggaccaggtcctgggggctggggacacca'.
'gggaggtgaaatacccctccagcgggtagggagggtgggcagaggagggccagcggccaggcatttgggaggggctc'.
'ctgctctttgggagaggtggggggccgtgcctggggatccaagttcccctctctccacctgtgctcacctctcctcc'.
'gtccccaaccctgcacaggcaagatcgtggacgccgtgattcaggagcaccagccctccgtgctgctggagctgggg'.
'gcctactgtggctactcagctgtgcgcatggcccgcctgctgtcaccaggggcgaggctcatcaccatcgagatcaa'.
'ccccgactgtgccgccatcacccagcggatggtggatttcgctggcatgaaggacaaggtgtgcatgcctgacccgt'.
'tgtcagacctggaaaaagggccggctgtgggcagggagggcatgcgcactttgtcctccccaccaggtgttcacacc'.
'acgttcactgaaaacccactatcaccaggcccctcagtgcttcccagcctggggctgaggaaagacccccccagcag'.
'ctcagtgagggtctcacagctctgggtaaactgccaaggtggcaccaggaggggcagggacagagtggggccttgtc'.
'atcccagaaccctaaagaaaactgatgaatgcttgtatgggtgtgtaaagatggcctcctgtctgtgtgggcgtggg'.
'cactgacaggcgctgttgtataggtgtgtagggatggcctcctgtctgtgaggacgtgggcactgacaggcgctgtt'.
'ccaggtcacccttgtggttggagcgtcccaggacatcatcccccagctgaagaagaagtatgatgtggacacactgg'.
'acatggtcttcctcgaccactggaaggaccggtacctgccggacacgcttcttttggaggtgagccccaaccaggat'.
'ggcatccgtgccagctgctgcccagagcccattcagtcagcctcagcctctccaaagagccaggcattccagtagag'.
'ccctgtgtggacacagctcgctctggaggcaccacctgaggtctgggagtgtgggggactgaggaggccctgtggtg'.
'ggtggagatgggtggggagctgggccaggggcctggctgggtggcctgttgggaactggggagccagctgcctgtgc'.
'aggtgcaaaatgggtggcagaagtggggtgcacaccccagaccagacaccagggcagaaacggcacaggaccaagga'.
'gatggggtggggaagggccgctctgggcccagcctgctctcccccaagcaagccactgctcgtgcaaagaaagcatg'.
'tgtctcctgcagatcttcctcctgaggccccatcttgtgcattcccccaacccagccccactggcgaggaccctgag'.
'tgccccgagtgaggctagacagcgggtggggctgtcctcgcttccctggggggcgtggggcactggtggcccttcac'.
'agactgatgcttaaggagcctcacatcagtgacacactgccccatccctccctggtggtcagcgacactgagtggct'.
'ctgtgatcctccactgggcttgggacacccaccctcacggcctctccacctggtgctcgctcacctgcagctctccc'.
'agaaactggacactgctgttagcagccagactaggagcacgaggggcacagcccccatgcctggctaggtagggccg'.
'ctggaccctggacacggattggaaggaaccagcactagcagaagcctgaggtgtgaaagggcagagaatgttccagg'.
'aacaatgggagtcagggcacacaggactttgggcaggtgaggatgaggttagacctgtcttctggagctgggctcag'.
'gggctcatgcctgtaacccttgcactttgggaggctacggcaggaggagcgcttgaggccaggagagttcgagacca'.
'gcctgggcaacatggcaaaagaaaaaatatatatatatattttagatggagtcttgctctgtcaccaggctggagtg'.
'cagtggcacgatcacggctcactgcaacctccacctcttgggttcaagcgattaccctgccttagcctcctgagtag'.
'ctgggactacaggcgcgcgctgccacacccggctagttttttgtagtttagtagagatggggtctcaccacattggc'.
'caggatggtctcaatatcctgacttcgtgatccgcccgcctcggcctcccaaagtgctgggattacaggcgtgagcc'.
'actgcgtccggccgtattccagcttttaaaacaacaaaaaacaacaaaaacttttctggaaagatccctgtcagcct'.
'tgtggagtgtggagagggctgtggggagggcatttcagatgccctgaactcacgaggaggcactgaaccctggccgt'.
'ggagagggaggacctgtagtggccaagggggtgggcattgggagggtgggagggagacctacaggccaagacagggt'.
'agctggaggggggctcacccctgacaaaggagcatgatgctggcaattgggtattgatggcagagagctggcactca'.
'gccagatgggcttcacttgggcaggaaagacacccacagctgggcctgcgttactgcggccgagtttcagcagctgt'.
'gatgtgggtgctaattacaggggcctgccttcatagaaaagtagcaaacattgcagtttagtaactaggaaactaat'.
'agttttctcagtgctgcttgcgcaaagctggtaattatctcaaaagaagcaaagtcatgaagtgggaagtcatgaat'.
'tgggaatgggtgtccttgttaaacgcacatctgcacactcagggctggggccctgtgcccccttgtggagggttagg'.
'ggacaacctggctcttgtgagggtctagccatcccctcagtgggttctgtgagcatcggaggcacggggggtgaggg'.
'gctcaggagcaggttgcaattcaaaatcaagggctgctttgaggaggcctctccaccgggctgctgtagtcaccaag'.
'tccagcccatgcccaaaggaagaggaatgagttcccccttaaaaaaaaaaaaaaaaagaaaaagacagagtcttgct'.
'ctgtgcccaggctggagtgcagtgatgacatcatagctcactgtagcctcaaactcctgagctccagtgatcctccc'.
'acctcagcctcctgagtagctaggactaaaggcatgcaccactacacctggctaatttaaaaattttttgtagaaat'.
'ggggtctccctatgttgcccagactggtctcaaactcctggcctcaagcgatcctcttgcctcaacctcccaaagtg'.
'ctgggagtacaggtgtgtgcttggtctgaggctccaactttttgttgttgtttctcgagacagtctctcgctctgtt'.
'gcccaggctggagtgcagtggcgcgatcttggctccctgcaacctctgtgaggctccaactcttgaagggaggagag'.
'tctaaggagggtgggccagatgaaaaccacctcagcatagtgtcacctgctcctctgacactgtcgcttctccatgg'.
'cattagattttcagtcctgctcagacgctgatgcatgtttagccagttctccaggtggtctgagtagctggtaggag'.
'gcttgcagtgtcgggcgacaggcaggacaggtgctgccttctttcccctcttgaccagtttcgtaaaggagtgggcc'.
'cctggcagcctccaaaggtgacccatgctcctttctgcccttccctccttctttcctgtttaactcgtgcaggtgca'.
'gtggtctggtgtctttcagtccgctgacgtcttctgtatccctgatgaccagattgggctcctgagtcccctggcgc'.
'aacccgagaagtccaggagcccaggcccctcactcatgcattccctggcccagactggaaggcagccgccctgctca'.
'aggcctaggccattgtcctcctcccgggtggcgctttgttctacgtcttttcagctgacattgctaggacatttttt'.
'tttttttctaaatgaaaacacatcatgattcatggtggtacttcctgctcaactccggaccttggggctgtcccctg'.
'acctcactgaccttgcagccgtgtggtgtccatactgtcacatgaaagccccctgctttctctgcagcatacaggct'.
'ggaaacgaccgccacccaccaccaggacagctgcaagccctgtgggactctccaggcccatcccagaggcatgtggg'.
'gtcggataccagtgtttcaaggcacctgcctgcaaattgattttattatactttagatgtttgagattgcttgttaa'.
'cttttgtttggtgactaagtcaaatttccaagacaaggtgactggggtgtcccttgccctggtaggtccttcctccc'.
'cataggcaaacacttcctctcaaggtttcttgtttatgtgatgtaagcaaacccttttctgatagcatagataggca'.
'agcatcctatgaggtttctcccgatagtggaccccacgggccatgccctatggctgcgtgtccagtaacaactcctt'.
'ccttctgcacagaacccaggcagaggaactctgtgtcctcccagggcccaggcactggtgaagatggggggtctgca'.
'aatgcaggagcttggggatgtccagaactgaccccaaggggcaggcttgttgatgggaggtctgccccacctcagcc'.
'ctgcagggtcaccctggtcaggccaatattgtctccagggaccataccagcaacccctctccttgggtgcctctccc'.
'tcataggcctgagttcctggcactgggtgttgagggccccattgtttccactcacccagctagcatttattgagcac'.
'ctactgtgtgccacatgctgttctaagggatggatactcctgagatggatacaggagttgatgagagaaaggtccct'.
'gtcctcacggggcccatgttctgaaggtggcacccaagtcttgtacagtcctttcctgcaggagtcacgctgggcag'.
'aaagtggaaacctggccccaggggctaggcacaggcgtggtgccgtggcctagtgaggagcacccatcctggtttgg'.
'ggcaggttctctgggcacctctgaccctcacctcccccaccccccggtctgtttgcaggaatgtggcctgctgcgga'.
'aggggacagtgctactggctgacaacgtgatctgcccaggtgcgccagacttcctagcacacgtgcgcgggagcagc'.
'tgctttgagtgcacacactaccaatcgttcctggaatacagggaggtggtggacggcctggagaaggccatctacaa'.
'gggcccaggcagcgaagcagggccctgactgccccccccggcccccctctcgggctctctcacccagcctggtactg'.
'aaggtgccagacgtgctcctgctgaccttctgcggctccgggctgtgtcctaaatgcaaagcacacctcggccgagg'.
'cctgcgccctgacatgctaacctctctgaactgcaacactggattgttcttttttaagactcaatcatgacttcttt'.
'actaacactggctagctatattatcttatatactaatatcatgttttaaaaatataaaatagaaattaagaatctaa'.
'atatttagatataactcgacttagtacatccttctcaactgccattcccctgctgcccttgacttgggcaccaaaca'.
'ttcaaagctccccttgacggacgctaacgctaagggcggggcccctagctggctgggttctgggtggcacgcctggc'.
'ccactggcctcccagccacagtggtgcagaggtcagccctcctgcagctaggccaggggcacctgttagccccatgg'.
'ggacgactgccagcctgggaaacgaagaggagtcagccagcattcacacctttctgaccaagcaggcgctggggaca'.
'ggtggaccccgcagcagcaccagcccctctgggccccatgtggcacagagtggaagcatctccttccctactcccca'.
'ctgggccttgcttacagaagaggcaatggctcagaccagctcccgcatccctgtagttgcctccctggcccatgagt'.
'gaggatgcagtgctggtttctgtccacctacacctagagctgtccccatctcctccaaggggtcagactgctagcca'.
'cctcagaggctccaagggcccagttcccaggcccaggacaggaatcaaccctgtgctagctgagttcacctgcaccg'.
'agaccagcccctagccaagattctactcctgggctcaaggcctggctagcccccagccagcccactcctatggatag'.
'acagaccagtgagcccaagtggacaagtttggggccacccagggaccagaaacagagcctctgcaggacacagcaga'.
'tgggcacctgggaccacctccacccagggccctgccccagacgcgcagaggcccgacacaagggagaagccagccac'.
'ttgtgccagacctgagtggcagaaagcaaaaagttcctttgctgctttaatttttaaattttcttacaaaaatttag'.
'gtgtttaccaatagtcttattttggcttatttttaatgctttttctcagtgtttttcttctgtttctgagtcacgaa'.
'cagcaggcactgaaagcagtcccccagccactgccgaaggtcagtcccggaggtgctgcccaggctccaggcagatg'.
'cggcagccccggccacagccagcatgggctggagaaaggctctctactgcacaggggcctcacgtgactgcagggct'.
'ctggggaggtggggcacctgtagcctgacccccaccttgctgcttccaaagcttccttgcccagggctgagccttgt'.
'ggggcaccccccacactgtggtctgcctgcctgcagggtgcccagggagaccctccgcctttagaagtccaagttct'.
'ttcccagccccctccctgcctagctgcctgcccctggcgccagacctggcccgcaccactggggcactgtgttccca'.
'ggggcaccctcctatcccaccagccccaaagcccagccaggcacccttccctgccacctccctgggccctgccccag'.
'cagcccagtcggcctcctcgggccttctgtcactcgctcacacacagcaccatgtcagtaaacagctaactcaggcc'.
'tagggagttaggtaggatggggggagtggggtgggggggcaggagggtgtccccaaagtcaggcttggctggggcga'.
'ggcgctgccaacccctgccgccagggggctccaagctccacggcacgatctgctcagggtggcccttcttccacgat'.
'ccaagccctaagaacaagaggctgggcctgggccctgcagagggaaaggggatggtggacgctgcagccactgagtg'.
'gcacaggaccacgtgtaacctcagggcagggcagccaactccacaggctacatggatggagatgtggatagaagcat'.
'ctgccctgggtggtgtgggctgaccccaagggtcttggcaccagggctgatcctgacttgctggtccccgaagggcg'.
'ttggagggtatggtgcccatccctactctggtcccatttcctcaggcccctgatcccacagtgcctgggacagggct'.
'gtgggcccagggagcaccctccctctctgacctctgcctggtctttccgggaatgggccactgggctgctggactgg'.
'aggccaaagtcctgcggggaacgtgcgggaagagcagagcgtgcaggcagcagagactaacaagaagccctggccca'.
'gagggcaggaacaggtggacgaacaaccagatgagagaacgtaccaggcatgcaagctagacccaggaatcaacggg'.
'ctgaggcttagcgtcccctacggcgtccaccagcctgaccgcgggcctgctgggcccggggggaggggccttcctgc'.
'tggggtcgagctgcagcgcacgggtgggcattagaggcacaatagagcaggttagttagagctcctggggggacagg'.
'gcaggggcagggccgaggctggcgatgtaagggttggcctgccaggacagcacaggtagcaccaagggcgcagggag'.
'ccggaaacgtgtggctcacacgggcccagggcgggcacgtgcacacacacaggcctgcacaggaagccaggggattg'.
'gcacacagcaggcagcaggtcctgccatcgctggtggaccctggtgggctctcacacgcacatgcacagaagggtgc'.
'acacacactagctcacaggctctggcccatgcagggtgtggccgggcagtgttgtccccagtgggtgggagctgcaa'.
'acttgtcagtacccacagactgactggcgtgaaggggctgcttcctgggcttggccccacaacccagctgtacccca'.
'gggcccagaccagacccagcatggcctaggctgctctccagcaacccctagacacagggcctcaccggggacctgcc'.
'cacagccacatgaccacttactttcaagggttccttctcagaggcctctcctgcagagctggcgccccgtggcctcc'.
'gctccctctggtccaccgtggagtatccgtctgtagatggggtaaggtggggcatgaggggcgctctgagggaggcc'.
'ctgtaggagcagatctccctctcagcccagacacaggggactcgtgggacaggggctttgggagacagcccccaccc'.
'accctgtcctggagatccaggctggtgccagctctcaccaacaccctgccaactctccagactcccctccacttgtg'.
'ggtcagagcccctggctgagcactaatccctctctagctgccctgtacctcaccctctaagcacccctaaaccaaat'.
'atctctcctccacccagcaccatctacaccccataaaaccagcaggcccacttcaggccttggtcccctcccggcac'.
'agaaaaccaaccacactgcatctgcactcacctgggcccagcgcatccatggggatcacatcccggctgccagtttt'.
'ctcgccctctgcaaggcaggaggaggaggcgggctgcatgtggcagccaggggggatcggggcagagaagcccacac'.
'agggctggcccaggtagccctagaggctctctgtcactaaggtgcccaacctctgccagctggcagcctcaccccag'.
'cttgacaacagcgcggatgctgtgggaagggagtagccaagaggcagagggcagggaaagtggcctatggaagccgt'.
'ctcagtgggaggcctgactcctccttcaccctcacccaagggtcaggcaactggggcagctggggtcgccaccctct'.
'aggctccctaagctccaccactcaccaaggctcttgtccaccagtggcagcgtgctgtcatcgaagcccccaggact'.
'cagtgctcccttaggccccttggcagtagcagcagctgactgagacataaaacacagacacagggtgggtgaagcac'.
'atggagtgggaataaggcaaagtgagcagggaatggaaggaaggccagggaagccgcacctggaagcgcgccttggt'.
'ccaaccatctttctgcaaggtaccacgcagctccttgtagctccacactgtctgcagcacgtgtgacgccgccttcg'.
'cttcgcgtaccgattggctgtggggccgggggcggggtcagtggtggcccctcccccacctccgcggctccccaagc'.
'caccgaccccgcccctccacacctggaggccacgagagccaccaacgctggcaccccgcgtgcctgcaggagcgagc'.
'gcgcgttatccaggctgtcggacacgatttcgtggatggtgttgagcaccgccaccacggtgtcttcctccaggcag'.
'gcccccggtcgcggcggagcctgtgcattgcgcacattccgcacaagctcagccatggcgtagctccctgaggggca'.
'ggactaggtgtcagaacacacctctgccccacctctccaggaaggagcagggatcccgcgagggcgaggggcactgc'.
'caggagagcccctggagaccgcctgtgtgcaggcggtcacaggagcccctgtgagcagggcgctgagcttcagagac'.
'agggccggggggactggagctacctccagttgggacagcgcccaagcgagagggccggggcctggactcccaaacca'.
'ctcatcctccaagcccctccgatgggaccccaaagctgcaggcacagttcggtgcccaggcgtgggctttgcaggcg'.
'tcctcaccgatgaggtctttgttgcgccggtccagcgagaggttgcgcagagcgatggcgacggcgcgcaccacctt'.
'gtcggtctcagactgcagcagttccacaagcaccggcagcccgcgctctttgcgcactgtggcgcggatgtacgtgg'.
'cccactgcggaggcggggagagggttgctcagacatacatgccaggcactctcccacctccagacgctgaccgctct'.
'ctccagctggaccttcctgctcccgtgcccgacaaagccctaccccaaaagctcaacggcacctccaccgaggtttt'.
'cccaccgtccagggtgcacgcattgcccgcagcccatacacctcttggatcctggggtggtggtgtggcccctcctt'.
'tccccgccagccgaggcaggagctgcaccagtgaggtgcctgggattccctctctcaggacttgcccaccctgcccg'.
'acctggtccctcaccatccagttgccggcactgaggttctgcagagcgccggcggcagcctccagggtgttgaagtt'.
'ccggctctccgtgaggagggagaggtagagacgtaccacctcgggctggtacagcagctcaaagcctaggtgcaggg'.
'caaccgccacccacggtcacccagaatctgctctcatccatcatacccctcccgcttcccgcttcagagctcccagg'.
'gcgtgggtgagctggggccagggatgggtgtggatgagtcacgtaatatttactatcaacatatagtcacccaaggg'.
'gaaaagcgttcccatttcacagaggagcaaactgaggctcaaatcagttggacctgcctggcagcaggagcatccag'.
'gaggcctggggtggggagggaggtgtcaaccaggaacgctctcctagcaacaagacccgcatttcccggtaggtccc'.
'tgaagctatgcatcctggccacgcccctggtaatagggcccaccctccctggcaacaagaccagcattggccagtaa'.
'ctgagagttgtataaccaaggccacacccctagcaagaggacctgctttcaccagtaactgaagctgtgcagagagc'.
'tacgccccctagcaacagggcccaccctcccccactgacaatagagcccaccctctgtaagtcaactgatgcagtgc'.
'aaccagggcagctgccctagcaacaggaggcactcttcctggcaaccactccaagttcccgggcaattgaggcgccg'.
'tcctgctgctctgcccagtgctccagaaatgaggggtcaaaacagccttccaagcttgcctgtctccaaactggggc'.
'ttcagcctggcttgggtactacctcgatctcccctgtacccacccagtgacatttcatcacaccctcgccagtcctc'.
'atgccccatgctccctctactcctgccctgctgggctttctgctccaacacactccaagcacactccccgctggggt'.
'atctgcatcagccctgctctgcctgtaatactcccccacagccctcctgcggctggagccctccaccctggtgacat'.
'gcaggctcttccaactggctaggccccaccaggacagacctctctctcaagccagatcccagcatacagctcaatag'.
'gcactgccctgcccctgcaggtgttcgtctggcccagcctctgaacctggatgtgagcatgcccgcctggctcccag'.
'ccccctcagataactcagctttgtggctaacacaggaggccctgcctccactggaggcgtccctccaaaccttccca'.
'cctcttacgcaccgtgaggccgagcaagccctctgcctctctgtgcctgtctcccccaaccttgcctgacatgaccc'.
'atggcacttcctcccattctaaaccctcagcaggtgtcctggtgctgaatcaccctccaggaaatcctgcacctagg'.
'ggcctgtttccccatctgttccctgaggccctccaggcctgcttgatggctcaaagcttcactaccagggcaatcct'.
'gagcccagacatcccccagtggagctggcttcatctcagcccactcacctttggcggcctcagttcgcttgggcagg'.
'tctagcgtgtcaaagttccggtccatctcaccatccttctttcctggaagggaaaggtggtgggaggtgaggcagac'.
'cccatatggggaatgggtgtatcaggagagttgggcacagttctctcctacccaggccccaaaaggcacccccatgt'.
'ccaggcctgggcacctgtgggagtggagcaccgttgtcagagtttgggcagacagtttagcctaggggtaggagttg'.
'gtggcagtggggcctggggatgtcccagccctgcccctaggactcatctcccaccaggtgctgggagctgtaccaca'.
'gaccctcccggtggctcccttgcaactgccaggtatgtagactgagggaagccaggagccctggctggatggtaggt'.
'ggatacaagccaagaaactgaaggctgaccaggacaagactcatttgggtcacacagtaaggcagaactagggggaa'.
'actcccccagctggggtcaggacattgtcccaggatctactagccaggagaaaccccacagcagcccacctaacatt'.
'tgtgtagccctggcttgcacacgtctgtgacagtgagcccactgtcaaccactctccccatgtcagatgatgcttct'.
'accccttcagaaggcagcagagtggagccagatgacctggggtccctgccctgctcaccctcatgggacccttgtat'.
'ccctccgagccacatgatgccccattctatcagagaaacagactgctccttggtgcccctagagataagtacccccg'.
'ggccctgcccactcttggctctgcccaactctgcccaggtaggcaagtctgaggttacagaatgagccccgtggcct'.
'tcccacctgccactgtcataaagatggcagcccgagtgatgaagccaggggtggggcagggccctggggctggaacg'.
'tgctcgcctcttcccaggtacccactgcacacgccaggcctggagagcaggataaaaagggactcaccttggtggaa'.
'ccactcctctgggaggccggaggaagcagaggagagaggagaggagcctgaacaggcagcactcatcacccccccat'.
'gccctcccggaagcctcaggttcccactgcacaccctggatcaagcaggcagcatgtggaacctcatcccatcactt'.
'ctgggcactgagcacccaccagggggacaagaagagggaggcctggggtcagtggggcaggggcaggtggcgtacag'.
'gtcccccacagctgctggggaggtcctgggaacctacaccctgctagtgcagtagagaaggtgtgcagggcatcttg'.
'cccaggcagatgggggctgccccacaggttggtggcagtctacagctattctgtgaacagtgagcaggcagcagcca'.
'tggctccttcccaactcatgggcaagtggaactctccccggagtagaaagactgggtctgggcattggttggtttcc'.
'cttgtgtactccctgggggtcccacagtgtagatggggaaggttggacctgggtcccatcaaccatgtgacccaggg'.
'cagtccagcctccttgactcctggcttccctgcctgcctgttgggggctgaccaggtgtcctctagcctccatgatg'.
'ggctgctgtgggtgtacagagagccttccgctggggcaggagttgagatggtagagatgataccccagtccgcccca'.
'cccacctttggccttcttgcctccaaagcagctggcatcatcccgcctccggcgctgggagcctacagcactgccca'.
'ggggcccgggctcggcctcctggtacctgtcggccccgggcacctccttgtgcacgtggtaggacaggttccgcatg'.
'atgcacacgcagttctccaccgactgcagggagaggtgagtgggtggggcagggcaccctaggcacagggctggccc'.
'tcaggaaagactggccacagctggtgtgcatgagggcaccgggagcaaaggaacagggagtcctcagtggaggggag'.
'caaaagggcggtaaccgccaggaagggtccatgggaggaagcctctgccctcacggcacaccttctgcctgcaggac'.
'ggtgcccacttcagtgtggtcactgcgaggcgggccacacccagaacgccaccccagacccacaagcccattcccct'.
'gtgctgctcccacagttccagcctcctgggacctgcatgatcgtctctccagcccttggtatgaggctgtgaccgtc'.
'cctgcccaccttgttgtcagtgtccttccggcccacagccgactgcagggcatgcaggagcgcgtccaccagccctt'.
'cacactcccggagtcgccgccgggcctcagcaccatcggagctcacattcctgtgtggccaagagcaggccaggtga'.
'cccctggctaccagaaactccctggctccaccctggccttgtgggcttgtcttcatctgcaaaataggccctgctgc'.
'tgccctcctagcactaatgggaaaggaccccacagtctggagctcagtgaagggggagaagctaactgcccccaggc'.
'ctcaggaggggagccctggcagacaactatcttggctggggatagctgggcagggaaagacagggtttccctgcctc'.
'ccagctgacctggaaagggacaggtgcactctcagagagacctgaacctgtgcaagggcaattctgggtccctcgcc'.
'accccaatggcagctctgggccccaccttaccccaaggtcaagagcctgcagggctgcgcgggaacaccctgatgga'.
'caagcaggactgtggggacccaggactctgtggggtcagcagggcctcccaggggtaggaggggaagggcagaggtc'.
'acaggtggctgggatgagcctcccaggcagatgaacaggaaggtcccagctccccctctggctgtcaagtgatggga'.
'aggtaggtgagagctgggcagggctacggtaccacagagacccctccagagggtgcccctgggaagactgggacacc'.
'acttgggggtgaggacagctccatcaggccccacttctcatccacaggacttgtgccacagctctgaagctcctaag'.
'ctctggcgctcctaagctcgccgccatcttccacactatctgggaccacgaggacggggcctggtgtgcatgtgggc'.
'tttagcaccaggtctggtccacacctcaggcagcccgacgtgttcttgaagacagttgtccactcggcgtcccgtgg'.
'cttggagtcctcgttgggctcacgctcccatcctgagtggggcacgatcacctcgtgggtcagcgtctgcaggccat'.
'ggtcaatgatgaccatcttcaggggctcataggatgacaggttccacagggtgcctgtggggtgcgattggccaatc'.
'tgtgctgaccatatgcaccgcctgcctacctccccaggtggccacgctcaggacctgtcccactctcctcatgtccc'.
'agctcatgcagaacagtaggaagtaacaaaagccgtgagtggttccgggggacacccagtactggtttccagctagg'.
'aaggagccccaaaggggaggaggtgcagaggagggtgtggcagtgctgtcccgtcccacccattccctgccatgtgg'.
'caggtggcactaacactcctgaggccacagggcctcacagagacacggtgaccctacctgtccctcagctctcacaa'.
'ggcacaagccccaccactgcacggttggggtgggaaccaaggaggtgggtcccaggagagtttctgtgggggcagga'.
'ggtgtgaaggcaggaggtgaggggacatgcccgaggggcgcagcgtcagcctccctactatggtagagactggggaa'.
'cctgtcacagtgtctgggcctgatgcctggctcctggggcaagcgtctcagcagctgcactcctgcctaccgggtgc'.
'tttcccaggcggtcgcaggccgagtggcctcgttcctcccgggttgagcctcacactcttctcttcccaggggatgt'.
'gagcatggccaggtcccactcaccagtgacaagctcacggacctcgttgtcccgggcagccctcagcaggcgcacca'.
'gggcaggcacaccaccgcagtcccggatggcggccttgttgtcagtgtcgcggccataggagaggttgcgcagtgcc'.
'ccacaggcccggcgccgcacctcagcccgcgggtggtccagcagtgccacaagcagcggcagcccccgcaactgccg'.
'tacacgccgcttgacaccctcgttctcaaagcacagatgctgcaggtaggcggccgcattggccttcacggggtcca'.
'cggggtgccgcagcatggccagcacctcaggcagctcagggtcccgccagcgcggctccttgcgggcgctatccact'.
'gagggcgagcgccgcaccagccggtccaggctgcccatgctgccccgttcaggctgggccaggggcgccgtcaccat'.
'tgggaacgcaggccgctcgtccgccagctcgccgccatcatctgctgtgtcctcgtaggccctgcacaggcaagtgg'.
'ggcgcgtggacatcgtcacagcagccgccagccctgcctctgagctgccccatcacaccttcttcaggactgcaaac'.
'tcacccagcagcgctgggctgagagcacctgtatcttggcccggagcatggtggggacacagagagtcatgcaccag'.
'cccagtgagaaccaattcagagccaaatgccaaaccccagccagcggctaccaggacccaggcaaccctcccaggac'.
'agcaaactcactcactgctgtcaccgggcagtttcccaatcccgagcaaaacaagtttctgtgagacatctgctatg';

return $seq;
}
