#!/usr/local/bin/perl


# Copyright [1999-2016] Wellcome Trust Sanger Institute and the EMBL-European Bioinformatics Institute
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#      http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


use Bio::EnsEMBL::Analysis;
use Bio::EnsEMBL::Pipeline::Rule;
use Bio::EnsEMBL::DBSQL::AnalysisAdaptor;
use Bio::EnsEMBL::Pipeline::DBSQL::DBAdaptor;

use strict;
use Getopt::Long qw(:config no_ignore_case);

my $host;
my $user = 'ensadmin';
my $pass = '';
my $port = 3306;
my $dbname;
my $logic_name;
my $inputclass;
my $dependents;
my $type;

GetOptions(
            'dbhost|host|h:s'     => \$host,
            'dbport|port|P:n'     => \$port,
            'dbuser|user|u:s'     => \$user,
            'dbpass|pass|p:s'     => \$pass,
            'dbname|db|D:s'     => \$dbname,
            'inputclass:s' => \$inputclass,
            'dependents:s' => \$dependents,
            'logic_name:s' => \$logic_name,
           );

my @dependents = split(/:/,$dependents);

print "Adding new analysis to pipeline for [$logic_name] Dependencies are @dependents\n";

my $db = new Bio::EnsEMBL::Pipeline::DBSQL::DBAdaptor(-host   => $host,
                                                      -user   => $user,
                                                      -pass   => $pass,
                                                      -port   => $port,
                                                      -dbname => $dbname);


my $analysis = $db->get_AnalysisAdaptor->fetch_by_logic_name($logic_name);

if (!defined($analysis)) {
  die "No analysis defined for $logic_name\n";
}

my %analhash;

foreach my $dep (@dependents) {
  my $ana = $db->get_AnalysisAdaptor->fetch_by_logic_name($dep);

  if (!defined($ana)) {
    die "No analysis defined for $dep\n";
  }

  $analhash{$dep} = $ana;
}

# Make rule

my $rule = new Bio::EnsEMBL::Pipeline::Rule(-adaptor => $db,
                                            -goal    => $analysis,
                                            );
# Make rule conditions

foreach my $dep (@dependents) {
  $rule->add_condition($dep);
}

$db->get_RuleAdaptor->store($rule);

