#!/usr/local/bin/perl

BEGIN {

unshift (@INC,"/nfs/disk89/michele/pogdir/ensembl/ensembl-pipeline/modules");
}

use Bio::EnsEMBL::Pipeline::LSF;


my $lsf = new Bio::EnsEMBL::Pipeline::LSF;


my @jobs = $lsf->get_all_jobs;


foreach my $job (@jobs) {
	print($job->id . "\t" . $job->status . "\t" . $job->submission_time . "\n");
}
