#!/usr/local/bin/perl

use Bio::EnsEMBL::Pipeline::DBSQL::Obj;
use Getopt::Long;

use vars qw(@ISA);

@ISA = qw(Bio::Root::Object);

my $status;
my $id;

&GetOptions( 
	     'status:s' => \$status,
	     'id:s'     => \$id,
	     );

die ("Input id or status") unless ($id || $status);

my $db = new Bio::EnsEMBL::Pipeline::DBSQL::Obj(-dbname => 'pipeline',
						-host => 'ensrv3',
						-user => 'ensro');

print("Connected to analysis database\n");

my @jobs;

if ($id){
    push(@jobs,$db->get_JobsByInputId($id));
} elsif ($status) {
    push(@jobs,$db->get_JobsByCurrentStatus($status));
}

print("Got jobs\n");

foreach my $job (@jobs) {
    $job->print;
}

