#!/usr/local/bin/perl

BEGIN {

unshift (@INC,"/nfs/disk89/michele/pogdir/ensembl/ensembl-pipeline/modules");
}

use Bio::EnsEMBL::Pipeline::LSF;

my $user = shift;
my $lsf  = new Bio::EnsEMBL::Pipeline::LSF(-user => $user);

my @jobs;

foreach my $jobid (@ARGV) {
    my $job = $lsf->get_job($jobid);
    
    if ($job) {
	$job->print;
    }
}
