#!/usr/local/bin/perl

BEGIN {

unshift (@INC,"/nfs/disk89/michele/pogdir/ensembl/ensembl-pipeline/modules");
unshift (@INC,"/nfs/disk89/michele/pogdir/ensembl/modules");
unshift (@INC,"/nfs/disk89/michele/bioperl-live");

}

=head1 NAME

Job_submitter - looks at the analysis database and
submits a chunk of jobs.


=head1 SYNOPSIS

    Job_Submitter

=head1 DESCRIPTION



=head1 OPTIONS

    -host      host name for database (gets put as host= in locator)

    -port      For RDBs, what port to connect to (port= in locator)

    -dbname    For RDBs, what name to connect to (dbname= in locator)

    -dbuser    For RDBs, what username to connect as (dbuser= in locator)

    -pass      For RDBs, what password to use (dbpass= in locator)

    -chunk     The number of jobs to pull off the queue and submit
=cut


use strict;
use Getopt::Long;

use Bio::EnsEMBL::DBSQL::Obj;
use Bio::EnsEMBL::Pipeline::DBSQL::Obj;
use Bio::EnsEMBL::Pipeline::DBSQL::Job;
use Bio::EnsEMBL::Pipeline::SimpleJob;
use Bio::EnsEMBL::Pipeline::Runnable::CloneExonPair;

use FreezeThaw;

my $anahost     = 'obi-wan';
my $anaport     = '410000';
my $anadbname   = 'analysis';
my $anadbuser   = 'root';
my $anapass     =  undef;
my $enshost     = 'obi-wan';
my $ensport     = '410000';
my $ensdbname   = 'ensembl';
my $ensdbuser   = 'ensro';
my $enspass     =  undef;
my $chunk    = 20;

&GetOptions(
	    'anahost:s'     => \$anahost,
	    'anaport:n'     => \$anaport,
	    'anadbname:s'   => \$anadbname,
	    'anadbuser:s'   => \$anadbuser,
	    'anapass:s'     => \$anapass,
	    'enshost:s'     => \$enshost,
	    'ensport:n'     => \$ensport,
	    'ensdbname:s'   => \$ensdbname,
	    'ensdbuser:s'   => \$ensdbuser,
	    'enspass:s'     => \$enspass,
	    'chunk:s'    => \$chunk,
	    );



my $anadb  = new Bio::EnsEMBL::Pipeline::DBSQL::Obj(-host   => $anahost,
						    -port   => $anaport,
						    -dbname => $anadbname,
						    -user   => $anadbuser,
						    -pass   => $anapass);


my $ensdb  = new Bio::EnsEMBL::DBSQL::Obj(-host   => $enshost,
					  -port   => $ensport,
					  -dbname => $ensdbname,
					  -user   => $ensdbuser,
					  -pass   => $enspass);


my @jobs = $anadb->get_JobsByCurrentStatus('CREATED');

foreach my $job (@jobs) {
    
    print("Id is " . $job->id . "\t" . $job->analysis->module . "\t" . $job->input_id . "\n");

    my $input    = make_clone($ensdb,$job->input_id);
    my $module   = $job     ->analysis->module;
    my $runnable = "$module"->new(-clone => $input);


    my $simplejob = new Bio::EnsEMBL::Pipeline::SimpleJob(-jobobj   => $job,
							  -runnable => $runnable,
							  );

    $simplejob->submit;
    $simplejob->store;
    
}


sub make_clone  {
    my ($db,$cloneid) = @_;

    my $clone = $db->get_Clone($cloneid);

    foreach my $contig ($clone->get_all_Contigs) {
        my @genes    = $contig->get_all_Genes;
        my @features = $contig->get_all_SimilarityFeatures;

        foreach my $gene (@genes) {

            foreach my $exon ($gene->each_unique_Exon) {
                $exon->find_supporting_evidence(\@features);
            }

        }
    }
   return $clone;
}

