#!/usr/local/bin/perl


=head1 NAME

Job_submitter - looks at the analysis database and
submits a chunk of jobs.


=head1 SYNOPSIS

    Job_Submitter

=head1 DESCRIPTION



=head1 OPTIONS

    -host      host name for database (gets put as host= in locator)

    -port      For RDBs, what port to connect to (port= in locator)

    -dbname    For RDBs, what name to connect to (dbname= in locator)

    -dbuser    For RDBs, what username to connect as (dbuser= in locator)

    -pass      For RDBs, what password to use (dbpass= in locator)

=cut


use strict;

use Getopt::Long;

use Bio::EnsEMBL::DBSQL::Obj;
use Bio::EnsEMBL::Pipeline::DBSQL::Obj;
use Bio::EnsEMBL::Pipeline::DBSQL::Job;
use Bio::EnsEMBL::Pipeline::SimpleJob;
use Bio::EnsEMBL::Pipeline::RunnableDB::Vert_Est2Genome;

use FreezeThaw;

my $anahost     = 'localhost';
my $anaport     = '410000';
my $anadbname   = 'pipeline',
my $anadbuser   = 'root';
my $anapass     =  undef;
my $jobchunk    =  20;

&GetOptions(
	    'anahost:s'     => \$anahost,
	    'anaport:n'     => \$anaport,
	    'anadbname:s'   => \$anadbname,
	    'anadbuser:s'   => \$anadbuser,
	    'anapass:s'     => \$anapass,
            'jobchunk:s'    => \$jobchunk,
	    );



my $anadb  = new Bio::EnsEMBL::Pipeline::DBSQL::Obj(-host   => $anahost,
						    -port   => $anaport,
						    -dbname => $anadbname,
						    -user   => $anadbuser,
						    -pass   => $anapass);

my $ensdb  = new Bio::EnsEMBL::DBSQL::Obj(-host   => 'obi-wan',
                                          -dbname => 'ensembl',
                                          -user   => 'ensro',
                                         );

my @jobs = $anadb->get_JobsByCurrentStatus('CREATED');
my $count = 0;

foreach my $job (@jobs) {
    eval {
    $job->_dbobj($anadb);
    exit(0) if $count >= $jobchunk; 
    $count++;
    print(STDERR "Id is " . $job->id . "\t" . $job->analysis->module . "\t" . $job->input_id . "\n");
    my $module   = $job->analysis->module;
    my $runnable = "$module"->new(-input_id => $job->input_id,
                                  -db2      => $ensdb,
				  -dbobj    => $anadb);

    $runnable->fetch_input;
  #  $job->queue('loadfastfarm');

    my $simplejob = new Bio::EnsEMBL::Pipeline::SimpleJob(-jobobj   => $job,
							  -runnable => $runnable,);
    $simplejob->submit;
    $simplejob->store;
   };

   if ($@) {
	print STDERR "Error submitting job. Error was [$@]\n";
   } 
}

