#!/bin/ksh


# Copyright [1999-2015] Wellcome Trust Sanger Institute and the EMBL-European Bioinformatics Institute
Copyright [2016-2017] EMBL-European Bioinformatics Institute
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#      http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


# Must edit the config files in Bio/EnsEMBL/Pipeline/Config first
# Need to configure things like blast header regexp parsing
# Output directories/paths etc

echo "create database " $1 | mysql -u ensadmin -p *** -h ecs2b

mysql -u ensadmin -p *** -h ecs2b $1 < ../../ensembl/sql/table.sql
mysql -u ensadmin -p *** -h ecs2b $1  < ../sql/table.sql

#./dump_fasta -host1 ecs1b -dbname1 human_chr13_fin -host2 ecs2b -dbname2 $1
./fasta2otter -host ecs2b -dbname $1 -fastafile $2 -chr $3 -type $3

./init_Pipeline -host ecs2b -dbname $1

./add_Analysis -host ecs2b -dbname $1 -logic_name RepeatMasker -program RepeatMasker -module RepeatMasker -gff_source repeat -gff_feature similarity
./add_Analysis -host ecs2b -dbname $1 -logic_name MouseBlastz -database /data/blastdb/Ensembl/Mouse_30 -module Blastz_m -gff_source mouse_blastz -gff_feature similarity
./add_Analysis -host ecs2b -dbname $1 -logic_name RatBlastz -database /data/blastdb/Ensembl/Rat_genome -module Blastz_m -gff_source rat_blastz -gff_feature similarity
./add_Analysis -host ecs2b -dbname $1 -logic_name ZfinBlatx -database /data/blastdb/Ensembl/michele_compara/zfin -module Blat -gff_source zfin_blatx -gff_feature similarity -parameters \"-tileSize=4 -t=dnax -q=dnax\"
./add_Analysis -host ecs2b -dbname $1 -logic_name FuguBlatx -database /data/blastdb/Ensembl/fugu.masked.dust.soft.fa -module Blat -gff_source fugu_blatx -gff_feature similarity -parameters \"-tileSize=4 -t=dnax -q=dnax\"

# Testing runnables

#./test_RunnableDB -input_id AL845154.5.1.26737 -runnable Bio::EnsEMBL::Pipeline::RunnableDB::Blat -analysis 6 -dbname $1 -host ecs2b > & blat.out &
#./test_RunnableDB -input_id AL845154.5.1.26737 -runnable Bio::EnsEMBL::Pipeline::RunnableDB::Blastz_m -analysis 4 -dbname $1 -host ecs2b > & blastz.out &

./add_to_Pipeline -logic_name RepeatMasker -dependents SubmitContig -host ecs2b -dbname $1
./add_to_Pipeline -logic_name MouseBlastz -dependents RepeatMasker -host ecs2b -dbname $1
./add_to_Pipeline -logic_name RatBlastz -dependents RepeatMasker -host ecs2b -dbname $1
./add_to_Pipeline -logic_name FuguBlatx -dependents RepeatMasker -host ecs2b -dbname $1
#./add_to_Pipeline -logic_name ZfinBlatx -dependents RepeatMasker -host ecs2b -dbname $1

cd ../modules/Bio/EnsEMBL/Pipeline/

perl RuleManager3.pl -dbhost ecs2b -dbname $1 -dbuser ensadmin -dbpass *** -output_dir /ecs2/scratch1/michele/chr6/out -start_from SubmitContig > & rule.$1.out &

cd ../../../../scripts/

./monitor -host ecs2b -dbname $1
