#!/usr/local/bin/perl

$| = 1;

use strict;
use Getopt::Long;

use Bio::EnsEMBL::Pipeline::DBSQL::DBAdaptor;
use Bio::EnsEMBL::Pipeline::Monitor;
use Bio::EnsEMBL::Pipeline::Config;
my $host = '';
my $port = 3306;
my $dbname = '';
my $user = 'ensro';
my $pass = undef;
my $analysis;
my $current_status;
my $current_summary;
my $finished;
my $core;
my $config;
my @files;

&GetOptions( 
	    'host:s'    => \$host,
	    'port:n'    => \$port,
	    'user:s'    => \$user,
	    'pass:s'    => \$pass,
	    'dbname:s'  => \$dbname,
	    'current_status' => \$current_status,
	    'current_status_summary' => \$current_summary,
	    'finished' => \$finished,
	    'core' => \$core,
	    'analysis' => \$analysis,
	    'config' => \$config,
	    'file:s@' => \@files,
	   );

my $db = new Bio::EnsEMBL::Pipeline::DBSQL::DBAdaptor(-host   => $host,
						      -user   => $user,
						      -pass   => $pass,
						      -dbname => $dbname,
						      -port => $port,
						     );
my $config_obj;
if($config){
 if(@files){
   $config_obj = new Bio::EnsEMBL::Pipeline::Config(-FILES => @files);
 }else{
   $config_obj = new Bio::EnsEMBL::Pipeline::Config(-DB => $db);
 }
}



my $monitor = new Bio::EnsEMBL::Pipeline::Monitor(-db => $db);


$monitor->show_current_status if($current_status);
$monitor->show_current_status_summary if($current_summary);
$monitor->show_finished if($finished);
if($core){
  $monitor->show_analysis if($analysis);
}

if($config_obj){
  foreach my $taskname ($config_obj->get_keys('TASKS')) {
    my $module = $config_obj->get_parameter('TASKS', $taskname); 
    eval "require $module";
    print $module.": ";
    print $module->description;
    print "\n";
  }
  print "\n";
}
