#!/usr/local/bin/perl

use strict;
use Bio::EnsEMBL::Pipeline::Importer;
use Bio::EnsEMBL::Pipeline::DBSQL::DBAdaptor;

$| = 1;

my $dbobj = new Bio::EnsEMBL::Pipeline::DBSQL::DBAdaptor(-host   => 'ecs1a',
						   -dbname => 'mouse',
						   -pass   => 'ensembl',
						   -user   => 'ensadmin');

my $mirror_dir = '/scratch2/ensembl/enspipe/embl_feed/';

my $importer   = new Bio::EnsEMBL::Pipeline::Importer(-dbobj      => $dbobj,
						      -species    => 'mm',
						      -mirror_dir => $mirror_dir);

# This does the reading,parsing and writing of the new sequences

$importer->retain_old_versions(0);
$importer->importClones;

exit;

# This stuff is just proving to myself we have sequence in the database
  
my @clones = $dbobj->get_all_Clone_id;

foreach my $cloneid (@clones) {
  my $clone = $dbobj->get_Clone($cloneid);

  print STDERR "\nGot clone ". $clone->id . " " . $clone->embl_id . " " . $clone->embl_version . " " . $clone->htg_phase . " " . $clone->version . "\n";

  my @contigs = $clone->get_all_Contigs;

  foreach my $contig (@contigs) {
    my $seq = $contig->seq;
    print STDERR "\tContig " . $contig->id . " " . $contig->length . " [" . length($seq) . "] " . $contig->embl_offset . "\n";
  }
}

    
