#!/usr/local/bin/perl

use Bio::EnsEMBL::Pipeline::MappedExon;



my $exon = new Bio::EnsEMBL::Pipeline::MappedExon;

$exon->start(1000);
$exon->end  (2000);
$exon->strand(1);

$exon->has_identical_sequence(0);

print("Identical = " . $exon->has_identical_sequence . "\n");

$exon->has_identical_sequence(1);

print("Identical = " . $exon->has_identical_sequence . "\n");

$exon->has_identical_sequence(3);

